/*
 Generated by typeshare 1.13.3
 */

import Foundation

/// From typescript to swift.
public enum BibtexEditorWebviewActions: String, Codable {
	case requestBibtexEditorData = "request-bibtex-data"
	case setWebviewLoaded = "set-bibtex-webview-loaded"
	case onEditorChange = "on-bib-editor-change"
}

/// From swift to typescript
public enum BibtexEditorWebviewEvents: String, Codable {
	case setInitialColorScheme = "set-bib-initial-color-scheme"
	case setBibtexEditorContent = "set-bibtex-data"
	case setEditorKeymap = "set-bib-editor-keymap"
	case setCodeTheme = "set-bib-code-theme"
	case setCodeThemeLight = "set-bib-code-theme-light"
	case setCodeThemeDark = "set-bib-code-theme-dark"
}

public enum BibtexEditorWebviewLocalStorageKeys: String, Codable {
	case initialValue = "bibtex-editor-initial-value"
}

/// From typescript to swift.
public enum MdxPreviewWebviewActions: String, Codable {
	case requestNoteData = "request-note-data"
	case setWebviewLoaded = "set-preview-webview-loaded"
}

/// From swift to typescript
public enum MdxPreviewWebviewEvents: String, Codable {
	case setInitialColorScheme = "set-initial-color-scheme"
	case setPreviewContent = "set-mdx-preview-content"
}

/// From typescript to swift.
public enum NoteDetailWebviewActions: String, Codable {
	case requestNoteDetailData = "request-note-detail-data"
	case setWebviewLoaded = "set-note-detail-webview-loaded"
}

/// From swift to typescript
public enum NoteDetailWebviewEvents: String, Codable {
	case setInitialColorScheme = "set-initial-color-scheme"
	case setNoteDetails = "set-note-details"
}

/// From typescript to swift.
public enum SplitviewEditorWebviewActions: String, Codable {
	case requestSplitviewEditorData = "request-editor-data"
	case requestParsedMdxContent = "request-parsed-mdx"
	case onEditorChange = "on-editor-change"
	case setWebviewLoaded = "set-editor-webview-loaded"
	case onTagClick = "tag-click-event"
	case setIsLandscape = "set-is-landscape-view"
}

/// From swift to typescript
public enum SplitviewEditorWebviewEvents: String, Codable {
	case setInitialColorScheme = "set-initial-color-scheme"
	case setSplitviewEditorContent = "set-editor-content"
	case setParsedMdxContent = "set-parsed-mdx-content"
	case setEditorKeymap = "set-editor-keymap"
	case setCodeTheme = "set-code-theme"
	case setCodeThemeLight = "set-code-theme-light"
	case setCodeThemeDark = "set-code-theme-dark"
	case resetPreviewScrollPosition = "reset-mdx-preview-scroll-position"
}

public enum SplitviewEditorWebviewLocalStorageKeys: String, Codable {
	case initialValue = "editor-initial-value"
	case parsedMdxData = "parsed-mdx-data"
	case codeTheme = "editor-code-theme"
	case codeThemeDark = "editor-code-theme-dark"
	case codeThemeLight = "editor-code-theme-light"
	case editorKeymap = "editor-keymap"
}
