// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class SerializedString {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):SerializedString {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsSerializedString(bb:flatbuffers.ByteBuffer, obj?:SerializedString):SerializedString {
  return (obj || new SerializedString()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsSerializedString(bb:flatbuffers.ByteBuffer, obj?:SerializedString):SerializedString {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new SerializedString()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

body():string|null
body(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
body(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static startSerializedString(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addBody(builder:flatbuffers.Builder, bodyOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, bodyOffset, 0);
}

static endSerializedString(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  builder.requiredField(offset, 4) // body
  return offset;
}

static createSerializedString(builder:flatbuffers.Builder, bodyOffset:flatbuffers.Offset):flatbuffers.Offset {
  SerializedString.startSerializedString(builder);
  SerializedString.addBody(builder, bodyOffset);
  return SerializedString.endSerializedString(builder);
}
}
