// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class WebviewJavascriptError {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):WebviewJavascriptError {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsWebviewJavascriptError(bb:flatbuffers.ByteBuffer, obj?:WebviewJavascriptError):WebviewJavascriptError {
  return (obj || new WebviewJavascriptError()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsWebviewJavascriptError(bb:flatbuffers.ByteBuffer, obj?:WebviewJavascriptError):WebviewJavascriptError {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new WebviewJavascriptError()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

message():string|null
message(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
message(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

url():string|null
url(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
url(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

line():string|null
line(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
line(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

column():string|null
column(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
column(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

error():string|null
error(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
error(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static startWebviewJavascriptError(builder:flatbuffers.Builder) {
  builder.startObject(5);
}

static addMessage(builder:flatbuffers.Builder, messageOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, messageOffset, 0);
}

static addUrl(builder:flatbuffers.Builder, urlOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, urlOffset, 0);
}

static addLine(builder:flatbuffers.Builder, lineOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, lineOffset, 0);
}

static addColumn(builder:flatbuffers.Builder, columnOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, columnOffset, 0);
}

static addError(builder:flatbuffers.Builder, errorOffset:flatbuffers.Offset) {
  builder.addFieldOffset(4, errorOffset, 0);
}

static endWebviewJavascriptError(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createWebviewJavascriptError(builder:flatbuffers.Builder, messageOffset:flatbuffers.Offset, urlOffset:flatbuffers.Offset, lineOffset:flatbuffers.Offset, columnOffset:flatbuffers.Offset, errorOffset:flatbuffers.Offset):flatbuffers.Offset {
  WebviewJavascriptError.startWebviewJavascriptError(builder);
  WebviewJavascriptError.addMessage(builder, messageOffset);
  WebviewJavascriptError.addUrl(builder, urlOffset);
  WebviewJavascriptError.addLine(builder, lineOffset);
  WebviewJavascriptError.addColumn(builder, columnOffset);
  WebviewJavascriptError.addError(builder, errorOffset);
  return WebviewJavascriptError.endWebviewJavascriptError(builder);
}
}
