import path from "path";
import fs from "fs";
import { globSync } from "glob";

const root = path.resolve(__dirname, "../templates/docs/");

const outputDir = path.resolve(__dirname, "../src/generated_generators/");

const generateIndexFileRecursively = (dirPath: string): void => {
    const filePaths = fs.readdirSync(dirPath);
    const isDir = (p: string) => {
        const x = fs.statSync(p);
        return x.isDirectory();
    };
    const files = filePaths.filter((f) => {
        return f !== "mod.rs";
    });
    const dirs = filePaths.filter((f) => {
        return isDir(path.join(dirPath, f));
    });
    let s = "";
    for (const f of files) {
        const fi = f.lastIndexOf(".");
        s += `pub mod ${f.slice(0, fi <= 0 ? f.length : fi, 0)};\n`;
    }
    const modPath = path.join(dirPath, "mod.rs");
    fs.writeFileSync(modPath, s, {
        encoding: "utf-8",
    });
    for (const d of dirs) {
        generateIndexFileRecursively(path.join(dirPath, d));
    }
};

const files = globSync("**/*.{md,mdx,cdrm}", {
    absolute: false,
    cwd: root,
});

const outputPaths: Record<string, string> = {};

const getRustPath = (p: string, withPrefix?: boolean): string => {
    const fi = p.lastIndexOf(".");
    return `${withPrefix ? "crate/generated_generators/" : ""}${p.slice(0, fi <= 0 ? p.length : fi)}`.replaceAll(
        "/",
        "::",
    );
};

for (const fp of files) {
    const fileContent = `
use askama::Template;
use conundrum::lang::runtime::traits::conundrum_template::CDRMTemplateRepresentableWithParam;
use strum::IntoEnumIterator;

#[derive(Template, Default)]
#[template(ext = "md", escape="none", path = "docs/${fp}")]
pub struct DocumentationGenerator {
    pub ctx: crate::generator_context::GeneratorContext
}
`;
    const outputPath = path.join(outputDir, fp);
    outputPaths[outputPath] = getRustPath(fp, true);
    const fi = outputPath.lastIndexOf(".");
    const rustPath = `${outputPath.slice(0, fi <= 0 ? outputPath.length : fi)}.rs`;
    const parentDir = path.dirname(rustPath);
    fs.mkdirSync(parentDir, {
        recursive: true,
    });
    fs.writeFileSync(rustPath, fileContent, {
        encoding: "utf-8",
    });
}

let s = `
use askama::Template;

pub fn run_generated_generators() -> crate::errors::DocGenResult<()> {
`;

const getDocOutputPath = (p: string): string => {
    return `${path.join(
        path.resolve(__dirname, "../../../../docs/generated/vector/"),
        p.replaceAll("::", "/").replace("crate/generated_generators", ""),
    )}.cdrm`;
};

for (const k in outputPaths) {
    const rustPath = getRustPath(outputPaths[k], false);
    s += `${rustPath}::DocumentationGenerator::default().render()
        .inspect(|x| {
            let _ = std::fs::create_dir_all("${path.dirname(getDocOutputPath(outputPaths[k]))}")
                .inspect_err(|e| {
                    log::error!("Create Directory Error: {:#?}", e);
                });
            if let Err(err) = std::fs::write("${getDocOutputPath(outputPaths[k])}", x.as_bytes()) {
                log::error!("Docgen Error: {:#?}", err);
            }
        })
        .map_err(|e| {
                                    log::error!("Error: {:#?}", e);
                                    crate::errors::DocGenError::GeneralError
                                })?;\n\n`;
}

s += "Ok(())\n}";

const outputFunctionFile = path.join(outputDir, "docgen_generators.rs");

fs.writeFileSync(outputFunctionFile, s, {
    encoding: "utf-8",
});

generateIndexFileRecursively(outputDir);

let q = `// WARN: THIS FILE IS AUTOMATICALLY GENERATED AS PART OF THE DOCGEN BUILD SCRIPT. DO NOT EDIT DIRECTLY.
use conundrum::ecosystem::error_handling::db_error::DatabaseError;

#[derive(serde::Serialize, serde::Deserialize, Clone, Debug, specta::Type, fake::Dummy, strum_macros::Display, strum_macros::EnumIter)]
pub enum DocumentationKey {
`;

const pulloutPath = (s: string): string => {
    return s.replaceAll("::", "/").replaceAll("crate/generated_generators/", "");
};

const formatName = (n: string): string => {
    return n
        .split("_")
        .map((x) => `${x[0].toUpperCase()}${x.slice(1)}`)
        .join("");
};

for (const k in outputPaths) {
    const fp = outputPaths[k];
    const p = pulloutPath(fp);
    const l = p.slice(p.lastIndexOf("/") + 1, p.length);
    const name = formatName(l);
    q += `
    #[strum(to_string = "${p}.cdrm")]
    #[serde(rename = "${p}.cdrm")]
    ${name},
`;
}

q += `}

impl Into<String> for DocumentationKey {
     fn into(self) -> String {
         match self {
`;

for (const k in outputPaths) {
    const fp = outputPaths[k];
    const p = pulloutPath(fp);
    const l = p.slice(p.lastIndexOf("/") + 1, p.length);
    const name = formatName(l);
    q += `             Self::${name} => include_str!("../../../../../../../../docs/generated/vector/${p}.cdrm").to_string(),
`;
}

q += `         }
     }
}
`;

fs.writeFileSync(
    path.resolve(
        __dirname,
        "../../conundrum_db/src/vector/models/ecosystem_data/documentation/documentation_key.rs",
    ),
    q,
    {
        encoding: "utf-8",
    },
);

console.info("Successfully generated docgen generators.");
