included:
  - apps/fluster/Fluster/
  - packages/swift/FlusterSwift/Sources/
type_body_length:
  warning: 500
  error: 800
identifier_name:
  min_length: 2
disabled_rules:
  - opening_brace
  - switch_case_alignment
  - todo
# opt_in_rules:
#   - force_unwrapping
