packages:
  - packages/webviews/splitview_mdx_editor
  - packages/webviews/bibtex_editor_webview
  - packages/webviews/bib_entry_details_webview
  - packages/webviews/standalone_mdx_editor
  - packages/webviews/standalone_mdx_preview
  - packages/webview_utils
  - packages/shared_config
