packages:
  - apps/website
  - apps/fluster_desktop
  - packages/webviews/splitview_mdx_editor
  - packages/webviews/bibtex_editor_webview
  - packages/webviews/bib_entry_details_webview
  - packages/webviews/standalone_mdx_editor
  - packages/webviews/standalone_mdx_preview
  - packages/webviews/note_detail_webview
  - packages/webviews/dictionary_webview
  - packages/webview_utils
  - packages/typescript/lezer
  - packages/shared_config
  - packages/generated/desktop_bindings
  - packages/swift/desktop_plugins/fluster_swift_data/
