// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class NoteDetailCitationBuffer {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):NoteDetailCitationBuffer {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsNoteDetailCitationBuffer(bb:flatbuffers.ByteBuffer, obj?:NoteDetailCitationBuffer):NoteDetailCitationBuffer {
  return (obj || new NoteDetailCitationBuffer()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsNoteDetailCitationBuffer(bb:flatbuffers.ByteBuffer, obj?:NoteDetailCitationBuffer):NoteDetailCitationBuffer {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new NoteDetailCitationBuffer()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

id():string|null
id(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
id(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

body():string|null
body(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
body(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

idx():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : 0;
}

static startNoteDetailCitationBuffer(builder:flatbuffers.Builder) {
  builder.startObject(3);
}

static addId(builder:flatbuffers.Builder, idOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, idOffset, 0);
}

static addBody(builder:flatbuffers.Builder, bodyOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, bodyOffset, 0);
}

static addIdx(builder:flatbuffers.Builder, idx:number) {
  builder.addFieldInt8(2, idx, 0);
}

static endNoteDetailCitationBuffer(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  builder.requiredField(offset, 4) // id
  builder.requiredField(offset, 6) // body
  return offset;
}

static createNoteDetailCitationBuffer(builder:flatbuffers.Builder, idOffset:flatbuffers.Offset, bodyOffset:flatbuffers.Offset, idx:number):flatbuffers.Offset {
  NoteDetailCitationBuffer.startNoteDetailCitationBuffer(builder);
  NoteDetailCitationBuffer.addId(builder, idOffset);
  NoteDetailCitationBuffer.addBody(builder, bodyOffset);
  NoteDetailCitationBuffer.addIdx(builder, idx);
  return NoteDetailCitationBuffer.endNoteDetailCitationBuffer(builder);
}
}
