use std::sync::Arc;

use crate::ecosystem::{
    db::{parameters::ai::schema_parameters::SchemaParameters, tables::DatabaseTable},
    error_handling::db_error::{DatabaseError, DatabaseResult},
};
use arrow_array::RecordBatch;
use arrow_schema::{Field, FieldRef};
use fake::{Dummy, Faker};
use lancedb::arrow::arrow_schema::Schema;
use serde::{Deserialize, Serialize};
use serde_arrow::{
    schema::{SchemaLike, TracingOptions},
    to_record_batch,
};

/// Deprecated, I'm pretty sure.
pub trait ArrowSchemaRepresentable {
    fn arrow_schema() -> Arc<Schema>;
}

pub trait DBSchema<'a>: Deserialize<'a> + Dummy<Faker> + Serialize {
    /// This method is only relevant for structs that can be generated by Type.
    /// If the arrow_fields method is overriden, this method will never be
    /// used.
    fn schema_options() -> DatabaseResult<TracingOptions> {
        Ok(TracingOptions::default().enums_without_data_as_strings(true))
    }

    fn arrow_fields() -> DatabaseResult<Vec<Arc<Field>>> {
        let opts = Self::schema_options()?;
        Vec::<FieldRef>::from_type::<Self>(opts).map_err(|e| {
                                                    log::error!("Arrow Fields Error: {:?}", e);
                                                    DatabaseError::SerializationError
                                                })
    }
    fn schema() -> DatabaseResult<Schema> {
        let fields = Self::arrow_fields()?;
        let schema = arrow_schema::Schema::new(fields);
        Ok(schema)
    }
}

/// An entity refers to an object *exactly* as it appears in the database, or as
/// close to that as we can get with Rust types. If you're looking for something
/// more composed and usable, look into the equivalent 'Model'.
pub trait DBEntity<'a, PrimaryValueType = String>: DBSchema<'a> {
    type PartialUpdateType;
    fn table() -> DatabaseTable;
    fn get_record_batch(data: Vec<Self>) -> DatabaseResult<RecordBatch>
        where Self: Sized + Clone + Serialize {
        let fields = Self::arrow_fields()?;
        to_record_batch(&fields, &data.clone()).map_err(|e| {
                                                   log::error!("Error: {:?}", e);
                                                   DatabaseError::SerializationError
                                               })
    }
    fn merge_keys() -> &'static [&'static str];
    fn primary_key() -> &'static str;
    fn primary_value(&self) -> PrimaryValueType;
    // fn save_self(&self, db: &ArcMutexDB) -> DatabaseResult<()>;
}
