// automatically generated by the FlatBuffers compiler, do not modify


// @generated

use core::mem;
use core::cmp::Ordering;

extern crate flatbuffers;
use self::flatbuffers::{EndianScalar, Follow};

#[allow(unused_imports, dead_code)]
pub mod mdx_serialization {

  use core::mem;
  use core::cmp::Ordering;

  extern crate flatbuffers;
  use self::flatbuffers::{EndianScalar, Follow};

pub enum CitationResultOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct CitationResult<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for CitationResult<'a> {
  type Inner = CitationResult<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> CitationResult<'a> {
  pub const VT_CITATION_KEY: flatbuffers::VOffsetT = 4;
  pub const VT_BODY: flatbuffers::VOffsetT = 6;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    CitationResult { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args CitationResultArgs<'args>
  ) -> flatbuffers::WIPOffset<CitationResult<'bldr>> {
    let mut builder = CitationResultBuilder::new(_fbb);
    if let Some(x) = args.body { builder.add_body(x); }
    if let Some(x) = args.citation_key { builder.add_citation_key(x); }
    builder.finish()
  }


  #[inline]
  pub fn citation_key(&self) -> &'a str {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(CitationResult::VT_CITATION_KEY, None).unwrap()}
  }
  #[inline]
  pub fn body(&self) -> &'a str {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(CitationResult::VT_BODY, None).unwrap()}
  }
}

impl flatbuffers::Verifiable for CitationResult<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("citation_key", Self::VT_CITATION_KEY, true)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("body", Self::VT_BODY, true)?
     .finish();
    Ok(())
  }
}
pub struct CitationResultArgs<'a> {
    pub citation_key: Option<flatbuffers::WIPOffset<&'a str>>,
    pub body: Option<flatbuffers::WIPOffset<&'a str>>,
}
impl<'a> Default for CitationResultArgs<'a> {
  #[inline]
  fn default() -> Self {
    CitationResultArgs {
      citation_key: None, // required field
      body: None, // required field
    }
  }
}

pub struct CitationResultBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> CitationResultBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_citation_key(&mut self, citation_key: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(CitationResult::VT_CITATION_KEY, citation_key);
  }
  #[inline]
  pub fn add_body(&mut self, body: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(CitationResult::VT_BODY, body);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>) -> CitationResultBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    CitationResultBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<CitationResult<'a>> {
    let o = self.fbb_.end_table(self.start_);
    self.fbb_.required(o, CitationResult::VT_CITATION_KEY,"citation_key");
    self.fbb_.required(o, CitationResult::VT_BODY,"body");
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for CitationResult<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("CitationResult");
      ds.field("citation_key", &self.citation_key());
      ds.field("body", &self.body());
      ds.finish()
  }
}
pub enum TagResultOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct TagResult<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for TagResult<'a> {
  type Inner = TagResult<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> TagResult<'a> {
  pub const VT_BODY: flatbuffers::VOffsetT = 4;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    TagResult { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args TagResultArgs<'args>
  ) -> flatbuffers::WIPOffset<TagResult<'bldr>> {
    let mut builder = TagResultBuilder::new(_fbb);
    if let Some(x) = args.body { builder.add_body(x); }
    builder.finish()
  }


  #[inline]
  pub fn body(&self) -> &'a str {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(TagResult::VT_BODY, None).unwrap()}
  }
}

impl flatbuffers::Verifiable for TagResult<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("body", Self::VT_BODY, true)?
     .finish();
    Ok(())
  }
}
pub struct TagResultArgs<'a> {
    pub body: Option<flatbuffers::WIPOffset<&'a str>>,
}
impl<'a> Default for TagResultArgs<'a> {
  #[inline]
  fn default() -> Self {
    TagResultArgs {
      body: None, // required field
    }
  }
}

pub struct TagResultBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> TagResultBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_body(&mut self, body: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(TagResult::VT_BODY, body);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>) -> TagResultBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    TagResultBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<TagResult<'a>> {
    let o = self.fbb_.end_table(self.start_);
    self.fbb_.required(o, TagResult::VT_BODY,"body");
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for TagResult<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("TagResult");
      ds.field("body", &self.body());
      ds.finish()
  }
}
pub enum FrontMatterResultOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct FrontMatterResult<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for FrontMatterResult<'a> {
  type Inner = FrontMatterResult<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> FrontMatterResult<'a> {
  pub const VT_IGNORE_PARSERS: flatbuffers::VOffsetT = 4;
  pub const VT_TITLE: flatbuffers::VOffsetT = 6;
  pub const VT_USER_DEFINED_ID: flatbuffers::VOffsetT = 8;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    FrontMatterResult { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args FrontMatterResultArgs<'args>
  ) -> flatbuffers::WIPOffset<FrontMatterResult<'bldr>> {
    let mut builder = FrontMatterResultBuilder::new(_fbb);
    if let Some(x) = args.user_defined_id { builder.add_user_defined_id(x); }
    if let Some(x) = args.title { builder.add_title(x); }
    if let Some(x) = args.ignore_parsers { builder.add_ignore_parsers(x); }
    builder.finish()
  }


  #[inline]
  pub fn ignore_parsers(&self) -> flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<&'a str>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<&'a str>>>>(FrontMatterResult::VT_IGNORE_PARSERS, None).unwrap()}
  }
  #[inline]
  pub fn title(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(FrontMatterResult::VT_TITLE, None)}
  }
  #[inline]
  pub fn user_defined_id(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(FrontMatterResult::VT_USER_DEFINED_ID, None)}
  }
}

impl flatbuffers::Verifiable for FrontMatterResult<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, flatbuffers::ForwardsUOffset<&'_ str>>>>("ignore_parsers", Self::VT_IGNORE_PARSERS, true)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("title", Self::VT_TITLE, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("user_defined_id", Self::VT_USER_DEFINED_ID, false)?
     .finish();
    Ok(())
  }
}
pub struct FrontMatterResultArgs<'a> {
    pub ignore_parsers: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<&'a str>>>>,
    pub title: Option<flatbuffers::WIPOffset<&'a str>>,
    pub user_defined_id: Option<flatbuffers::WIPOffset<&'a str>>,
}
impl<'a> Default for FrontMatterResultArgs<'a> {
  #[inline]
  fn default() -> Self {
    FrontMatterResultArgs {
      ignore_parsers: None, // required field
      title: None,
      user_defined_id: None,
    }
  }
}

pub struct FrontMatterResultBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> FrontMatterResultBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_ignore_parsers(&mut self, ignore_parsers: flatbuffers::WIPOffset<flatbuffers::Vector<'b , flatbuffers::ForwardsUOffset<&'b  str>>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(FrontMatterResult::VT_IGNORE_PARSERS, ignore_parsers);
  }
  #[inline]
  pub fn add_title(&mut self, title: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(FrontMatterResult::VT_TITLE, title);
  }
  #[inline]
  pub fn add_user_defined_id(&mut self, user_defined_id: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(FrontMatterResult::VT_USER_DEFINED_ID, user_defined_id);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>) -> FrontMatterResultBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    FrontMatterResultBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<FrontMatterResult<'a>> {
    let o = self.fbb_.end_table(self.start_);
    self.fbb_.required(o, FrontMatterResult::VT_IGNORE_PARSERS,"ignore_parsers");
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for FrontMatterResult<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("FrontMatterResult");
      ds.field("ignore_parsers", &self.ignore_parsers());
      ds.field("title", &self.title());
      ds.field("user_defined_id", &self.user_defined_id());
      ds.finish()
  }
}
pub enum MdxParsingResultOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct MdxParsingResult<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for MdxParsingResult<'a> {
  type Inner = MdxParsingResult<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> MdxParsingResult<'a> {
  pub const VT_CONTENT: flatbuffers::VOffsetT = 4;
  pub const VT_TAGS: flatbuffers::VOffsetT = 6;
  pub const VT_FRONT_MATTER: flatbuffers::VOffsetT = 8;
  pub const VT_CITATIONS: flatbuffers::VOffsetT = 10;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    MdxParsingResult { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args MdxParsingResultArgs<'args>
  ) -> flatbuffers::WIPOffset<MdxParsingResult<'bldr>> {
    let mut builder = MdxParsingResultBuilder::new(_fbb);
    if let Some(x) = args.citations { builder.add_citations(x); }
    if let Some(x) = args.front_matter { builder.add_front_matter(x); }
    if let Some(x) = args.tags { builder.add_tags(x); }
    if let Some(x) = args.content { builder.add_content(x); }
    builder.finish()
  }


  #[inline]
  pub fn content(&self) -> &'a str {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(MdxParsingResult::VT_CONTENT, None).unwrap()}
  }
  #[inline]
  pub fn tags(&self) -> flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<TagResult<'a>>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<TagResult>>>>(MdxParsingResult::VT_TAGS, None).unwrap()}
  }
  #[inline]
  pub fn front_matter(&self) -> Option<FrontMatterResult<'a>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<FrontMatterResult>>(MdxParsingResult::VT_FRONT_MATTER, None)}
  }
  #[inline]
  pub fn citations(&self) -> Option<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<CitationResult<'a>>>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<CitationResult>>>>(MdxParsingResult::VT_CITATIONS, None)}
  }
}

impl flatbuffers::Verifiable for MdxParsingResult<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("content", Self::VT_CONTENT, true)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, flatbuffers::ForwardsUOffset<TagResult>>>>("tags", Self::VT_TAGS, true)?
     .visit_field::<flatbuffers::ForwardsUOffset<FrontMatterResult>>("front_matter", Self::VT_FRONT_MATTER, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, flatbuffers::ForwardsUOffset<CitationResult>>>>("citations", Self::VT_CITATIONS, false)?
     .finish();
    Ok(())
  }
}
pub struct MdxParsingResultArgs<'a> {
    pub content: Option<flatbuffers::WIPOffset<&'a str>>,
    pub tags: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<TagResult<'a>>>>>,
    pub front_matter: Option<flatbuffers::WIPOffset<FrontMatterResult<'a>>>,
    pub citations: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<CitationResult<'a>>>>>,
}
impl<'a> Default for MdxParsingResultArgs<'a> {
  #[inline]
  fn default() -> Self {
    MdxParsingResultArgs {
      content: None, // required field
      tags: None, // required field
      front_matter: None,
      citations: None,
    }
  }
}

pub struct MdxParsingResultBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> MdxParsingResultBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_content(&mut self, content: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(MdxParsingResult::VT_CONTENT, content);
  }
  #[inline]
  pub fn add_tags(&mut self, tags: flatbuffers::WIPOffset<flatbuffers::Vector<'b , flatbuffers::ForwardsUOffset<TagResult<'b >>>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(MdxParsingResult::VT_TAGS, tags);
  }
  #[inline]
  pub fn add_front_matter(&mut self, front_matter: flatbuffers::WIPOffset<FrontMatterResult<'b >>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<FrontMatterResult>>(MdxParsingResult::VT_FRONT_MATTER, front_matter);
  }
  #[inline]
  pub fn add_citations(&mut self, citations: flatbuffers::WIPOffset<flatbuffers::Vector<'b , flatbuffers::ForwardsUOffset<CitationResult<'b >>>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(MdxParsingResult::VT_CITATIONS, citations);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>) -> MdxParsingResultBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    MdxParsingResultBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<MdxParsingResult<'a>> {
    let o = self.fbb_.end_table(self.start_);
    self.fbb_.required(o, MdxParsingResult::VT_CONTENT,"content");
    self.fbb_.required(o, MdxParsingResult::VT_TAGS,"tags");
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for MdxParsingResult<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("MdxParsingResult");
      ds.field("content", &self.content());
      ds.field("tags", &self.tags());
      ds.field("front_matter", &self.front_matter());
      ds.field("citations", &self.citations());
      ds.finish()
  }
}
#[inline]
/// Verifies that a buffer of bytes contains a `MdxParsingResult`
/// and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_mdx_parsing_result_unchecked`.
pub fn root_as_mdx_parsing_result(buf: &[u8]) -> Result<MdxParsingResult, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::root::<MdxParsingResult>(buf)
}
#[inline]
/// Verifies that a buffer of bytes contains a size prefixed
/// `MdxParsingResult` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `size_prefixed_root_as_mdx_parsing_result_unchecked`.
pub fn size_prefixed_root_as_mdx_parsing_result(buf: &[u8]) -> Result<MdxParsingResult, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::size_prefixed_root::<MdxParsingResult>(buf)
}
#[inline]
/// Verifies, with the given options, that a buffer of bytes
/// contains a `MdxParsingResult` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_mdx_parsing_result_unchecked`.
pub fn root_as_mdx_parsing_result_with_opts<'b, 'o>(
  opts: &'o flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<MdxParsingResult<'b>, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::root_with_opts::<MdxParsingResult<'b>>(opts, buf)
}
#[inline]
/// Verifies, with the given verifier options, that a buffer of
/// bytes contains a size prefixed `MdxParsingResult` and returns
/// it. Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_mdx_parsing_result_unchecked`.
pub fn size_prefixed_root_as_mdx_parsing_result_with_opts<'b, 'o>(
  opts: &'o flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<MdxParsingResult<'b>, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::size_prefixed_root_with_opts::<MdxParsingResult<'b>>(opts, buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a MdxParsingResult and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid `MdxParsingResult`.
pub unsafe fn root_as_mdx_parsing_result_unchecked(buf: &[u8]) -> MdxParsingResult {
  unsafe { flatbuffers::root_unchecked::<MdxParsingResult>(buf) }
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a size prefixed MdxParsingResult and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid size prefixed `MdxParsingResult`.
pub unsafe fn size_prefixed_root_as_mdx_parsing_result_unchecked(buf: &[u8]) -> MdxParsingResult {
  unsafe { flatbuffers::size_prefixed_root_unchecked::<MdxParsingResult>(buf) }
}
#[inline]
pub fn finish_mdx_parsing_result_buffer<'a, 'b, A: flatbuffers::Allocator + 'a>(
    fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
    root: flatbuffers::WIPOffset<MdxParsingResult<'a>>) {
  fbb.finish(root, None);
}

#[inline]
pub fn finish_size_prefixed_mdx_parsing_result_buffer<'a, 'b, A: flatbuffers::Allocator + 'a>(fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>, root: flatbuffers::WIPOffset<MdxParsingResult<'a>>) {
  fbb.finish_size_prefixed(root, None);
}
#[allow(unused_imports, dead_code)]
pub mod request {

  use core::mem;
  use core::cmp::Ordering;

  extern crate flatbuffers;
  use self::flatbuffers::{EndianScalar, Follow};

pub enum ParseMdxOptionsOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct ParseMdxOptions<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for ParseMdxOptions<'a> {
  type Inner = ParseMdxOptions<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> ParseMdxOptions<'a> {
  pub const VT_CONTENT: flatbuffers::VOffsetT = 4;
  pub const VT_CITATIONS: flatbuffers::VOffsetT = 6;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    ParseMdxOptions { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args ParseMdxOptionsArgs<'args>
  ) -> flatbuffers::WIPOffset<ParseMdxOptions<'bldr>> {
    let mut builder = ParseMdxOptionsBuilder::new(_fbb);
    if let Some(x) = args.citations { builder.add_citations(x); }
    if let Some(x) = args.content { builder.add_content(x); }
    builder.finish()
  }


  #[inline]
  pub fn content(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(ParseMdxOptions::VT_CONTENT, None)}
  }
  #[inline]
  pub fn citations(&self) -> Option<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<super::CitationResult<'a>>>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<super::CitationResult>>>>(ParseMdxOptions::VT_CITATIONS, None)}
  }
}

impl flatbuffers::Verifiable for ParseMdxOptions<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("content", Self::VT_CONTENT, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, flatbuffers::ForwardsUOffset<super::CitationResult>>>>("citations", Self::VT_CITATIONS, false)?
     .finish();
    Ok(())
  }
}
pub struct ParseMdxOptionsArgs<'a> {
    pub content: Option<flatbuffers::WIPOffset<&'a str>>,
    pub citations: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<super::CitationResult<'a>>>>>,
}
impl<'a> Default for ParseMdxOptionsArgs<'a> {
  #[inline]
  fn default() -> Self {
    ParseMdxOptionsArgs {
      content: None,
      citations: None,
    }
  }
}

pub struct ParseMdxOptionsBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> ParseMdxOptionsBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_content(&mut self, content: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(ParseMdxOptions::VT_CONTENT, content);
  }
  #[inline]
  pub fn add_citations(&mut self, citations: flatbuffers::WIPOffset<flatbuffers::Vector<'b , flatbuffers::ForwardsUOffset<super::CitationResult<'b >>>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(ParseMdxOptions::VT_CITATIONS, citations);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>) -> ParseMdxOptionsBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    ParseMdxOptionsBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<ParseMdxOptions<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for ParseMdxOptions<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("ParseMdxOptions");
      ds.field("content", &self.content());
      ds.field("citations", &self.citations());
      ds.finish()
  }
}
}  // pub mod Request

#[allow(unused_imports, dead_code)]
pub mod note_details {

  use core::mem;
  use core::cmp::Ordering;

  extern crate flatbuffers;
  use self::flatbuffers::{EndianScalar, Follow};

pub enum NoteDetailDataOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct NoteDetailData<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for NoteDetailData<'a> {
  type Inner = NoteDetailData<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> NoteDetailData<'a> {
  pub const VT_NOTE_ID: flatbuffers::VOffsetT = 4;
  pub const VT_TITLE: flatbuffers::VOffsetT = 6;
  pub const VT_TAGS: flatbuffers::VOffsetT = 8;
  pub const VT_CITATIONS: flatbuffers::VOffsetT = 10;
  pub const VT_LAST_MODIFIED_STRING: flatbuffers::VOffsetT = 12;
  pub const VT_LAST_READ_STRING: flatbuffers::VOffsetT = 14;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    NoteDetailData { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args NoteDetailDataArgs<'args>
  ) -> flatbuffers::WIPOffset<NoteDetailData<'bldr>> {
    let mut builder = NoteDetailDataBuilder::new(_fbb);
    if let Some(x) = args.last_read_string { builder.add_last_read_string(x); }
    if let Some(x) = args.last_modified_string { builder.add_last_modified_string(x); }
    if let Some(x) = args.citations { builder.add_citations(x); }
    if let Some(x) = args.tags { builder.add_tags(x); }
    if let Some(x) = args.title { builder.add_title(x); }
    if let Some(x) = args.note_id { builder.add_note_id(x); }
    builder.finish()
  }


  #[inline]
  pub fn note_id(&self) -> &'a str {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(NoteDetailData::VT_NOTE_ID, None).unwrap()}
  }
  #[inline]
  pub fn title(&self) -> &'a str {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(NoteDetailData::VT_TITLE, None).unwrap()}
  }
  #[inline]
  pub fn tags(&self) -> flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<super::TagResult<'a>>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<super::TagResult>>>>(NoteDetailData::VT_TAGS, None).unwrap()}
  }
  #[inline]
  pub fn citations(&self) -> flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<super::CitationResult<'a>>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<super::CitationResult>>>>(NoteDetailData::VT_CITATIONS, None).unwrap()}
  }
  #[inline]
  pub fn last_modified_string(&self) -> &'a str {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(NoteDetailData::VT_LAST_MODIFIED_STRING, None).unwrap()}
  }
  #[inline]
  pub fn last_read_string(&self) -> &'a str {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(NoteDetailData::VT_LAST_READ_STRING, None).unwrap()}
  }
}

impl flatbuffers::Verifiable for NoteDetailData<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("note_id", Self::VT_NOTE_ID, true)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("title", Self::VT_TITLE, true)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, flatbuffers::ForwardsUOffset<super::TagResult>>>>("tags", Self::VT_TAGS, true)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, flatbuffers::ForwardsUOffset<super::CitationResult>>>>("citations", Self::VT_CITATIONS, true)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("last_modified_string", Self::VT_LAST_MODIFIED_STRING, true)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("last_read_string", Self::VT_LAST_READ_STRING, true)?
     .finish();
    Ok(())
  }
}
pub struct NoteDetailDataArgs<'a> {
    pub note_id: Option<flatbuffers::WIPOffset<&'a str>>,
    pub title: Option<flatbuffers::WIPOffset<&'a str>>,
    pub tags: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<super::TagResult<'a>>>>>,
    pub citations: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<super::CitationResult<'a>>>>>,
    pub last_modified_string: Option<flatbuffers::WIPOffset<&'a str>>,
    pub last_read_string: Option<flatbuffers::WIPOffset<&'a str>>,
}
impl<'a> Default for NoteDetailDataArgs<'a> {
  #[inline]
  fn default() -> Self {
    NoteDetailDataArgs {
      note_id: None, // required field
      title: None, // required field
      tags: None, // required field
      citations: None, // required field
      last_modified_string: None, // required field
      last_read_string: None, // required field
    }
  }
}

pub struct NoteDetailDataBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> NoteDetailDataBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_note_id(&mut self, note_id: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(NoteDetailData::VT_NOTE_ID, note_id);
  }
  #[inline]
  pub fn add_title(&mut self, title: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(NoteDetailData::VT_TITLE, title);
  }
  #[inline]
  pub fn add_tags(&mut self, tags: flatbuffers::WIPOffset<flatbuffers::Vector<'b , flatbuffers::ForwardsUOffset<super::TagResult<'b >>>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(NoteDetailData::VT_TAGS, tags);
  }
  #[inline]
  pub fn add_citations(&mut self, citations: flatbuffers::WIPOffset<flatbuffers::Vector<'b , flatbuffers::ForwardsUOffset<super::CitationResult<'b >>>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(NoteDetailData::VT_CITATIONS, citations);
  }
  #[inline]
  pub fn add_last_modified_string(&mut self, last_modified_string: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(NoteDetailData::VT_LAST_MODIFIED_STRING, last_modified_string);
  }
  #[inline]
  pub fn add_last_read_string(&mut self, last_read_string: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(NoteDetailData::VT_LAST_READ_STRING, last_read_string);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>) -> NoteDetailDataBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    NoteDetailDataBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<NoteDetailData<'a>> {
    let o = self.fbb_.end_table(self.start_);
    self.fbb_.required(o, NoteDetailData::VT_NOTE_ID,"note_id");
    self.fbb_.required(o, NoteDetailData::VT_TITLE,"title");
    self.fbb_.required(o, NoteDetailData::VT_TAGS,"tags");
    self.fbb_.required(o, NoteDetailData::VT_CITATIONS,"citations");
    self.fbb_.required(o, NoteDetailData::VT_LAST_MODIFIED_STRING,"last_modified_string");
    self.fbb_.required(o, NoteDetailData::VT_LAST_READ_STRING,"last_read_string");
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for NoteDetailData<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("NoteDetailData");
      ds.field("note_id", &self.note_id());
      ds.field("title", &self.title());
      ds.field("tags", &self.tags());
      ds.field("citations", &self.citations());
      ds.field("last_modified_string", &self.last_modified_string());
      ds.field("last_read_string", &self.last_read_string());
      ds.finish()
  }
}
}  // pub mod NoteDetails
}  // pub mod MdxSerialization

