// WARNING: This file is automatically generated as part of the docgen script.
// Any work done here will be lost.
use winnow::Parser;
use winnow::error::ErrMode;
use winnow::token::literal;

use crate::lang::runtime::state::conundrum_error::ConundrumError;
use crate::lang::runtime::state::conundrum_error_variant::{ConundrumErrorVariant, ConundrumModalResult};
use crate::lang::runtime::traits::conundrum_input::ConundrumInput;
use crate::parsers::conundrum::color::css_color::CssColor;

/// For the love of God, do not call this function in the main markdown text.
/// It's super inefficient, but it makes sense where a color is expected.
pub fn named_color(input: &mut ConundrumInput) -> ConundrumModalResult<CssColor> {
             if let Ok(res) = literal::<_, ConundrumInput, ErrMode<ConundrumErrorVariant>>("blanchedalmond").map(|_| {
                CssColor::from_rgba(255, 235, 205, 1)
            }).parse_next(input) {
                Ok(res)
            } else  if let Ok(res) = literal::<_, ConundrumInput, ErrMode<ConundrumErrorVariant>>("azure").map(|_| {
                CssColor::from_rgba(240, 255, 255, 1)
            }).parse_next(input) {
                Ok(res)
            } else  if let Ok(res) = literal::<_, ConundrumInput, ErrMode<ConundrumErrorVariant>>("olive").map(|_| {
                CssColor::from_rgba(128, 128, 0, 1)
            }).parse_next(input) {
                Ok(res)
            } else  if let Ok(res) = literal::<_, ConundrumInput, ErrMode<ConundrumErrorVariant>>("slateblue").map(|_| {
                CssColor::from_rgba(106, 90, 205, 1)
            }).parse_next(input) {
                Ok(res)
            } else  if let Ok(res) = literal::<_, ConundrumInput, ErrMode<ConundrumErrorVariant>>("navy").map(|_| {
                CssColor::from_rgba(0, 0, 128, 1)
            }).parse_next(input) {
                Ok(res)
            } else  if let Ok(res) = literal::<_, ConundrumInput, ErrMode<ConundrumErrorVariant>>("brown").map(|_| {
                CssColor::from_rgba(165, 42, 42, 1)
            }).parse_next(input) {
                Ok(res)
            } else  if let Ok(res) = literal::<_, ConundrumInput, ErrMode<ConundrumErrorVariant>>("greenyellow").map(|_| {
                CssColor::from_rgba(173, 255, 47, 1)
            }).parse_next(input) {
                Ok(res)
            } else  if let Ok(res) = literal::<_, ConundrumInput, ErrMode<ConundrumErrorVariant>>("darkmagenta").map(|_| {
                CssColor::from_rgba(139, 0, 139, 1)
            }).parse_next(input) {
                Ok(res)
            } else  if let Ok(res) = literal::<_, ConundrumInput, ErrMode<ConundrumErrorVariant>>("limegreen").map(|_| {
                CssColor::from_rgba(50, 205, 50, 1)
            }).parse_next(input) {
                Ok(res)
            } else  if let Ok(res) = literal::<_, ConundrumInput, ErrMode<ConundrumErrorVariant>>("darkolivegreen").map(|_| {
                CssColor::from_rgba(85, 107, 47, 1)
            }).parse_next(input) {
                Ok(res)
            } else  if let Ok(res) = literal::<_, ConundrumInput, ErrMode<ConundrumErrorVariant>>("navajowhite").map(|_| {
                CssColor::from_rgba(255, 222, 173, 1)
            }).parse_next(input) {
                Ok(res)
            } else  if let Ok(res) = literal::<_, ConundrumInput, ErrMode<ConundrumErrorVariant>>("mediumaquamarine").map(|_| {
                CssColor::from_rgba(102, 205, 170, 1)
            }).parse_next(input) {
                Ok(res)
            } else  if let Ok(res) = literal::<_, ConundrumInput, ErrMode<ConundrumErrorVariant>>("lime").map(|_| {
                CssColor::from_rgba(0, 255, 0, 1)
            }).parse_next(input) {
                Ok(res)
            } else  if let Ok(res) = literal::<_, ConundrumInput, ErrMode<ConundrumErrorVariant>>("chocolate").map(|_| {
                CssColor::from_rgba(210, 105, 30, 1)
            }).parse_next(input) {
                Ok(res)
            } else  if let Ok(res) = literal::<_, ConundrumInput, ErrMode<ConundrumErrorVariant>>("gold").map(|_| {
                CssColor::from_rgba(255, 215, 0, 1)
            }).parse_next(input) {
                Ok(res)
            } else  if let Ok(res) = literal::<_, ConundrumInput, ErrMode<ConundrumErrorVariant>>("tomato").map(|_| {
                CssColor::from_rgba(255, 99, 71, 1)
            }).parse_next(input) {
                Ok(res)
            } else  if let Ok(res) = literal::<_, ConundrumInput, ErrMode<ConundrumErrorVariant>>("peachpuff").map(|_| {
                CssColor::from_rgba(255, 218, 185, 1)
            }).parse_next(input) {
                Ok(res)
            } else  if let Ok(res) = literal::<_, ConundrumInput, ErrMode<ConundrumErrorVariant>>("lightsalmon").map(|_| {
                CssColor::from_rgba(255, 160, 122, 1)
            }).parse_next(input) {
                Ok(res)
            } else  if let Ok(res) = literal::<_, ConundrumInput, ErrMode<ConundrumErrorVariant>>("lightslategrey").map(|_| {
                CssColor::from_rgba(119, 136, 153, 1)
            }).parse_next(input) {
                Ok(res)
            } else  if let Ok(res) = literal::<_, ConundrumInput, ErrMode<ConundrumErrorVariant>>("aquamarine").map(|_| {
                CssColor::from_rgba(127, 255, 212, 1)
            }).parse_next(input) {
                Ok(res)
            } else  if let Ok(res) = literal::<_, ConundrumInput, ErrMode<ConundrumErrorVariant>>("teal").map(|_| {
                CssColor::from_rgba(0, 128, 128, 1)
            }).parse_next(input) {
                Ok(res)
            } else  if let Ok(res) = literal::<_, ConundrumInput, ErrMode<ConundrumErrorVariant>>("lightpink").map(|_| {
                CssColor::from_rgba(255, 182, 193, 1)
            }).parse_next(input) {
                Ok(res)
            } else  if let Ok(res) = literal::<_, ConundrumInput, ErrMode<ConundrumErrorVariant>>("mediumvioletred").map(|_| {
                CssColor::from_rgba(199, 21, 133, 1)
            }).parse_next(input) {
                Ok(res)
            } else  if let Ok(res) = literal::<_, ConundrumInput, ErrMode<ConundrumErrorVariant>>("tan").map(|_| {
                CssColor::from_rgba(210, 180, 140, 1)
            }).parse_next(input) {
                Ok(res)
            } else  if let Ok(res) = literal::<_, ConundrumInput, ErrMode<ConundrumErrorVariant>>("lemonchiffon").map(|_| {
                CssColor::from_rgba(255, 250, 205, 1)
            }).parse_next(input) {
                Ok(res)
            } else  if let Ok(res) = literal::<_, ConundrumInput, ErrMode<ConundrumErrorVariant>>("green").map(|_| {
                CssColor::from_rgba(0, 128, 0, 1)
            }).parse_next(input) {
                Ok(res)
            } else  if let Ok(res) = literal::<_, ConundrumInput, ErrMode<ConundrumErrorVariant>>("olivedrab").map(|_| {
                CssColor::from_rgba(107, 142, 35, 1)
            }).parse_next(input) {
                Ok(res)
            } else  if let Ok(res) = literal::<_, ConundrumInput, ErrMode<ConundrumErrorVariant>>("deepskyblue").map(|_| {
                CssColor::from_rgba(0, 191, 255, 1)
            }).parse_next(input) {
                Ok(res)
            } else  if let Ok(res) = literal::<_, ConundrumInput, ErrMode<ConundrumErrorVariant>>("darkgray").map(|_| {
                CssColor::from_rgba(169, 169, 169, 1)
            }).parse_next(input) {
                Ok(res)
            } else  if let Ok(res) = literal::<_, ConundrumInput, ErrMode<ConundrumErrorVariant>>("lightgreen").map(|_| {
                CssColor::from_rgba(144, 238, 144, 1)
            }).parse_next(input) {
                Ok(res)
            } else  if let Ok(res) = literal::<_, ConundrumInput, ErrMode<ConundrumErrorVariant>>("mintcream").map(|_| {
                CssColor::from_rgba(245, 255, 250, 1)
            }).parse_next(input) {
                Ok(res)
            } else  if let Ok(res) = literal::<_, ConundrumInput, ErrMode<ConundrumErrorVariant>>("salmon").map(|_| {
                CssColor::from_rgba(250, 128, 114, 1)
            }).parse_next(input) {
                Ok(res)
            } else  if let Ok(res) = literal::<_, ConundrumInput, ErrMode<ConundrumErrorVariant>>("dodgerblue").map(|_| {
                CssColor::from_rgba(30, 144, 255, 1)
            }).parse_next(input) {
                Ok(res)
            } else  if let Ok(res) = literal::<_, ConundrumInput, ErrMode<ConundrumErrorVariant>>("mediumturquoise").map(|_| {
                CssColor::from_rgba(72, 209, 204, 1)
            }).parse_next(input) {
                Ok(res)
            } else  if let Ok(res) = literal::<_, ConundrumInput, ErrMode<ConundrumErrorVariant>>("steelblue").map(|_| {
                CssColor::from_rgba(70, 130, 180, 1)
            }).parse_next(input) {
                Ok(res)
            } else  if let Ok(res) = literal::<_, ConundrumInput, ErrMode<ConundrumErrorVariant>>("lightgrey").map(|_| {
                CssColor::from_rgba(211, 211, 211, 1)
            }).parse_next(input) {
                Ok(res)
            } else  if let Ok(res) = literal::<_, ConundrumInput, ErrMode<ConundrumErrorVariant>>("mediumorchid").map(|_| {
                CssColor::from_rgba(186, 85, 211, 1)
            }).parse_next(input) {
                Ok(res)
            } else  if let Ok(res) = literal::<_, ConundrumInput, ErrMode<ConundrumErrorVariant>>("skyblue").map(|_| {
                CssColor::from_rgba(135, 206, 235, 1)
            }).parse_next(input) {
                Ok(res)
            } else  if let Ok(res) = literal::<_, ConundrumInput, ErrMode<ConundrumErrorVariant>>("darkviolet").map(|_| {
                CssColor::from_rgba(148, 0, 211, 1)
            }).parse_next(input) {
                Ok(res)
            } else  if let Ok(res) = literal::<_, ConundrumInput, ErrMode<ConundrumErrorVariant>>("mediumseagreen").map(|_| {
                CssColor::from_rgba(60, 179, 113, 1)
            }).parse_next(input) {
                Ok(res)
            } else  if let Ok(res) = literal::<_, ConundrumInput, ErrMode<ConundrumErrorVariant>>("paleturquoise").map(|_| {
                CssColor::from_rgba(175, 238, 238, 1)
            }).parse_next(input) {
                Ok(res)
            } else  if let Ok(res) = literal::<_, ConundrumInput, ErrMode<ConundrumErrorVariant>>("plum").map(|_| {
                CssColor::from_rgba(221, 160, 221, 1)
            }).parse_next(input) {
                Ok(res)
            } else  if let Ok(res) = literal::<_, ConundrumInput, ErrMode<ConundrumErrorVariant>>("blueviolet").map(|_| {
                CssColor::from_rgba(138, 43, 226, 1)
            }).parse_next(input) {
                Ok(res)
            } else  if let Ok(res) = literal::<_, ConundrumInput, ErrMode<ConundrumErrorVariant>>("lightslategray").map(|_| {
                CssColor::from_rgba(119, 136, 153, 1)
            }).parse_next(input) {
                Ok(res)
            } else  if let Ok(res) = literal::<_, ConundrumInput, ErrMode<ConundrumErrorVariant>>("slategray").map(|_| {
                CssColor::from_rgba(112, 128, 144, 1)
            }).parse_next(input) {
                Ok(res)
            } else  if let Ok(res) = literal::<_, ConundrumInput, ErrMode<ConundrumErrorVariant>>("ivory").map(|_| {
                CssColor::from_rgba(255, 255, 240, 1)
            }).parse_next(input) {
                Ok(res)
            } else  if let Ok(res) = literal::<_, ConundrumInput, ErrMode<ConundrumErrorVariant>>("snow").map(|_| {
                CssColor::from_rgba(255, 250, 250, 1)
            }).parse_next(input) {
                Ok(res)
            } else  if let Ok(res) = literal::<_, ConundrumInput, ErrMode<ConundrumErrorVariant>>("cornsilk").map(|_| {
                CssColor::from_rgba(255, 248, 220, 1)
            }).parse_next(input) {
                Ok(res)
            } else  if let Ok(res) = literal::<_, ConundrumInput, ErrMode<ConundrumErrorVariant>>("darkgreen").map(|_| {
                CssColor::from_rgba(0, 100, 0, 1)
            }).parse_next(input) {
                Ok(res)
            } else  if let Ok(res) = literal::<_, ConundrumInput, ErrMode<ConundrumErrorVariant>>("orchid").map(|_| {
                CssColor::from_rgba(218, 112, 214, 1)
            }).parse_next(input) {
                Ok(res)
            } else  if let Ok(res) = literal::<_, ConundrumInput, ErrMode<ConundrumErrorVariant>>("bisque").map(|_| {
                CssColor::from_rgba(255, 228, 196, 1)
            }).parse_next(input) {
                Ok(res)
            } else  if let Ok(res) = literal::<_, ConundrumInput, ErrMode<ConundrumErrorVariant>>("purple").map(|_| {
                CssColor::from_rgba(128, 0, 128, 1)
            }).parse_next(input) {
                Ok(res)
            } else  if let Ok(res) = literal::<_, ConundrumInput, ErrMode<ConundrumErrorVariant>>("orange").map(|_| {
                CssColor::from_rgba(255, 165, 0, 1)
            }).parse_next(input) {
                Ok(res)
            } else  if let Ok(res) = literal::<_, ConundrumInput, ErrMode<ConundrumErrorVariant>>("linen").map(|_| {
                CssColor::from_rgba(250, 240, 230, 1)
            }).parse_next(input) {
                Ok(res)
            } else  if let Ok(res) = literal::<_, ConundrumInput, ErrMode<ConundrumErrorVariant>>("darkslateblue").map(|_| {
                CssColor::from_rgba(72, 61, 139, 1)
            }).parse_next(input) {
                Ok(res)
            } else  if let Ok(res) = literal::<_, ConundrumInput, ErrMode<ConundrumErrorVariant>>("grey").map(|_| {
                CssColor::from_rgba(128, 128, 128, 1)
            }).parse_next(input) {
                Ok(res)
            } else  if let Ok(res) = literal::<_, ConundrumInput, ErrMode<ConundrumErrorVariant>>("beige").map(|_| {
                CssColor::from_rgba(245, 245, 220, 1)
            }).parse_next(input) {
                Ok(res)
            } else  if let Ok(res) = literal::<_, ConundrumInput, ErrMode<ConundrumErrorVariant>>("forestgreen").map(|_| {
                CssColor::from_rgba(34, 139, 34, 1)
            }).parse_next(input) {
                Ok(res)
            } else  if let Ok(res) = literal::<_, ConundrumInput, ErrMode<ConundrumErrorVariant>>("lavender").map(|_| {
                CssColor::from_rgba(230, 230, 250, 1)
            }).parse_next(input) {
                Ok(res)
            } else  if let Ok(res) = literal::<_, ConundrumInput, ErrMode<ConundrumErrorVariant>>("darkseagreen").map(|_| {
                CssColor::from_rgba(143, 188, 143, 1)
            }).parse_next(input) {
                Ok(res)
            } else  if let Ok(res) = literal::<_, ConundrumInput, ErrMode<ConundrumErrorVariant>>("lavenderblush").map(|_| {
                CssColor::from_rgba(255, 240, 245, 1)
            }).parse_next(input) {
                Ok(res)
            } else  if let Ok(res) = literal::<_, ConundrumInput, ErrMode<ConundrumErrorVariant>>("turquoise").map(|_| {
                CssColor::from_rgba(64, 224, 208, 1)
            }).parse_next(input) {
                Ok(res)
            } else  if let Ok(res) = literal::<_, ConundrumInput, ErrMode<ConundrumErrorVariant>>("darkkhaki").map(|_| {
                CssColor::from_rgba(189, 183, 107, 1)
            }).parse_next(input) {
                Ok(res)
            } else  if let Ok(res) = literal::<_, ConundrumInput, ErrMode<ConundrumErrorVariant>>("gray").map(|_| {
                CssColor::from_rgba(128, 128, 128, 1)
            }).parse_next(input) {
                Ok(res)
            } else  if let Ok(res) = literal::<_, ConundrumInput, ErrMode<ConundrumErrorVariant>>("lightseagreen").map(|_| {
                CssColor::from_rgba(32, 178, 170, 1)
            }).parse_next(input) {
                Ok(res)
            } else  if let Ok(res) = literal::<_, ConundrumInput, ErrMode<ConundrumErrorVariant>>("palegoldenrod").map(|_| {
                CssColor::from_rgba(238, 232, 170, 1)
            }).parse_next(input) {
                Ok(res)
            } else  if let Ok(res) = literal::<_, ConundrumInput, ErrMode<ConundrumErrorVariant>>("powderblue").map(|_| {
                CssColor::from_rgba(176, 224, 230, 1)
            }).parse_next(input) {
                Ok(res)
            } else  if let Ok(res) = literal::<_, ConundrumInput, ErrMode<ConundrumErrorVariant>>("yellowgreen").map(|_| {
                CssColor::from_rgba(154, 205, 50, 1)
            }).parse_next(input) {
                Ok(res)
            } else  if let Ok(res) = literal::<_, ConundrumInput, ErrMode<ConundrumErrorVariant>>("lightblue").map(|_| {
                CssColor::from_rgba(173, 216, 230, 1)
            }).parse_next(input) {
                Ok(res)
            } else  if let Ok(res) = literal::<_, ConundrumInput, ErrMode<ConundrumErrorVariant>>("yellow").map(|_| {
                CssColor::from_rgba(255, 255, 0, 1)
            }).parse_next(input) {
                Ok(res)
            } else  if let Ok(res) = literal::<_, ConundrumInput, ErrMode<ConundrumErrorVariant>>("indigo").map(|_| {
                CssColor::from_rgba(75, 0, 130, 1)
            }).parse_next(input) {
                Ok(res)
            } else  if let Ok(res) = literal::<_, ConundrumInput, ErrMode<ConundrumErrorVariant>>("peru").map(|_| {
                CssColor::from_rgba(205, 133, 63, 1)
            }).parse_next(input) {
                Ok(res)
            } else  if let Ok(res) = literal::<_, ConundrumInput, ErrMode<ConundrumErrorVariant>>("darkorchid").map(|_| {
                CssColor::from_rgba(153, 50, 204, 1)
            }).parse_next(input) {
                Ok(res)
            } else  if let Ok(res) = literal::<_, ConundrumInput, ErrMode<ConundrumErrorVariant>>("darkred").map(|_| {
                CssColor::from_rgba(139, 0, 0, 1)
            }).parse_next(input) {
                Ok(res)
            } else  if let Ok(res) = literal::<_, ConundrumInput, ErrMode<ConundrumErrorVariant>>("slategrey").map(|_| {
                CssColor::from_rgba(112, 128, 144, 1)
            }).parse_next(input) {
                Ok(res)
            } else  if let Ok(res) = literal::<_, ConundrumInput, ErrMode<ConundrumErrorVariant>>("oldlace").map(|_| {
                CssColor::from_rgba(253, 245, 230, 1)
            }).parse_next(input) {
                Ok(res)
            } else  if let Ok(res) = literal::<_, ConundrumInput, ErrMode<ConundrumErrorVariant>>("cornflowerblue").map(|_| {
                CssColor::from_rgba(100, 149, 237, 1)
            }).parse_next(input) {
                Ok(res)
            } else  if let Ok(res) = literal::<_, ConundrumInput, ErrMode<ConundrumErrorVariant>>("darkslategray").map(|_| {
                CssColor::from_rgba(47, 79, 79, 1)
            }).parse_next(input) {
                Ok(res)
            } else  if let Ok(res) = literal::<_, ConundrumInput, ErrMode<ConundrumErrorVariant>>("goldenrod").map(|_| {
                CssColor::from_rgba(218, 165, 32, 1)
            }).parse_next(input) {
                Ok(res)
            } else  if let Ok(res) = literal::<_, ConundrumInput, ErrMode<ConundrumErrorVariant>>("darksalmon").map(|_| {
                CssColor::from_rgba(233, 150, 122, 1)
            }).parse_next(input) {
                Ok(res)
            } else  if let Ok(res) = literal::<_, ConundrumInput, ErrMode<ConundrumErrorVariant>>("darkgoldenrod").map(|_| {
                CssColor::from_rgba(184, 134, 11, 1)
            }).parse_next(input) {
                Ok(res)
            } else  if let Ok(res) = literal::<_, ConundrumInput, ErrMode<ConundrumErrorVariant>>("khaki").map(|_| {
                CssColor::from_rgba(240, 230, 140, 1)
            }).parse_next(input) {
                Ok(res)
            } else  if let Ok(res) = literal::<_, ConundrumInput, ErrMode<ConundrumErrorVariant>>("fuchsia").map(|_| {
                CssColor::from_rgba(255, 0, 255, 1)
            }).parse_next(input) {
                Ok(res)
            } else  if let Ok(res) = literal::<_, ConundrumInput, ErrMode<ConundrumErrorVariant>>("magenta").map(|_| {
                CssColor::from_rgba(255, 0, 255, 1)
            }).parse_next(input) {
                Ok(res)
            } else  if let Ok(res) = literal::<_, ConundrumInput, ErrMode<ConundrumErrorVariant>>("palevioletred").map(|_| {
                CssColor::from_rgba(219, 112, 147, 1)
            }).parse_next(input) {
                Ok(res)
            } else  if let Ok(res) = literal::<_, ConundrumInput, ErrMode<ConundrumErrorVariant>>("white").map(|_| {
                CssColor::from_rgba(255, 255, 255, 1)
            }).parse_next(input) {
                Ok(res)
            } else  if let Ok(res) = literal::<_, ConundrumInput, ErrMode<ConundrumErrorVariant>>("violet").map(|_| {
                CssColor::from_rgba(238, 130, 238, 1)
            }).parse_next(input) {
                Ok(res)
            } else  if let Ok(res) = literal::<_, ConundrumInput, ErrMode<ConundrumErrorVariant>>("blue").map(|_| {
                CssColor::from_rgba(0, 0, 255, 1)
            }).parse_next(input) {
                Ok(res)
            } else  if let Ok(res) = literal::<_, ConundrumInput, ErrMode<ConundrumErrorVariant>>("crimson").map(|_| {
                CssColor::from_rgba(220, 20, 60, 1)
            }).parse_next(input) {
                Ok(res)
            } else  if let Ok(res) = literal::<_, ConundrumInput, ErrMode<ConundrumErrorVariant>>("lightgoldenrodyellow").map(|_| {
                CssColor::from_rgba(250, 250, 210, 1)
            }).parse_next(input) {
                Ok(res)
            } else  if let Ok(res) = literal::<_, ConundrumInput, ErrMode<ConundrumErrorVariant>>("maroon").map(|_| {
                CssColor::from_rgba(128, 0, 0, 1)
            }).parse_next(input) {
                Ok(res)
            } else  if let Ok(res) = literal::<_, ConundrumInput, ErrMode<ConundrumErrorVariant>>("mediumpurple").map(|_| {
                CssColor::from_rgba(147, 112, 219, 1)
            }).parse_next(input) {
                Ok(res)
            } else  if let Ok(res) = literal::<_, ConundrumInput, ErrMode<ConundrumErrorVariant>>("darkblue").map(|_| {
                CssColor::from_rgba(0, 0, 139, 1)
            }).parse_next(input) {
                Ok(res)
            } else  if let Ok(res) = literal::<_, ConundrumInput, ErrMode<ConundrumErrorVariant>>("coral").map(|_| {
                CssColor::from_rgba(255, 127, 80, 1)
            }).parse_next(input) {
                Ok(res)
            } else  if let Ok(res) = literal::<_, ConundrumInput, ErrMode<ConundrumErrorVariant>>("deeppink").map(|_| {
                CssColor::from_rgba(255, 20, 147, 1)
            }).parse_next(input) {
                Ok(res)
            } else  if let Ok(res) = literal::<_, ConundrumInput, ErrMode<ConundrumErrorVariant>>("moccasin").map(|_| {
                CssColor::from_rgba(255, 228, 181, 1)
            }).parse_next(input) {
                Ok(res)
            } else  if let Ok(res) = literal::<_, ConundrumInput, ErrMode<ConundrumErrorVariant>>("lightsteelblue").map(|_| {
                CssColor::from_rgba(176, 196, 222, 1)
            }).parse_next(input) {
                Ok(res)
            } else  if let Ok(res) = literal::<_, ConundrumInput, ErrMode<ConundrumErrorVariant>>("lawngreen").map(|_| {
                CssColor::from_rgba(124, 252, 0, 1)
            }).parse_next(input) {
                Ok(res)
            } else  if let Ok(res) = literal::<_, ConundrumInput, ErrMode<ConundrumErrorVariant>>("mediumspringgreen").map(|_| {
                CssColor::from_rgba(0, 250, 154, 1)
            }).parse_next(input) {
                Ok(res)
            } else  if let Ok(res) = literal::<_, ConundrumInput, ErrMode<ConundrumErrorVariant>>("black").map(|_| {
                CssColor::from_rgba(0, 0, 0, 1)
            }).parse_next(input) {
                Ok(res)
            } else  if let Ok(res) = literal::<_, ConundrumInput, ErrMode<ConundrumErrorVariant>>("antiquewhite").map(|_| {
                CssColor::from_rgba(250, 235, 215, 1)
            }).parse_next(input) {
                Ok(res)
            } else  if let Ok(res) = literal::<_, ConundrumInput, ErrMode<ConundrumErrorVariant>>("lightcoral").map(|_| {
                CssColor::from_rgba(240, 128, 128, 1)
            }).parse_next(input) {
                Ok(res)
            } else  if let Ok(res) = literal::<_, ConundrumInput, ErrMode<ConundrumErrorVariant>>("midnightblue").map(|_| {
                CssColor::from_rgba(25, 25, 112, 1)
            }).parse_next(input) {
                Ok(res)
            } else  if let Ok(res) = literal::<_, ConundrumInput, ErrMode<ConundrumErrorVariant>>("lightskyblue").map(|_| {
                CssColor::from_rgba(135, 206, 250, 1)
            }).parse_next(input) {
                Ok(res)
            } else  if let Ok(res) = literal::<_, ConundrumInput, ErrMode<ConundrumErrorVariant>>("burlywood").map(|_| {
                CssColor::from_rgba(222, 184, 135, 1)
            }).parse_next(input) {
                Ok(res)
            } else  if let Ok(res) = literal::<_, ConundrumInput, ErrMode<ConundrumErrorVariant>>("red").map(|_| {
                CssColor::from_rgba(255, 0, 0, 1)
            }).parse_next(input) {
                Ok(res)
            } else  if let Ok(res) = literal::<_, ConundrumInput, ErrMode<ConundrumErrorVariant>>("lightcyan").map(|_| {
                CssColor::from_rgba(224, 255, 255, 1)
            }).parse_next(input) {
                Ok(res)
            } else  if let Ok(res) = literal::<_, ConundrumInput, ErrMode<ConundrumErrorVariant>>("sandybrown").map(|_| {
                CssColor::from_rgba(244, 164, 96, 1)
            }).parse_next(input) {
                Ok(res)
            } else  if let Ok(res) = literal::<_, ConundrumInput, ErrMode<ConundrumErrorVariant>>("darkgrey").map(|_| {
                CssColor::from_rgba(169, 169, 169, 1)
            }).parse_next(input) {
                Ok(res)
            } else  if let Ok(res) = literal::<_, ConundrumInput, ErrMode<ConundrumErrorVariant>>("silver").map(|_| {
                CssColor::from_rgba(192, 192, 192, 1)
            }).parse_next(input) {
                Ok(res)
            } else  if let Ok(res) = literal::<_, ConundrumInput, ErrMode<ConundrumErrorVariant>>("springgreen").map(|_| {
                CssColor::from_rgba(0, 255, 127, 1)
            }).parse_next(input) {
                Ok(res)
            } else  if let Ok(res) = literal::<_, ConundrumInput, ErrMode<ConundrumErrorVariant>>("lightgray").map(|_| {
                CssColor::from_rgba(211, 211, 211, 1)
            }).parse_next(input) {
                Ok(res)
            } else  if let Ok(res) = literal::<_, ConundrumInput, ErrMode<ConundrumErrorVariant>>("ghostwhite").map(|_| {
                CssColor::from_rgba(248, 248, 255, 1)
            }).parse_next(input) {
                Ok(res)
            } else  if let Ok(res) = literal::<_, ConundrumInput, ErrMode<ConundrumErrorVariant>>("rosybrown").map(|_| {
                CssColor::from_rgba(188, 143, 143, 1)
            }).parse_next(input) {
                Ok(res)
            } else  if let Ok(res) = literal::<_, ConundrumInput, ErrMode<ConundrumErrorVariant>>("aliceblue").map(|_| {
                CssColor::from_rgba(240, 248, 255, 1)
            }).parse_next(input) {
                Ok(res)
            } else  if let Ok(res) = literal::<_, ConundrumInput, ErrMode<ConundrumErrorVariant>>("dimgray").map(|_| {
                CssColor::from_rgba(105, 105, 105, 1)
            }).parse_next(input) {
                Ok(res)
            } else  if let Ok(res) = literal::<_, ConundrumInput, ErrMode<ConundrumErrorVariant>>("aqua").map(|_| {
                CssColor::from_rgba(0, 255, 255, 1)
            }).parse_next(input) {
                Ok(res)
            } else  if let Ok(res) = literal::<_, ConundrumInput, ErrMode<ConundrumErrorVariant>>("darkorange").map(|_| {
                CssColor::from_rgba(255, 140, 0, 1)
            }).parse_next(input) {
                Ok(res)
            } else  if let Ok(res) = literal::<_, ConundrumInput, ErrMode<ConundrumErrorVariant>>("hotpink").map(|_| {
                CssColor::from_rgba(255, 105, 180, 1)
            }).parse_next(input) {
                Ok(res)
            } else  if let Ok(res) = literal::<_, ConundrumInput, ErrMode<ConundrumErrorVariant>>("sienna").map(|_| {
                CssColor::from_rgba(160, 82, 45, 1)
            }).parse_next(input) {
                Ok(res)
            } else  if let Ok(res) = literal::<_, ConundrumInput, ErrMode<ConundrumErrorVariant>>("pink").map(|_| {
                CssColor::from_rgba(255, 192, 203, 1)
            }).parse_next(input) {
                Ok(res)
            } else  if let Ok(res) = literal::<_, ConundrumInput, ErrMode<ConundrumErrorVariant>>("dimgrey").map(|_| {
                CssColor::from_rgba(105, 105, 105, 1)
            }).parse_next(input) {
                Ok(res)
            } else  if let Ok(res) = literal::<_, ConundrumInput, ErrMode<ConundrumErrorVariant>>("firebrick").map(|_| {
                CssColor::from_rgba(178, 34, 34, 1)
            }).parse_next(input) {
                Ok(res)
            } else  if let Ok(res) = literal::<_, ConundrumInput, ErrMode<ConundrumErrorVariant>>("saddlebrown").map(|_| {
                CssColor::from_rgba(139, 69, 19, 1)
            }).parse_next(input) {
                Ok(res)
            } else  if let Ok(res) = literal::<_, ConundrumInput, ErrMode<ConundrumErrorVariant>>("mistyrose").map(|_| {
                CssColor::from_rgba(255, 228, 225, 1)
            }).parse_next(input) {
                Ok(res)
            } else  if let Ok(res) = literal::<_, ConundrumInput, ErrMode<ConundrumErrorVariant>>("chartreuse").map(|_| {
                CssColor::from_rgba(127, 255, 0, 1)
            }).parse_next(input) {
                Ok(res)
            } else  if let Ok(res) = literal::<_, ConundrumInput, ErrMode<ConundrumErrorVariant>>("royalblue").map(|_| {
                CssColor::from_rgba(65, 105, 225, 1)
            }).parse_next(input) {
                Ok(res)
            } else  if let Ok(res) = literal::<_, ConundrumInput, ErrMode<ConundrumErrorVariant>>("cadetblue").map(|_| {
                CssColor::from_rgba(95, 158, 160, 1)
            }).parse_next(input) {
                Ok(res)
            } else  if let Ok(res) = literal::<_, ConundrumInput, ErrMode<ConundrumErrorVariant>>("seagreen").map(|_| {
                CssColor::from_rgba(46, 139, 87, 1)
            }).parse_next(input) {
                Ok(res)
            } else  if let Ok(res) = literal::<_, ConundrumInput, ErrMode<ConundrumErrorVariant>>("darkslategrey").map(|_| {
                CssColor::from_rgba(47, 79, 79, 1)
            }).parse_next(input) {
                Ok(res)
            } else  if let Ok(res) = literal::<_, ConundrumInput, ErrMode<ConundrumErrorVariant>>("lightyellow").map(|_| {
                CssColor::from_rgba(255, 255, 224, 1)
            }).parse_next(input) {
                Ok(res)
            } else  if let Ok(res) = literal::<_, ConundrumInput, ErrMode<ConundrumErrorVariant>>("orangered").map(|_| {
                CssColor::from_rgba(255, 69, 0, 1)
            }).parse_next(input) {
                Ok(res)
            } else  if let Ok(res) = literal::<_, ConundrumInput, ErrMode<ConundrumErrorVariant>>("gainsboro").map(|_| {
                CssColor::from_rgba(220, 220, 220, 1)
            }).parse_next(input) {
                Ok(res)
            } else  if let Ok(res) = literal::<_, ConundrumInput, ErrMode<ConundrumErrorVariant>>("thistle").map(|_| {
                CssColor::from_rgba(216, 191, 216, 1)
            }).parse_next(input) {
                Ok(res)
            } else  if let Ok(res) = literal::<_, ConundrumInput, ErrMode<ConundrumErrorVariant>>("palegreen").map(|_| {
                CssColor::from_rgba(152, 251, 152, 1)
            }).parse_next(input) {
                Ok(res)
            } else  if let Ok(res) = literal::<_, ConundrumInput, ErrMode<ConundrumErrorVariant>>("darkturquoise").map(|_| {
                CssColor::from_rgba(0, 206, 209, 1)
            }).parse_next(input) {
                Ok(res)
            } else  if let Ok(res) = literal::<_, ConundrumInput, ErrMode<ConundrumErrorVariant>>("darkcyan").map(|_| {
                CssColor::from_rgba(0, 139, 139, 1)
            }).parse_next(input) {
                Ok(res)
            } else  if let Ok(res) = literal::<_, ConundrumInput, ErrMode<ConundrumErrorVariant>>("mediumslateblue").map(|_| {
                CssColor::from_rgba(123, 104, 238, 1)
            }).parse_next(input) {
                Ok(res)
            } else  if let Ok(res) = literal::<_, ConundrumInput, ErrMode<ConundrumErrorVariant>>("cyan").map(|_| {
                CssColor::from_rgba(0, 255, 255, 1)
            }).parse_next(input) {
                Ok(res)
            } else  if let Ok(res) = literal::<_, ConundrumInput, ErrMode<ConundrumErrorVariant>>("floralwhite").map(|_| {
                CssColor::from_rgba(255, 250, 240, 1)
            }).parse_next(input) {
                Ok(res)
            } else  if let Ok(res) = literal::<_, ConundrumInput, ErrMode<ConundrumErrorVariant>>("rebeccapurple").map(|_| {
                CssColor::from_rgba(102, 51, 153, 1)
            }).parse_next(input) {
                Ok(res)
            } else  if let Ok(res) = literal::<_, ConundrumInput, ErrMode<ConundrumErrorVariant>>("wheat").map(|_| {
                CssColor::from_rgba(245, 222, 179, 1)
            }).parse_next(input) {
                Ok(res)
            } else  if let Ok(res) = literal::<_, ConundrumInput, ErrMode<ConundrumErrorVariant>>("seashell").map(|_| {
                CssColor::from_rgba(255, 245, 238, 1)
            }).parse_next(input) {
                Ok(res)
            } else  if let Ok(res) = literal::<_, ConundrumInput, ErrMode<ConundrumErrorVariant>>("honeydew").map(|_| {
                CssColor::from_rgba(240, 255, 240, 1)
            }).parse_next(input) {
                Ok(res)
            } else  if let Ok(res) = literal::<_, ConundrumInput, ErrMode<ConundrumErrorVariant>>("whitesmoke").map(|_| {
                CssColor::from_rgba(245, 245, 245, 1)
            }).parse_next(input) {
                Ok(res)
            } else  if let Ok(res) = literal::<_, ConundrumInput, ErrMode<ConundrumErrorVariant>>("indianred").map(|_| {
                CssColor::from_rgba(205, 92, 92, 1)
            }).parse_next(input) {
                Ok(res)
            } else  if let Ok(res) = literal::<_, ConundrumInput, ErrMode<ConundrumErrorVariant>>("papayawhip").map(|_| {
                CssColor::from_rgba(255, 239, 213, 1)
            }).parse_next(input) {
                Ok(res)
            } else  if let Ok(res) = literal::<_, ConundrumInput, ErrMode<ConundrumErrorVariant>>("mediumblue").map(|_| {
                CssColor::from_rgba(0, 0, 205, 1)
            }).parse_next(input) {
                Ok(res)
            } else  {
                Err(
                    ErrMode::Backtrack(ConundrumErrorVariant::InternalParserError(ConundrumError::from_message("Not a named color")))
                )
            }
}