// @ts-nocheck -- skip type checking
import * as documentation_6 from "../content/docs/developer/index.mdx?collection=documentation&hash=1767747565020"
import * as documentation_5 from "../content/docs/developer/developer_setup.mdx?collection=documentation&hash=1767747565020"
import * as documentation_4 from "../content/docs/user/special_files.mdx?collection=documentation&hash=1767747565020"
import * as documentation_3 from "../content/docs/user/intro_to_jsx.mdx?collection=documentation&hash=1767747565020"
import * as documentation_2 from "../content/docs/user/index.mdx?collection=documentation&hash=1767747565020"
import * as documentation_1 from "../content/docs/user/front_matter.mdx?collection=documentation&hash=1767747565020"
import * as documentation_0 from "../content/docs/my_work/on_the_gravitational_nature_of_time.mdx?collection=documentation&hash=1767747565020"
import * as metaFiles_3 from "../content/docs/user/meta.json?collection=metaFiles&hash=1767747565020"
import * as metaFiles_2 from "../content/docs/my_work/meta.json?collection=metaFiles&hash=1767747565020"
import * as metaFiles_1 from "../content/docs/developer/meta.json?collection=metaFiles&hash=1767747565020"
import * as metaFiles_0 from "../content/docs/meta.json?collection=metaFiles&hash=1767747565020"
import * as docs_6 from "../content/docs/user/special_files.mdx?collection=docs&hash=1767747565020"
import * as docs_5 from "../content/docs/user/intro_to_jsx.mdx?collection=docs&hash=1767747565020"
import * as docs_4 from "../content/docs/user/index.mdx?collection=docs&hash=1767747565020"
import * as docs_3 from "../content/docs/user/front_matter.mdx?collection=docs&hash=1767747565020"
import * as docs_2 from "../content/docs/my_work/on_the_gravitational_nature_of_time.mdx?collection=docs&hash=1767747565020"
import * as docs_1 from "../content/docs/developer/index.mdx?collection=docs&hash=1767747565020"
import * as docs_0 from "../content/docs/developer/developer_setup.mdx?collection=docs&hash=1767747565020"
import { _runtime } from "fumadocs-mdx"
import * as _source from "../source.config"
export const docs = _runtime.doc<typeof _source.docs>([{ info: {"path":"developer/developer_setup.mdx","absolutePath":"/Users/bigsexy/Desktop/swift/Fluster/apps/website/content/docs/developer/developer_setup.mdx"}, data: docs_0 }, { info: {"path":"developer/index.mdx","absolutePath":"/Users/bigsexy/Desktop/swift/Fluster/apps/website/content/docs/developer/index.mdx"}, data: docs_1 }, { info: {"path":"my_work/on_the_gravitational_nature_of_time.mdx","absolutePath":"/Users/bigsexy/Desktop/swift/Fluster/apps/website/content/docs/my_work/on_the_gravitational_nature_of_time.mdx"}, data: docs_2 }, { info: {"path":"user/front_matter.mdx","absolutePath":"/Users/bigsexy/Desktop/swift/Fluster/apps/website/content/docs/user/front_matter.mdx"}, data: docs_3 }, { info: {"path":"user/index.mdx","absolutePath":"/Users/bigsexy/Desktop/swift/Fluster/apps/website/content/docs/user/index.mdx"}, data: docs_4 }, { info: {"path":"user/intro_to_jsx.mdx","absolutePath":"/Users/bigsexy/Desktop/swift/Fluster/apps/website/content/docs/user/intro_to_jsx.mdx"}, data: docs_5 }, { info: {"path":"user/special_files.mdx","absolutePath":"/Users/bigsexy/Desktop/swift/Fluster/apps/website/content/docs/user/special_files.mdx"}, data: docs_6 }]);
export const documentation = _runtime.docs<typeof _source.documentation>([{ info: {"path":"my_work/on_the_gravitational_nature_of_time.mdx","absolutePath":"/Users/bigsexy/Desktop/swift/Fluster/apps/website/content/docs/my_work/on_the_gravitational_nature_of_time.mdx"}, data: documentation_0 }, { info: {"path":"user/front_matter.mdx","absolutePath":"/Users/bigsexy/Desktop/swift/Fluster/apps/website/content/docs/user/front_matter.mdx"}, data: documentation_1 }, { info: {"path":"user/index.mdx","absolutePath":"/Users/bigsexy/Desktop/swift/Fluster/apps/website/content/docs/user/index.mdx"}, data: documentation_2 }, { info: {"path":"user/intro_to_jsx.mdx","absolutePath":"/Users/bigsexy/Desktop/swift/Fluster/apps/website/content/docs/user/intro_to_jsx.mdx"}, data: documentation_3 }, { info: {"path":"user/special_files.mdx","absolutePath":"/Users/bigsexy/Desktop/swift/Fluster/apps/website/content/docs/user/special_files.mdx"}, data: documentation_4 }, { info: {"path":"developer/developer_setup.mdx","absolutePath":"/Users/bigsexy/Desktop/swift/Fluster/apps/website/content/docs/developer/developer_setup.mdx"}, data: documentation_5 }, { info: {"path":"developer/index.mdx","absolutePath":"/Users/bigsexy/Desktop/swift/Fluster/apps/website/content/docs/developer/index.mdx"}, data: documentation_6 }], [{"info":{"path":"meta.json","absolutePath":"/Users/bigsexy/Desktop/swift/Fluster/apps/website/content/docs/meta.json"},"data":{"pages":["user","developer","my_work"]}}, {"info":{"path":"developer/meta.json","absolutePath":"/Users/bigsexy/Desktop/swift/Fluster/apps/website/content/docs/developer/meta.json"},"data":{"title":"Developer"}}, {"info":{"path":"my_work/meta.json","absolutePath":"/Users/bigsexy/Desktop/swift/Fluster/apps/website/content/docs/my_work/meta.json"},"data":{"title":"My Work"}}, {"info":{"path":"user/meta.json","absolutePath":"/Users/bigsexy/Desktop/swift/Fluster/apps/website/content/docs/user/meta.json"},"data":{"title":"User"}}])
export const legal = _runtime.doc<typeof _source.legal>([]);
export const metaFiles = _runtime.meta<typeof _source.metaFiles>([{ info: {"path":"docs/meta.json","absolutePath":"/Users/bigsexy/Desktop/swift/Fluster/apps/website/content/docs/meta.json"}, data: metaFiles_0 }, { info: {"path":"docs/developer/meta.json","absolutePath":"/Users/bigsexy/Desktop/swift/Fluster/apps/website/content/docs/developer/meta.json"}, data: metaFiles_1 }, { info: {"path":"docs/my_work/meta.json","absolutePath":"/Users/bigsexy/Desktop/swift/Fluster/apps/website/content/docs/my_work/meta.json"}, data: metaFiles_2 }, { info: {"path":"docs/user/meta.json","absolutePath":"/Users/bigsexy/Desktop/swift/Fluster/apps/website/content/docs/user/meta.json"}, data: metaFiles_3 }]);
export const myWork = _runtime.docs<typeof _source.myWork>([], [])