// @ts-nocheck -- skip type checking
import * as documentation_2 from "../content/docs/user/index.mdx?collection=documentation&hash=1773524373568"
import * as documentation_1 from "../content/docs/my_work/on_the_gravitational_nature_of_time.mdx?collection=documentation&hash=1773524373568"
import * as documentation_0 from "../content/docs/blog/initial_launch.mdx?collection=documentation&hash=1773524373568"
import * as metaFiles_3 from "../content/docs/my_work/meta.json?collection=metaFiles&hash=1773524373568"
import * as metaFiles_2 from "../content/docs/user/meta.json?collection=metaFiles&hash=1773524373568"
import * as metaFiles_1 from "../content/docs/blog/meta.json?collection=metaFiles&hash=1773524373568"
import * as metaFiles_0 from "../content/docs/meta.json?collection=metaFiles&hash=1773524373568"
import * as docs_2 from "../content/docs/user/index.mdx?collection=docs&hash=1773524373568"
import * as docs_1 from "../content/docs/my_work/on_the_gravitational_nature_of_time.mdx?collection=docs&hash=1773524373568"
import * as docs_0 from "../content/docs/blog/initial_launch.mdx?collection=docs&hash=1773524373568"
import { _runtime } from "fumadocs-mdx"
import * as _source from "../source.config"
export const docs = _runtime.doc<typeof _source.docs>([{ info: {"path":"blog/initial_launch.mdx","absolutePath":"/Users/bigsexy/Desktop/swift/Fluster/apps/website/content/docs/blog/initial_launch.mdx"}, data: docs_0 }, { info: {"path":"my_work/on_the_gravitational_nature_of_time.mdx","absolutePath":"/Users/bigsexy/Desktop/swift/Fluster/apps/website/content/docs/my_work/on_the_gravitational_nature_of_time.mdx"}, data: docs_1 }, { info: {"path":"user/index.mdx","absolutePath":"/Users/bigsexy/Desktop/swift/Fluster/apps/website/content/docs/user/index.mdx"}, data: docs_2 }]);
export const documentation = _runtime.docs<typeof _source.documentation>([{ info: {"path":"blog/initial_launch.mdx","absolutePath":"/Users/bigsexy/Desktop/swift/Fluster/apps/website/content/docs/blog/initial_launch.mdx"}, data: documentation_0 }, { info: {"path":"my_work/on_the_gravitational_nature_of_time.mdx","absolutePath":"/Users/bigsexy/Desktop/swift/Fluster/apps/website/content/docs/my_work/on_the_gravitational_nature_of_time.mdx"}, data: documentation_1 }, { info: {"path":"user/index.mdx","absolutePath":"/Users/bigsexy/Desktop/swift/Fluster/apps/website/content/docs/user/index.mdx"}, data: documentation_2 }], [{"info":{"path":"meta.json","absolutePath":"/Users/bigsexy/Desktop/swift/Fluster/apps/website/content/docs/meta.json"},"data":{"pages":["user","my_work","blog"]}}, {"info":{"path":"blog/meta.json","absolutePath":"/Users/bigsexy/Desktop/swift/Fluster/apps/website/content/docs/blog/meta.json"},"data":{"title":"Blog"}}, {"info":{"path":"my_work/meta.json","absolutePath":"/Users/bigsexy/Desktop/swift/Fluster/apps/website/content/docs/my_work/meta.json"},"data":{"title":"My Work"}}, {"info":{"path":"user/meta.json","absolutePath":"/Users/bigsexy/Desktop/swift/Fluster/apps/website/content/docs/user/meta.json"},"data":{"title":"User"}}])
export const legal = _runtime.doc<typeof _source.legal>([]);
export const metaFiles = _runtime.meta<typeof _source.metaFiles>([{ info: {"path":"docs/meta.json","absolutePath":"/Users/bigsexy/Desktop/swift/Fluster/apps/website/content/docs/meta.json"}, data: metaFiles_0 }, { info: {"path":"docs/blog/meta.json","absolutePath":"/Users/bigsexy/Desktop/swift/Fluster/apps/website/content/docs/blog/meta.json"}, data: metaFiles_1 }, { info: {"path":"docs/user/meta.json","absolutePath":"/Users/bigsexy/Desktop/swift/Fluster/apps/website/content/docs/user/meta.json"}, data: metaFiles_2 }, { info: {"path":"docs/my_work/meta.json","absolutePath":"/Users/bigsexy/Desktop/swift/Fluster/apps/website/content/docs/my_work/meta.json"}, data: metaFiles_3 }]);
export const myWork = _runtime.docs<typeof _source.myWork>([], [])