// WARN: This file is automatically generated. Any work done here, and not
use crate::lang::lib::ui::ui_types::emphasis::emphasis_model::Emphasis;
use crate::lang::runtime::state::conundrum_error_variant::ConundrumModalResult;
use crate::parsers::conundrum::color::color_scheme_group::{ColorSchemeGroup, ConundrumCompleteColor};
use crate::parsers::conundrum::color::css_color::CssColor;
use crate::parsers::conundrum::color::{color_pair::ColorPair, conundrum_color::ConundrumColor};

pub fn emphasis_to_default_complete_color(emphasis: Emphasis) -> ConundrumModalResult<ConundrumCompleteColor> {
    match emphasis {
        Emphasis::Info => {
            Ok(ColorSchemeGroup { light: ColorPair { background: ConundrumColor::Css(CssColor::try_from("hsl(221.0, 100.0%, 65.0%)")?),
                                                     foreground: ConundrumColor::Css(CssColor::try_from("hsl(0, 0%, 100%)")?) },
                                  dark: ColorPair { background: ConundrumColor::Css(CssColor::try_from("hsl(221.0, 100.0%, 65.0%)")?),
                                                    foreground: ConundrumColor::Css(CssColor::try_from("hsl(0, 0%, 100%)")?) } })
        }

        Emphasis::Error => {
            Ok(ColorSchemeGroup { light: ColorPair { background: ConundrumColor::Css(CssColor::try_from("hsl(0.0, 100.0%, 50.0%)")?),
                                                     foreground: ConundrumColor::Css(CssColor::try_from("hsl(0, 0%, 100%)")?) },
                                  dark: ColorPair { background: ConundrumColor::Css(CssColor::try_from("hsl(0.0, 100.0%, 65.0%)")?),
                                                    foreground: ConundrumColor::Css(CssColor::try_from("hsl(0, 0%, 100%)")?) } })
        }

        Emphasis::Important => {
            Ok(ColorSchemeGroup { light: ColorPair { background: ConundrumColor::Css(CssColor::try_from("hsl(270.0, 100.0%, 55.0%)")?),
                                                     foreground: ConundrumColor::Css(CssColor::try_from("hsl(0, 0%, 100%)")?) },
                                  dark: ColorPair { background: ConundrumColor::Css(CssColor::try_from("hsl(270.0, 100.0%, 70.0%)")?),
                                                    foreground: ConundrumColor::Css(CssColor::try_from("hsl(0, 0%, 100%)")?) } })
        }

        Emphasis::Research => {
            Ok(ColorSchemeGroup { light: ColorPair { background: ConundrumColor::Css(CssColor::try_from("hsl(185.0, 100.0%, 40.0%)")?),
                                                     foreground: ConundrumColor::Css(CssColor::try_from("hsl(0, 0%, 100%)")?) },
                                  dark: ColorPair { background: ConundrumColor::Css(CssColor::try_from("hsl(185.0, 100.0%, 50.0%)")?),
                                                    foreground: ConundrumColor::Css(CssColor::try_from("hsl(222.2, 84%, 4.9%)")?) } })
        }

        Emphasis::Warn => {
            Ok(ColorSchemeGroup { light: ColorPair { background: ConundrumColor::Css(CssColor::try_from("hsl(20.0, 100.0%, 55.0%)")?),
                                                     foreground: ConundrumColor::Css(CssColor::try_from("hsl(222.2, 84%, 4.9%)")?) },
                                  dark: ColorPair { background: ConundrumColor::Css(CssColor::try_from("hsl(20.0, 100.0%, 55.0%)")?),
                                                    foreground: ConundrumColor::Css(CssColor::try_from("hsl(222.2, 84%, 4.9%)")?) } })
        }

        Emphasis::Success => {
            Ok(ColorSchemeGroup { light: ColorPair { background: ConundrumColor::Css(CssColor::try_from("hsl(142, 100%, 40%)")?),
                                                     foreground: ConundrumColor::Css(CssColor::try_from("hsl(0, 0%, 100%)")?) },
                                  dark: ColorPair { background: ConundrumColor::Css(CssColor::try_from("hsl(142, 100%, 50%)")?),
                                                    foreground: ConundrumColor::Css(CssColor::try_from("hsl(222.2, 84%, 4.9%)")?) } })
        }

        Emphasis::Highlight => {
            Ok(ColorSchemeGroup { light: ColorPair { background: ConundrumColor::Css(CssColor::try_from("hsl(60, 100%, 48%)")?),
                                                     foreground: ConundrumColor::Css(CssColor::try_from("hsl(222.2, 84%, 4.9%)")?) },
                                  dark: ColorPair { background: ConundrumColor::Css(CssColor::try_from("hsl(60, 100%, 48%)")?),
                                                    foreground: ConundrumColor::Css(CssColor::try_from("hsl(222.2, 84%, 4.9%)")?) } })
        }
    }
}
