// WARN: This file is automatically generated. Any work done here, and not
use crate::lang::{
    lib::ui::ui_types::emphasis::emphasis_model::Emphasis,
    runtime::{state::conundrum_error_variant::ConundrumModalResult, traits::conundrum_input::ConundrumInput},
};

use winnow::{Parser, combinator::alt, token::literal};

pub fn emphasis_css_variable(input: &mut ConundrumInput) -> ConundrumModalResult<Emphasis> {
     alt((  
literal("--color-emphasis-info").value(Emphasis::Info),
literal("--color-emphasis-info-foreground").value(Emphasis::Info),  
literal("--color-emphasis-error").value(Emphasis::Error),
literal("--color-emphasis-error-foreground").value(Emphasis::Error),  
literal("--color-emphasis-warn").value(Emphasis::Warn),
literal("--color-emphasis-warn-foreground").value(Emphasis::Warn),  
literal("--color-emphasis-success").value(Emphasis::Success),
literal("--color-emphasis-success-foreground").value(Emphasis::Success),  
literal("--color-emphasis-primary").value(Emphasis::Primary),
literal("--color-emphasis-primary-foreground").value(Emphasis::Primary),  
literal("--color-emphasis-important").value(Emphasis::Important),
literal("--color-emphasis-important-foreground").value(Emphasis::Important),  
literal("--color-emphasis-research").value(Emphasis::Research),
literal("--color-emphasis-research-foreground").value(Emphasis::Research),  
literal("--color-emphasis-highlight").value(Emphasis::Highlight),
literal("--color-emphasis-highlight-foreground").value(Emphasis::Highlight),  
literal("--color-fd-card").value(Emphasis::Card),
literal("--color-fd-card-foreground").value(Emphasis::Card), 
    )).parse_next(input)
}

pub fn css_variable_to_emphasis(variable: &str) -> Option<Emphasis> {
      match variable { 
        "--color-emphasis-info" => Some(Emphasis::Info),
        "--color-emphasis-info-foreground" => Some(Emphasis::Info), 
        "--color-emphasis-error" => Some(Emphasis::Error),
        "--color-emphasis-error-foreground" => Some(Emphasis::Error), 
        "--color-emphasis-warn" => Some(Emphasis::Warn),
        "--color-emphasis-warn-foreground" => Some(Emphasis::Warn), 
        "--color-emphasis-success" => Some(Emphasis::Success),
        "--color-emphasis-success-foreground" => Some(Emphasis::Success), 
        "--color-emphasis-primary" => Some(Emphasis::Primary),
        "--color-emphasis-primary-foreground" => Some(Emphasis::Primary), 
        "--color-emphasis-important" => Some(Emphasis::Important),
        "--color-emphasis-important-foreground" => Some(Emphasis::Important), 
        "--color-emphasis-research" => Some(Emphasis::Research),
        "--color-emphasis-research-foreground" => Some(Emphasis::Research), 
        "--color-emphasis-highlight" => Some(Emphasis::Highlight),
        "--color-emphasis-highlight-foreground" => Some(Emphasis::Highlight), 
        "--color-fd-card" => Some(Emphasis::Card),
        "--color-fd-card-foreground" => Some(Emphasis::Card),  
        _ => None
       }
}