// WARN: This file is automatically generated. Any work done here, and not
use crate::lang::lib::ui::ui_types::emphasis::emphasis_model::Emphasis;

pub fn css_variable_to_emphasis(variable: &str) -> Option<Emphasis> {
      match variable { 
        "--color-emphasis-info" => Some(Emphasis::Info),
        "--color-emphasis-info-foreground" => Some(Emphasis::Info), 
        "--color-emphasis-error" => Some(Emphasis::Error),
        "--color-emphasis-error-foreground" => Some(Emphasis::Error), 
        "--color-emphasis-warn" => Some(Emphasis::Warn),
        "--color-emphasis-warn-foreground" => Some(Emphasis::Warn), 
        "--color-emphasis-success" => Some(Emphasis::Success),
        "--color-emphasis-success-foreground" => Some(Emphasis::Success), 
        "--color-primary" => Some(Emphasis::Primary),
        "--color-primary-foreground" => Some(Emphasis::Primary), 
        "--color-emphasis-important" => Some(Emphasis::Important),
        "--color-emphasis-important-foreground" => Some(Emphasis::Important), 
        "--color-emphasis-research" => Some(Emphasis::Research),
        "--color-emphasis-research-foreground" => Some(Emphasis::Research), 
        "--color-emphasis-highlight" => Some(Emphasis::Highlight),
        "--color-emphasis-highlight-foreground" => Some(Emphasis::Highlight), 
        "--color-fd-card" => Some(Emphasis::Card),
        "--color-fd-card-foreground" => Some(Emphasis::Card),  
        _ => None
       }
}