/*
 Generated by typeshare 1.13.3
 */

import Foundation

public struct CodeBlockParsingResult: Codable {
	public let full_match: String
	public let language_tag: String
	public let block_content: String

	public init(full_match: String, language_tag: String, block_content: String) {
		self.full_match = full_match
		self.language_tag = language_tag
		self.block_content = block_content
	}
}

/// From typescript to swift.
public enum WebviewEnvironment: String, Codable {
	case macOS = "fluster-mac"
	case iPad = "fluster-ipad"
	case multiPlatformDesktop = "fluster-multi-platform-desktop"
}

public enum WebviewImplementation: String, Codable {
	case bibEditor = "bib-editor"
	case mdxEditor = "mdx-editor"
	case mdxViewer = "mdx-viewer"
	case development
	case awaitingData = "pending"
}

public enum FlusterTheme: String, Codable, CaseIterable {
	case zinc
	case yellow
	case violet
	case fluster
	case stone
	case slate
	case rose
	case red
	case orange
	case neutral
	case green
	case gray
	case blue
}

public struct WebviewContainerSharedInitialState: Codable {
	public let environment: WebviewEnvironment
	public let dark_mode: Bool
	public let implementation: WebviewImplementation
	public let fluster_theme: FlusterTheme

	public init(environment: WebviewEnvironment, dark_mode: Bool, implementation: WebviewImplementation, fluster_theme: FlusterTheme) {
		self.environment = environment
		self.dark_mode = dark_mode
		self.implementation = implementation
		self.fluster_theme = fluster_theme
	}
}

public enum CodeEditorKeymap: String, Codable, CaseIterable {
	case vim
	case base
	case emacs
}

public enum CodeEditorTheme: String, Codable, CaseIterable {
	case materialLight
	case solarizedLight
	case solarizedDark
	case githubLight
	case aura
	case tokyoNightDay
	case xcodeLight
	case dracula
	case tokyoNight
	case materialDark
	case tokyoNightStorm
	case githubDark
	case xcodeDark
}

public struct SnippetState: Codable {
	public let includeEmojiSnippets: Bool

	public init(includeEmojiSnippets: Bool) {
		self.includeEmojiSnippets = includeEmojiSnippets
	}
}

public enum EditorSaveMethod: String, Codable {
	case onSave = "on-save"
	case onChange = "on-change"
}

public struct EditorInitialStatePayload: Codable {
	public let note_id: String
	public let keymap: CodeEditorKeymap
	public let theme: CodeEditorTheme
	public let allCitationIds: [String]
	public let value: String
	public let parsedValue: String
	public let haveSetInitialValue: Bool
	public let snippetProps: SnippetState
	public let lockEditorScrollToPreview: Bool
	public let saveMethod: EditorSaveMethod

	public init(note_id: String, keymap: CodeEditorKeymap, theme: CodeEditorTheme, allCitationIds: [String], value: String, parsedValue: String, haveSetInitialValue: Bool, snippetProps: SnippetState, lockEditorScrollToPreview: Bool, saveMethod: EditorSaveMethod) {
		self.note_id = note_id
		self.keymap = keymap
		self.theme = theme
		self.allCitationIds = allCitationIds
		self.value = value
		self.parsedValue = parsedValue
		self.haveSetInitialValue = haveSetInitialValue
		self.snippetProps = snippetProps
		self.lockEditorScrollToPreview = lockEditorScrollToPreview
		self.saveMethod = saveMethod
	}
}

public struct EditorBasedWebviewInitialState: Codable {
	public let container: WebviewContainerSharedInitialState
	public let editor: EditorInitialStatePayload

	public init(container: WebviewContainerSharedInitialState, editor: EditorInitialStatePayload) {
		self.container = container
		self.editor = editor
	}
}

public struct EditorChangeEvent: Codable {
	public let note_id: String
	/// The _unparsed_ content.
	public let content: String

	public init(note_id: String, content: String) {
		self.note_id = note_id
		self.content = content
	}
}

/// Basically a Partial<BibEntryModel> that's cross language, to be sent to the
/// editor.
public struct EditorCitation: Codable {
	public let citation_key: String
	public let html: String

	public init(citation_key: String, html: String) {
		self.citation_key = citation_key
		self.html = html
	}
}

public enum CodeEditorBaseKeymap: String, Codable {
	case `default`
	case vsCode
}

/// Basically a Partial<TagModel> that's cross language, to be sent to the
/// editor.
public struct EditorTag: Codable {
	public let body: String

	public init(body: String) {
		self.body = body
	}
}

public enum EditorView: String, Codable {
	case pending = "Pending"
	case splitview = "Splitview"
	case previewOnly = "PreviewOnly"
}

public struct EditorState: Codable {
	/// * Required for verification before saving manually as the async,
	/// back-forth approach with the AI parser
	/// might allow tme for things to change.
	/// This might resolve some DB issues that popped up
	/// during dev too... not sure if they're just dev tool things or real issues.
	public let note_id: String?
	public let baseKeymap: CodeEditorBaseKeymap
	public let citations: [EditorCitation]
	public let keymap: CodeEditorKeymap
	public let theme: CodeEditorTheme
	public let tags: [EditorTag]
	public let allCitationIds: [String]
	public let value: String
	public let parsedValue: String?
	public let haveSetInitialValue: Bool
	public let editorView: EditorView
	public let snippetProps: SnippetState
	public let lockEditorScrollToPreview: Bool
	public let saveMethod: EditorSaveMethod
	public let autoSaveTimeout: UInt32

	public init(note_id: String?, baseKeymap: CodeEditorBaseKeymap, citations: [EditorCitation], keymap: CodeEditorKeymap, theme: CodeEditorTheme, tags: [EditorTag], allCitationIds: [String], value: String, parsedValue: String?, haveSetInitialValue: Bool, editorView: EditorView, snippetProps: SnippetState, lockEditorScrollToPreview: Bool, saveMethod: EditorSaveMethod, autoSaveTimeout: UInt32) {
		self.note_id = note_id
		self.baseKeymap = baseKeymap
		self.citations = citations
		self.keymap = keymap
		self.theme = theme
		self.tags = tags
		self.allCitationIds = allCitationIds
		self.value = value
		self.parsedValue = parsedValue
		self.haveSetInitialValue = haveSetInitialValue
		self.editorView = editorView
		self.snippetProps = snippetProps
		self.lockEditorScrollToPreview = lockEditorScrollToPreview
		self.saveMethod = saveMethod
		self.autoSaveTimeout = autoSaveTimeout
	}
}

public struct ManualSaveRequestEvent: Codable {
	public let current_note_content: String
	/// note_id is required to verify the note before updating the note's data since there's so
	/// much async shit going on.
	public let note_id: String

	public init(current_note_content: String, note_id: String) {
		self.current_note_content = current_note_content
		self.note_id = note_id
	}
}

public enum EditorStateActions: String, Codable {
	case setEditorSaveMethod = "set-editor-save-method"
	case setInitialEditorState = "set-initial-editor-state"
	/// This is the 'onChange' method that's executed _after_ the content is parsed.
	case setParsedEditorContent = "set-parsed-editor-content"
	case setEditorKeymap = "set-initial-editor-keymap"
}

public struct SetEditorInitialStateEditorAction: Codable {
	public let type: EditorStateActions
	public let payload: EditorBasedWebviewInitialState

	public init(type: EditorStateActions, payload: EditorBasedWebviewInitialState) {
		self.type = type
		self.payload = payload
	}
}

public struct SetEditorKeymapPayload: Codable {
	public let keymap: CodeEditorKeymap

	public init(keymap: CodeEditorKeymap) {
		self.keymap = keymap
	}
}

public struct SetEditorKeymapAction: Codable {
	public let type: EditorStateActions
	public let payload: SetEditorKeymapPayload

	public init(type: EditorStateActions, payload: SetEditorKeymapPayload) {
		self.type = type
		self.payload = payload
	}
}

public struct SetEditorSaveMethodEditorAction: Codable {
	public let type: EditorStateActions
	public let payload: EditorSaveMethod

	public init(type: EditorStateActions, payload: EditorSaveMethod) {
		self.type = type
		self.payload = payload
	}
}

public struct SetEditorThemePayload: Codable {
	public let theme: CodeEditorTheme

	public init(theme: CodeEditorTheme) {
		self.theme = theme
	}
}

public struct SetEditorThemeAction: Codable {
	public let type: EditorStateActions
	public let payload: SetEditorThemePayload

	public init(type: EditorStateActions, payload: SetEditorThemePayload) {
		self.type = type
		self.payload = payload
	}
}

public struct SetParsedMdxContentEditorAction: Codable {
	public let type: EditorStateActions
	/// The serialized flatbuffer for the OnParsedContentChangeEventBuffer table.
	public let payload: [UInt8]

	public init(type: EditorStateActions, payload: [UInt8]) {
		self.type = type
		self.payload = payload
	}
}

public enum SizableOption: String, Codable {
	case none
	case small
	case smedium
	case medium
	case large
	case xl
	case xxl
	case fit
	case full
}

public struct WebviewContainerState: Codable {
	public let environment: WebviewEnvironment?
	public let size: SizableOption
	public let wasm_loaded: Bool
	public let dark_mode: Bool
	public let implementation: WebviewImplementation
	public let fluster_theme: FlusterTheme

	public init(environment: WebviewEnvironment?, size: SizableOption, wasm_loaded: Bool, dark_mode: Bool, implementation: WebviewImplementation, fluster_theme: FlusterTheme) {
		self.environment = environment
		self.size = size
		self.wasm_loaded = wasm_loaded
		self.dark_mode = dark_mode
		self.implementation = implementation
		self.fluster_theme = fluster_theme
	}
}

public enum AiNoteInteractionType: String, Codable {
	case generateSummary = "generate-summary"
}

public enum AutoInsertedComponentName: String, Codable {
	case noteLink = "NoteLink"
	case autoInsertedTag = "AutoInsertedTag"
	case flusterCitation = "FlusterCitation"
	case dictionaryEntry = "DictionaryEntry"
	case flusterAiParsePendingContainer = "FlusterAiParsePendingContainer"
}

public enum AutoTaggableType: String, Codable {
	case tag
	case topic
	case subject
}

/// Represents the date given some generated mdx benchmark content
/// as the content will need to grow as components are added.
public enum BenchmarkGeneratedDateString: String, Codable {
	case initial = "2_2_2026"
}

public enum BenchmarkMagnitude: String, Codable {
	case five = "Five"
	case ten = "Ten"
	case twenty = "Twenty"
	case fifty = "Fifty"
}

/// From typescript to swift.
public enum BibtexEditorWebviewActions: String, Codable {
	case requestBibtexEditorData = "request-bibtex-data"
	case setWebviewLoaded = "set-bibtex-webview-loaded"
	case onEditorChange = "on-bib-editor-change"
}

/// From swift to typescript
public enum BibtexEditorWebviewEvents: String, Codable {
	case setInitialColorScheme = "set-bib-initial-color-scheme"
	case setBibtexEditorContent = "set-bibtex-data"
	case setEditorKeymap = "set-bib-editor-keymap"
	case setCodeTheme = "set-bib-code-theme"
	case setCodeThemeLight = "set-bib-code-theme-light"
	case setCodeThemeDark = "set-bib-code-theme-dark"
}

public enum BibtexEditorWebviewLocalStorageKeys: String, Codable {
	case initialValue = "bibtex-editor-initial-value"
}

/// From typescript to swift.
public enum DictionaryWebviewActions: String, Codable {
	case requestDictionaryData = "request-dictionary-data"
	case setWebviewLoaded = "set-webview-loaded"
}

/// From swift to typescript
public enum DictionaryWebviewEvents: String, Codable {
	case setInitialColorScheme = "set-initial-color-scheme"
	case setDictionaryData = "set-dictionary-data"
	case setCodeTheme = "set-code-theme"
}

public enum DictionaryWebviewIds: String, Codable {
	case dictionaryContainer = "dictionary-container"
}

public enum DictionaryWebviewStorageKeys: String, Codable {
	case scrollPositionPortrait = "dict-scroll-pos-portrait"
	case scrollPositionLandscape = "dict-scroll-pos-landscape"
	case dictionaryData = "dict-data"
}

public enum DocumentationComponentName: String, Codable {
	case inContentDocumentationContainer = "InContentDocumentationContainer"
	case inContentDocsEmphasisTypeList = "InContentDocsEmphasisTypeList"
}

/// From typescript to swift.
public enum EmbeddableComponentId: String, Codable {
	case admonition
	case hl = "highlight"
	case ul = "underline"
	case card
	case grid
	case utlityContainer = "util-container"
	case hrWithChildren = "hr-with-children"
	case hint = "embeddable-hint-component"
}

public enum EmbeddableComponentName: String, Codable {
	case admonition = "Admonition"
	case hl = "Hl"
	case highlight = "Highlight"
	case ul = "Ul"
	case underline = "Underline"
	case card = "Card"
	case grid = "Grid"
	case utlityContainer = "Container"
	case hrWithChildren = "Hr"
	case hint = "Hint"
}

public enum InContentDocumentationFormat: String, Codable {
	case full
	case short
}

public enum InContentDocumentationId: String, Codable {
	case markdown = "Markdown"
	case docs = "Docs"
	case syntax = "Syntax"
	case jsx = "Jsx"
	case sizableObject = "Sizable"
	case emphasis = "Emphasis"
	case emoji = "Emoji"
	case components = "Components"
}

public enum InContentDocumentationSource: String, Codable {
	case componentDocs = "component"
	case internalDocs = "internal-docs"
}

/// From typescript to swift.
public enum MdxPreviewWebviewActions: String, Codable {
	case requestNoteData = "request-note-data"
	case setWebviewLoaded = "set-preview-webview-loaded"
	case viewNoteByUserDefinedId = "view-note-by-user-def-id"
	case viewNoteById = "view-note-by--id"
	case onTagClick = "tag-click-event"
	case onTopicClick = "handle-topic-click"
	case onSubjectClick = "handle-subject-click"
	case onCitationClick = "handle-citation-click"
	case showUserFacingNotification = "show-user-facing-notification"
}

/// From swift to typescript
public enum MdxPreviewWebviewEvents: String, Codable {
	case setInitialColorScheme = "set-initial-color-scheme"
	case setPreviewContent = "set-mdx-preview-content"
}

/// From typescript to swift.
public enum NoteDetailWebviewActions: String, Codable {
	case requestNoteDetailData = "request-note-detail-data"
	case setWebviewLoaded = "set-note-detail-webview-loaded"
	case onTagClick = "handle-tag-click"
	case onTopicClick = "handle-topic-click"
	case onSubjectClick = "handle-subject-click"
	case onCitationClick = "handle-citation-click"
}

/// From swift to typescript
public enum NoteDetailWebviewEvents: String, Codable {
	case setInitialColorScheme = "set-initial-color-scheme"
	case setNoteDetails = "set-note-details"
}

public enum ParserId: String, Codable {
	case tags
	case citations
	case dictionary
	case noteLink = "note_link"
	case documentation = "docs"
	case aiTrigger = "ai"
}

/// From typescript to swift.
public enum SharedWebviewActions: String, Codable {
	case javascriptError = "javascript-error"
}

/// Events
public enum SharedWebviewEvents: String, Codable {
	case localStorageWrite = "broadcast-local-storage"
}

public enum SplitviewEditorDomIds: String, Codable {
	case mdxPreview = "mdx-preview"
}

/// From typescript to swift.
public enum SplitviewEditorWebviewActions: String, Codable {
	case requestSplitviewEditorData = "request-editor-data"
	case requestParsedMdxContent = "request-parsed-mdx"
	case onEditorChange = "on-editor-change"
	case setWebviewLoaded = "set-editor-webview-loaded"
	case setIsLandscape = "set-is-landscape-view"
	case manualSaveRequest = "manual-save-req"
}

/// From swift to typescript
public enum SplitviewEditorWebviewEvents: String, Codable {
	case setInitialColorScheme = "set-initial-color-scheme"
	case setSplitviewEditorContent = "set-editor-content"
	case setParsedMdxContent = "set-parsed-mdx-content"
	case setParsedMdxContentString = "set-editor-content-str"
	case setEditorKeymap = "set-editor-keymap"
	case setEditorSnippetProps = "set-editor-snippet-props"
	case setCodeTheme = "set-code-theme"
	case setCodeThemeLight = "set-code-theme-light"
	case setCodeThemeDark = "set-code-theme-dark"
	case resetPreviewScrollPosition = "reset-mdx-preview-scroll-position"
	case emitMdxParsingError = "mdx-parsing-error"
	case emitMdxParsingSuccess = "mdx-parsing-success"
	case setWebviewPreviewScrollLock = "set-webview-preview-scroll-lock"
	case editorStateUpdate = "cross-lang-editor-update"
	case editorStateParsedContentUpdate = "editor-parsed-content-update"
}

public enum SplitviewEditorWebviewLocalStorageKeys: String, Codable {
	case initialValue = "editor-initial-value"
	case parsedMdxData = "parsed-mdx-data"
	case codeTheme = "editor-code-theme"
	case codeThemeDark = "editor-code-theme-dark"
	case codeThemeLight = "editor-code-theme-light"
	case editorKeymap = "editor-keymap"
	case scrollPositionPreviewOnly = "editor-scroll-pos-preview-only"
	case scrollPositionSplitview = "editor-scroll-pos-splitview"
	case editorState = "editor-state"
}
