/*
 Generated by typeshare 1.13.3
 */

import Foundation

public enum AutoInsertedComponentName: String, Codable {
	case noteLink = "NoteLink"
	case autoInsertedTag = "AutoInsertedTag"
	case flusterCitation = "FlusterCitation"
	case dictionaryEntry = "DictionaryEntry"
}

public enum AutoTaggableType: String, Codable {
	case tag
	case topic
	case subject
}

/// Represents the date given some generated mdx benchmark content
/// as the content will need to grow as components are added.
public enum BenchmarkGeneratedDateString: String, Codable {
	case initial = "2_2_2026"
}

public enum BenchmarkMagnitude: String, Codable {
	case five = "Five"
	case ten = "Ten"
	case twenty = "Twenty"
	case fifty = "Fifty"
}

/// From typescript to swift.
public enum BibtexEditorWebviewActions: String, Codable {
	case requestBibtexEditorData = "request-bibtex-data"
	case setWebviewLoaded = "set-bibtex-webview-loaded"
	case onEditorChange = "on-bib-editor-change"
}

/// From swift to typescript
public enum BibtexEditorWebviewEvents: String, Codable {
	case setInitialColorScheme = "set-bib-initial-color-scheme"
	case setBibtexEditorContent = "set-bibtex-data"
	case setEditorKeymap = "set-bib-editor-keymap"
	case setCodeTheme = "set-bib-code-theme"
	case setCodeThemeLight = "set-bib-code-theme-light"
	case setCodeThemeDark = "set-bib-code-theme-dark"
}

public enum BibtexEditorWebviewLocalStorageKeys: String, Codable {
	case initialValue = "bibtex-editor-initial-value"
}

/// From typescript to swift.
public enum DictionaryWebviewActions: String, Codable {
	case requestDictionaryData = "request-dictionary-data"
	case setWebviewLoaded = "set-webview-loaded"
}

/// From swift to typescript
public enum DictionaryWebviewEvents: String, Codable {
	case setInitialColorScheme = "set-initial-color-scheme"
	case setDictionaryData = "set-dictionary-data"
	case setCodeTheme = "set-code-theme"
}

public enum DictionaryWebviewIds: String, Codable {
	case dictionaryContainer = "dictionary-container"
}

public enum DictionaryWebviewStorageKeys: String, Codable {
	case scrollPositionPortrait = "dict-scroll-pos-portrait"
	case scrollPositionLandscape = "dict-scroll-pos-landscape"
	case dictionaryData = "dict-data"
}

public enum DocumentationComponentName: String, Codable {
	case inContentDocumentationContainer = "InContentDocumentationContainer"
	case inContentDocsEmphasisTypeList = "InContentDocsEmphasisTypeList"
}

/// From typescript to swift.
public enum EmbeddableComponentId: String, Codable {
	case admonition
	case hl = "highlight"
	case ul = "underline"
	case card
	case grid
	case utlityContainer = "util-container"
	case hrWithChildren = "hr-with-children"
	case hint = "embeddable-hint-component"
}

public enum EmbeddableComponentName: String, Codable {
	case admonition = "Admonition"
	case hl = "Hl"
	case highlight = "Highlight"
	case ul = "Ul"
	case underline = "Underline"
	case card = "Card"
	case grid = "Grid"
	case utlityContainer = "Container"
	case hrWithChildren = "Hr"
	case hint = "Hint"
}

public enum InContentDocumentationFormat: String, Codable {
	case full
	case short
}

public enum InContentDocumentationId: String, Codable {
	case markdown = "Markdown"
	case docs = "Docs"
	case syntax = "Syntax"
	case jsx = "Jsx"
	case sizableObject = "Sizable"
	case emphasis = "Emphasis"
	case emoji = "Emoji"
	case components = "Components"
}

public enum InContentDocumentationSource: String, Codable {
	case componentDocs = "component"
	case internalDocs = "internal-docs"
}

/// From typescript to swift.
public enum MdxPreviewWebviewActions: String, Codable {
	case requestNoteData = "request-note-data"
	case setWebviewLoaded = "set-preview-webview-loaded"
	case viewNoteByUserDefinedId = "view-note-by-user-def-id"
	case viewNoteById = "view-note-by--id"
	case onTagClick = "tag-click-event"
	case onTopicClick = "handle-topic-click"
	case onSubjectClick = "handle-subject-click"
	case onCitationClick = "handle-citation-click"
	case showUserFacingNotification = "show-user-facing-notification"
}

/// From swift to typescript
public enum MdxPreviewWebviewEvents: String, Codable {
	case setInitialColorScheme = "set-initial-color-scheme"
	case setPreviewContent = "set-mdx-preview-content"
}

/// From typescript to swift.
public enum NoteDetailWebviewActions: String, Codable {
	case requestNoteDetailData = "request-note-detail-data"
	case setWebviewLoaded = "set-note-detail-webview-loaded"
	case onTagClick = "handle-tag-click"
	case onTopicClick = "handle-topic-click"
	case onSubjectClick = "handle-subject-click"
	case onCitationClick = "handle-citation-click"
}

/// From swift to typescript
public enum NoteDetailWebviewEvents: String, Codable {
	case setInitialColorScheme = "set-initial-color-scheme"
	case setNoteDetails = "set-note-details"
}

/// From typescript to swift.
public enum SharedWebviewActions: String, Codable {
	case javascriptError = "javascript-error"
}

/// Events
public enum SharedWebviewEvents: String, Codable {
	case localStorageWrite = "broadcast-local-storage"
}

public enum SplitviewEditorDomIds: String, Codable {
	case mdxPreview = "mdx-preview"
}

/// From typescript to swift.
public enum SplitviewEditorWebviewActions: String, Codable {
	case requestSplitviewEditorData = "request-editor-data"
	case requestParsedMdxContent = "request-parsed-mdx"
	case onEditorChange = "on-editor-change"
	case setWebviewLoaded = "set-editor-webview-loaded"
	case setIsLandscape = "set-is-landscape-view"
}

/// From swift to typescript
public enum SplitviewEditorWebviewEvents: String, Codable {
	case setInitialColorScheme = "set-initial-color-scheme"
	case setSplitviewEditorContent = "set-editor-content"
	case setParsedMdxContent = "set-parsed-mdx-content"
	case setParsedMdxContentString = "set-editor-content-str"
	case setEditorKeymap = "set-editor-keymap"
	case setEditorSnippetProps = "set-editor-snippet-props"
	case setCodeTheme = "set-code-theme"
	case setCodeThemeLight = "set-code-theme-light"
	case setCodeThemeDark = "set-code-theme-dark"
	case resetPreviewScrollPosition = "reset-mdx-preview-scroll-position"
	case emitMdxParsingError = "mdx-parsing-error"
	case emitMdxParsingSuccess = "mdx-parsing-success"
	case setWebviewPreviewScrollLock = "set-webview-preview-scroll-lock"
}

public enum SplitviewEditorWebviewLocalStorageKeys: String, Codable {
	case initialValue = "editor-initial-value"
	case parsedMdxData = "parsed-mdx-data"
	case codeTheme = "editor-code-theme"
	case codeThemeDark = "editor-code-theme-dark"
	case codeThemeLight = "editor-code-theme-light"
	case editorKeymap = "editor-keymap"
	case scrollPositionPreviewOnly = "editor-scroll-pos-preview-only"
	case scrollPositionSplitview = "editor-scroll-pos-splitview"
}

/// From typescript to swift.
public enum WebviewEnvironment: String, Codable {
	case macOS = "fluster-mac"
	case iPad = "fluster-ipad"
	case multiPlatformDesktop = "fluster-multi-platform-desktop"
}
