/*
 Generated by typeshare 1.13.3
 */

import Foundation

public enum FoundationModelAccessStatus: String, Codable {
	case available
	case modelNotReady = "not-ready"
	case unknownStatus = "unknown-status"
	case deviceNotEligible = "device-not-elig"
	case appleIntelligenceNotEnabled = "ai-not-enabled"
}

public struct AiInitialStatePayload: Codable {
	public let foundation_model_access: FoundationModelAccessStatus

	public init(foundation_model_access: FoundationModelAccessStatus) {
		self.foundation_model_access = foundation_model_access
	}
}

public struct AiState: Codable {
	public let foundation_model_access: FoundationModelAccessStatus
	public let ai_thinking: Bool

	public init(foundation_model_access: FoundationModelAccessStatus, ai_thinking: Bool) {
		self.foundation_model_access = foundation_model_access
		self.ai_thinking = ai_thinking
	}
}

public enum EditorStateActions: String, Codable {
	case setEditorSaveMethod = "set-editor-save-method"
	case setInitialEditorState = "set-initial-editor-state"
	case setEditorValue = "set-editor-value"
	case setParsedEditorContent = "set-parsed-editor-content"
	case setEditorKeymap = "set-initial-editor-keymap"
	case setEditorThemeLight = "set-editor-theme-light"
	case setEditorThemeDark = "set-editor-theme-dark"
	case setAutoSaveTimeout = "set-autosave-timeout"
	case setBaseKeymap = "set-base-keymap"
	case setEditorTags = "set-editor-tags"
	case setAllCitationIds = "set-all-citation-ids"
	case setLockEditorScrollToPreview = "set-lock-editor-scroll-to-prev"
	case setSnippetProps = "set-snippet-props"
	case setEditingBibEntry = "set-editing-bib-entry"
}

public struct EditorBannerNotification: Codable {
	public let title: String
	public let id: String
	public let body: String?
	public let timeout: UInt32?

	public init(title: String, id: String, body: String?, timeout: UInt32?) {
		self.title = title
		self.id = id
		self.body = body
		self.timeout = timeout
	}
}

public struct AppendNotificationBannerPayload: Codable {
	public let notification: EditorBannerNotification

	public init(notification: EditorBannerNotification) {
		self.notification = notification
	}
}

public struct AppendNotificationBannerAction: Codable {
	public let type: EditorStateActions
	public let payload: AppendNotificationBannerPayload

	public init(type: EditorStateActions, payload: AppendNotificationBannerPayload) {
		self.type = type
		self.payload = payload
	}
}

public struct BibtexEditorState: Codable {
	public let value: String

	public init(value: String) {
		self.value = value
	}
}

public struct WebviewDictionaryEntry: Codable {
	public let label: String
	public let body: String
	public let origin_note_id: String?

	public init(label: String, body: String, origin_note_id: String?) {
		self.label = label
		self.body = body
		self.origin_note_id = origin_note_id
	}
}

public struct DictionaryState: Codable {
	public let entries: [WebviewDictionaryEntry]

	public init(entries: [WebviewDictionaryEntry]) {
		self.entries = entries
	}
}

public struct NoteTocHeadingRustMirror: Codable {
	public let content: String
	public let id: String
	public let depth: UInt8

	public init(content: String, id: String, depth: UInt8) {
		self.content = content
		self.id = id
		self.depth = depth
	}
}

public struct EchoNoteTocPayload: Codable {
	public let headings: [NoteTocHeadingRustMirror]

	public init(headings: [NoteTocHeadingRustMirror]) {
		self.headings = headings
	}
}

public struct EchoNoteTocEvent: Codable {
	public let type: EditorStateActions
	public let payload: EchoNoteTocPayload

	public init(type: EditorStateActions, payload: EchoNoteTocPayload) {
		self.type = type
		self.payload = payload
	}
}

/// From typescript to swift.
public enum WebviewEnvironment: String, Codable {
	case macOS = "fluster-mac"
	case iPad = "fluster-ipad"
	case multiPlatformDesktop = "fluster-multi-platform-desktop"
	case awaitingData = "awaiting-data"
}

public enum WebviewImplementation: String, Codable {
	case bibEditor = "bib-editor"
	case mdxEditor = "mdx-editor"
	case mdxViewer = "mdx-viewer"
	case dictionary
	case noteDetails = "note-details"
	case development
	case awaitingData = "pending"
}

public enum FlusterTheme: String, Codable, CaseIterable {
	case zinc
	case yellow
	case violet
	case fluster
	case stone
	case slate
	case rose
	case red
	case orange
	case neutral
	case green
	case gray
	case blue
}

public struct WebviewContainerSharedInitialState: Codable {
	public let environment: WebviewEnvironment
	public let dark_mode: Bool
	public let implementation: WebviewImplementation
	public let fluster_theme: FlusterTheme

	public init(environment: WebviewEnvironment, dark_mode: Bool, implementation: WebviewImplementation, fluster_theme: FlusterTheme) {
		self.environment = environment
		self.dark_mode = dark_mode
		self.implementation = implementation
		self.fluster_theme = fluster_theme
	}
}

public enum CodeEditorKeymap: String, Codable, CaseIterable {
	case vim
	case base
	case emacs
}

public enum CodeEditorTheme: String, Codable, CaseIterable {
	case materialLight
	case solarizedLight
	case solarizedDark
	case githubLight
	case aura
	case tokyoNightDay
	case xcodeLight
	case dracula
	case tokyoNight
	case materialDark
	case tokyoNightStorm
	case githubDark
	case xcodeDark
}

public struct SnippetState: Codable {
	public let includeEmojiSnippets: Bool

	public init(includeEmojiSnippets: Bool) {
		self.includeEmojiSnippets = includeEmojiSnippets
	}
}

public enum EditorSaveMethod: String, Codable {
	case onSave = "on-save"
	case onChange = "on-change"
}

public struct EditorInitialStatePayload: Codable {
	public let note_id: String
	public let keymap: CodeEditorKeymap
	public let theme_light: CodeEditorTheme
	public let theme_dark: CodeEditorTheme
	public let allCitationIds: [String]
	public let value: String
	public let parsedValue: String
	public let haveSetInitialValue: Bool
	public let snippetProps: SnippetState
	public let lockEditorScrollToPreview: Bool
	public let saveMethod: EditorSaveMethod

	public init(note_id: String, keymap: CodeEditorKeymap, theme_light: CodeEditorTheme, theme_dark: CodeEditorTheme, allCitationIds: [String], value: String, parsedValue: String, haveSetInitialValue: Bool, snippetProps: SnippetState, lockEditorScrollToPreview: Bool, saveMethod: EditorSaveMethod) {
		self.note_id = note_id
		self.keymap = keymap
		self.theme_light = theme_light
		self.theme_dark = theme_dark
		self.allCitationIds = allCitationIds
		self.value = value
		self.parsedValue = parsedValue
		self.haveSetInitialValue = haveSetInitialValue
		self.snippetProps = snippetProps
		self.lockEditorScrollToPreview = lockEditorScrollToPreview
		self.saveMethod = saveMethod
	}
}

public struct MathState: Codable {
	public let mathjax_font_url: String

	public init(mathjax_font_url: String) {
		self.mathjax_font_url = mathjax_font_url
	}
}

public struct EditorBasedWebviewInitialState: Codable {
	public let container: WebviewContainerSharedInitialState
	public let editor: EditorInitialStatePayload
	public let math: MathState
	public let ai: AiInitialStatePayload

	public init(container: WebviewContainerSharedInitialState, editor: EditorInitialStatePayload, math: MathState, ai: AiInitialStatePayload) {
		self.container = container
		self.editor = editor
		self.math = math
		self.ai = ai
	}
}

public struct EditorChangeEvent: Codable {
	public let note_id: String
	/// The _unparsed_ content.
	public let content: String

	public init(note_id: String, content: String) {
		self.note_id = note_id
		self.content = content
	}
}

/// Basically a Partial<BibEntryModel> that's cross language, to be sent to the
/// editor.
public struct EditorCitation: Codable {
	public let citation_key: String
	public let html: String
	public let url: String?

	public init(citation_key: String, html: String, url: String?) {
		self.citation_key = citation_key
		self.html = html
		self.url = url
	}
}

public enum EditorLogSeverity: String, Codable {
	case info = "Info"
	case warn = "Warn"
	case error = "Error"
	case fatal = "Fatal"
}

public struct EditorLog: Codable {
	public let msg: String
	public let severity: EditorLogSeverity

	public init(msg: String, severity: EditorLogSeverity) {
		self.msg = msg
		self.severity = severity
	}
}

public enum CodeEditorBaseKeymap: String, Codable {
	case `default`
	case vsCode
}

/// Basically a Partial<TagModel> that's cross language, to be sent to the
/// editor.
public struct EditorTag: Codable {
	public let body: String

	public init(body: String) {
		self.body = body
	}
}

public enum EditorView: String, Codable {
	case pending = "Pending"
	case splitview = "Splitview"
	case previewOnly = "PreviewOnly"
}

public struct EditorState: Codable {
	/// * Required for verification before saving manually as the async,
	/// back-forth approach with the AI parser
	/// might allow tme for things to change.
	/// This might resolve some DB issues that popped up
	/// during dev too... not sure if they're just dev tool things or real
	/// issues.
	public let note_id: String?
	public let baseKeymap: CodeEditorBaseKeymap
	public let citations: [EditorCitation]
	public let keymap: CodeEditorKeymap
	public let theme_light: CodeEditorTheme
	public let theme_dark: CodeEditorTheme
	public let tags: [EditorTag]
	public let allCitationIds: [String]
	public let value: String
	public let parsedValue: String?
	public let haveSetInitialValue: Bool
	public let editorView: EditorView
	public let snippetProps: SnippetState
	public let lockEditorScrollToPreview: Bool
	public let saveMethod: EditorSaveMethod
	public let autoSaveTimeout: UInt32
	public let bib_editor: BibtexEditorState

	public init(note_id: String?, baseKeymap: CodeEditorBaseKeymap, citations: [EditorCitation], keymap: CodeEditorKeymap, theme_light: CodeEditorTheme, theme_dark: CodeEditorTheme, tags: [EditorTag], allCitationIds: [String], value: String, parsedValue: String?, haveSetInitialValue: Bool, editorView: EditorView, snippetProps: SnippetState, lockEditorScrollToPreview: Bool, saveMethod: EditorSaveMethod, autoSaveTimeout: UInt32, bib_editor: BibtexEditorState) {
		self.note_id = note_id
		self.baseKeymap = baseKeymap
		self.citations = citations
		self.keymap = keymap
		self.theme_light = theme_light
		self.theme_dark = theme_dark
		self.tags = tags
		self.allCitationIds = allCitationIds
		self.value = value
		self.parsedValue = parsedValue
		self.haveSetInitialValue = haveSetInitialValue
		self.editorView = editorView
		self.snippetProps = snippetProps
		self.lockEditorScrollToPreview = lockEditorScrollToPreview
		self.saveMethod = saveMethod
		self.autoSaveTimeout = autoSaveTimeout
		self.bib_editor = bib_editor
	}
}

public enum UserSetLLM: String, Codable {
	/// The default model varies by use case.
	case `default` = "Default"
}

public struct GeneralAiRequestPhase2Event: Codable {
	/// The content of the request as a natural language string.
	public let user_request: String
	/// The full_match of the component that was passed into phase1. This is
	/// required to replace the content once the AI request succeeds.
	public let full_match: String
	/// Optionally let the user provide a model that is an enum of supported
	/// models.
	public let model: UserSetLLM

	public init(user_request: String, full_match: String, model: UserSetLLM) {
		self.user_request = user_request
		self.full_match = full_match
		self.model = model
	}
}

public struct GenerateNoteSummaryRequest: Codable {
	public let note_id: String

	public init(note_id: String) {
		self.note_id = note_id
	}
}

public enum SizableOption: String, Codable {
	case none
	case small
	case smedium
	case medium
	case large
	case xl
	case xxl
	case fit
	case full
}

public enum WebviewFontSize: String, Codable, CaseIterable {
	case small
	case base
	case large
	case xl
	case xxl
}

public struct WebviewContainerState: Codable {
	public let environment: WebviewEnvironment?
	public let size: SizableOption
	public let wasm_loaded: Bool
	public let dark_mode: Bool
	public let implementation: WebviewImplementation
	public let fluster_theme: FlusterTheme
	public let font_size: WebviewFontSize

	public init(environment: WebviewEnvironment?, size: SizableOption, wasm_loaded: Bool, dark_mode: Bool, implementation: WebviewImplementation, fluster_theme: FlusterTheme, font_size: WebviewFontSize) {
		self.environment = environment
		self.size = size
		self.wasm_loaded = wasm_loaded
		self.dark_mode = dark_mode
		self.implementation = implementation
		self.fluster_theme = fluster_theme
		self.font_size = font_size
	}
}

public struct NotificationState: Codable {
	public let logs: [EditorLog]
	public let banners: [EditorBannerNotification]

	public init(logs: [EditorLog], banners: [EditorBannerNotification]) {
		self.logs = logs
		self.banners = banners
	}
}

public struct ImageData: Codable {
	public let data: [UInt8]
	public let id: String

	public init(data: [UInt8], id: String) {
		self.data = data
		self.id = id
	}
}

public struct MediaState: Codable {
	/// A HashMap between an Id and an Object with the necessary image data.
	public let image_data: [String: ImageData]

	public init(image_data: [String: ImageData]) {
		self.image_data = image_data
	}
}

public enum SummaryGenerationMethod: String, Codable {
	case ai
	case aIManualTrigger = "ai-manual"
	case frontMatter = "frontmatter"
}

public struct SummaryState: Codable {
	public let content: String
	/// The javascript/unix timestamp in milliseconds.
	public let ctime: Float
	public let generation_method: SummaryGenerationMethod

	public init(content: String, ctime: Float, generation_method: SummaryGenerationMethod) {
		self.content = content
		self.ctime = ctime
		self.generation_method = generation_method
	}
}

public struct NoteDetailState: Codable {
	public let note_id: String
	public let title: String
	public let summary: SummaryState?
	public let topic: String?
	public let subject: String?
	public let tags: [EditorTag]
	public let citations: [EditorCitation]
	public let last_modified_string: String
	public let last_read_string: String

	public init(note_id: String, title: String, summary: SummaryState?, topic: String?, subject: String?, tags: [EditorTag], citations: [EditorCitation], last_modified_string: String, last_read_string: String) {
		self.note_id = note_id
		self.title = title
		self.summary = summary
		self.topic = topic
		self.subject = subject
		self.tags = tags
		self.citations = citations
		self.last_modified_string = last_modified_string
		self.last_read_string = last_read_string
	}
}

public struct GlobalWebviewState: Codable {
	public let container: WebviewContainerState
	public let editor: EditorState
	public let notifications: NotificationState
	public let ai: AiState
	public let media: MediaState
	public let note_details: NoteDetailState?
	public let dictionary: DictionaryState
	public let math: MathState

	public init(container: WebviewContainerState, editor: EditorState, notifications: NotificationState, ai: AiState, media: MediaState, note_details: NoteDetailState?, dictionary: DictionaryState, math: MathState) {
		self.container = container
		self.editor = editor
		self.notifications = notifications
		self.ai = ai
		self.media = media
		self.note_details = note_details
		self.dictionary = dictionary
		self.math = math
	}
}

public struct ManualSaveRequestEvent: Codable {
	public let current_note_content: String
	/// note_id is required to verify the note before updating the note's data since there's so
	/// much async shit going on.
	public let note_id: String

	public init(current_note_content: String, note_id: String) {
		self.current_note_content = current_note_content
		self.note_id = note_id
	}
}

public struct ReduxStateLoadedEvent: Codable {
	/// The currently focused note_id.
	public let note_id: String?

	public init(note_id: String?) {
		self.note_id = note_id
	}
}

public struct RemoveBannerNotificationByIdPayload: Codable {
	public let id: String

	public init(id: String) {
		self.id = id
	}
}

public struct RemoveBannerNotificationByIdAction: Codable {
	public let type: EditorStateActions
	public let payload: RemoveBannerNotificationByIdPayload

	public init(type: EditorStateActions, payload: RemoveBannerNotificationByIdPayload) {
		self.type = type
		self.payload = payload
	}
}

public enum AiAction: String, Codable {
	case setAiThinking = "set-ai-thinking"
	case setFoundationModelAvailability = "set-foundation-model-avail"
}

public struct SetAiThinkingPayload: Codable {
	public let ai_thinking: Bool

	public init(ai_thinking: Bool) {
		self.ai_thinking = ai_thinking
	}
}

public struct SetAiThinkingAction: Codable {
	public let type: AiAction
	public let payload: SetAiThinkingPayload

	public init(type: AiAction, payload: SetAiThinkingPayload) {
		self.type = type
		self.payload = payload
	}
}

public struct SetAllCitationIdsPayload: Codable {
	public let all_citation_ids: [String]

	public init(all_citation_ids: [String]) {
		self.all_citation_ids = all_citation_ids
	}
}

public struct SetAllCitationIdsAction: Codable {
	public let type: EditorStateActions
	public let payload: SetAllCitationIdsPayload

	public init(type: EditorStateActions, payload: SetAllCitationIdsPayload) {
		self.type = type
		self.payload = payload
	}
}

public struct SetAutoSaveTimeoutPayload: Codable {
	public let auto_save_timeout: UInt32

	public init(auto_save_timeout: UInt32) {
		self.auto_save_timeout = auto_save_timeout
	}
}

public struct SetAutoSaveTimeoutAction: Codable {
	public let type: EditorStateActions
	public let payload: SetAutoSaveTimeoutPayload

	public init(type: EditorStateActions, payload: SetAutoSaveTimeoutPayload) {
		self.type = type
		self.payload = payload
	}
}

public struct SetBaseKeymapPayload: Codable {
	public let base_keymap: CodeEditorBaseKeymap

	public init(base_keymap: CodeEditorBaseKeymap) {
		self.base_keymap = base_keymap
	}
}

public struct SetBaseKeymapAction: Codable {
	public let type: EditorStateActions
	public let payload: SetBaseKeymapPayload

	public init(type: EditorStateActions, payload: SetBaseKeymapPayload) {
		self.type = type
		self.payload = payload
	}
}

public enum WebviewContainerActions: String, Codable {
	case setFlusterTheme = "set-fluster-theme"
	case setDarkMode = "set-dark-mode"
	case handleNoteDeleted = "handle-note-deleted"
	case setWebviewFontSize = "set-webview-fontsize"
}

public struct SetDarkModePayload: Codable {
	public let dark_mode: Bool

	public init(dark_mode: Bool) {
		self.dark_mode = dark_mode
	}
}

public struct SetDarkModeAction: Codable {
	public let type: WebviewContainerActions
	public let payload: SetDarkModePayload

	public init(type: WebviewContainerActions, payload: SetDarkModePayload) {
		self.type = type
		self.payload = payload
	}
}

public enum DictionaryStateActions: String, Codable {
	case setDictionaryEntries = "set-note-details"
}

public struct SetDictionaryEntriesAction: Codable {
	public let type: DictionaryStateActions
	public let payload: DictionaryState

	public init(type: DictionaryStateActions, payload: DictionaryState) {
		self.type = type
		self.payload = payload
	}
}

public struct SetEditingBibEntryPayload: Codable {
	public let content: String

	public init(content: String) {
		self.content = content
	}
}

public struct SetEditingBibEntryAction: Codable {
	public let type: EditorStateActions
	public let payload: SetEditingBibEntryPayload

	public init(type: EditorStateActions, payload: SetEditingBibEntryPayload) {
		self.type = type
		self.payload = payload
	}
}

public struct SetEditorContentPayload: Codable {
	public let value: String

	public init(value: String) {
		self.value = value
	}
}

public struct SetEditorContentAction: Codable {
	public let type: EditorStateActions
	public let payload: SetEditorContentPayload

	public init(type: EditorStateActions, payload: SetEditorContentPayload) {
		self.type = type
		self.payload = payload
	}
}

public struct SetEditorInitialStateEditorAction: Codable {
	public let type: EditorStateActions
	public let payload: EditorBasedWebviewInitialState

	public init(type: EditorStateActions, payload: EditorBasedWebviewInitialState) {
		self.type = type
		self.payload = payload
	}
}

public struct SetEditorKeymapPayload: Codable {
	public let keymap: CodeEditorKeymap

	public init(keymap: CodeEditorKeymap) {
		self.keymap = keymap
	}
}

public struct SetEditorKeymapAction: Codable {
	public let type: EditorStateActions
	public let payload: SetEditorKeymapPayload

	public init(type: EditorStateActions, payload: SetEditorKeymapPayload) {
		self.type = type
		self.payload = payload
	}
}

public struct SetEditorSaveMethodEditorAction: Codable {
	public let type: EditorStateActions
	public let payload: EditorSaveMethod

	public init(type: EditorStateActions, payload: EditorSaveMethod) {
		self.type = type
		self.payload = payload
	}
}

public struct SetEditorTagsPayload: Codable {
	public let tags: [EditorTag]

	public init(tags: [EditorTag]) {
		self.tags = tags
	}
}

public struct SetEditorTagsAction: Codable {
	public let type: EditorStateActions
	public let payload: SetEditorTagsPayload

	public init(type: EditorStateActions, payload: SetEditorTagsPayload) {
		self.type = type
		self.payload = payload
	}
}

public struct SetEditorThemeDarkPayload: Codable {
	public let theme_dark: CodeEditorTheme

	public init(theme_dark: CodeEditorTheme) {
		self.theme_dark = theme_dark
	}
}

public struct SetEditorThemeDarkAction: Codable {
	public let type: EditorStateActions
	public let payload: SetEditorThemeDarkPayload

	public init(type: EditorStateActions, payload: SetEditorThemeDarkPayload) {
		self.type = type
		self.payload = payload
	}
}

public struct SetEditorThemeLightPayload: Codable {
	public let theme_light: CodeEditorTheme

	public init(theme_light: CodeEditorTheme) {
		self.theme_light = theme_light
	}
}

public struct SetEditorThemeLightAction: Codable {
	public let type: EditorStateActions
	public let payload: SetEditorThemeLightPayload

	public init(type: EditorStateActions, payload: SetEditorThemeLightPayload) {
		self.type = type
		self.payload = payload
	}
}

public struct SetFlusterThemePayload: Codable {
	public let fluster_theme: FlusterTheme

	public init(fluster_theme: FlusterTheme) {
		self.fluster_theme = fluster_theme
	}
}

public struct SetFlusterThemeAction: Codable {
	public let type: WebviewContainerActions
	public let payload: SetFlusterThemePayload

	public init(type: WebviewContainerActions, payload: SetFlusterThemePayload) {
		self.type = type
		self.payload = payload
	}
}

public struct SetFoundationModelAvailabilityPayload: Codable {
	public let foundation_model_availability: FoundationModelAccessStatus

	public init(foundation_model_availability: FoundationModelAccessStatus) {
		self.foundation_model_availability = foundation_model_availability
	}
}

public struct SetFoundationModelAvailabilityAction: Codable {
	public let type: AiAction
	public let payload: SetFoundationModelAvailabilityPayload

	public init(type: AiAction, payload: SetFoundationModelAvailabilityPayload) {
		self.type = type
		self.payload = payload
	}
}

public struct SetLockEditorScrollToPreviewPayload: Codable {
	public let lock_editor_scroll_to_preview: Bool

	public init(lock_editor_scroll_to_preview: Bool) {
		self.lock_editor_scroll_to_preview = lock_editor_scroll_to_preview
	}
}

public struct SetLockEditorScrollToPreviewAction: Codable {
	public let type: EditorStateActions
	public let payload: SetLockEditorScrollToPreviewPayload

	public init(type: EditorStateActions, payload: SetLockEditorScrollToPreviewPayload) {
		self.type = type
		self.payload = payload
	}
}

public struct SetMathjaxFontUrlPayload: Codable {
	public let mathjax_font_url: String

	public init(mathjax_font_url: String) {
		self.mathjax_font_url = mathjax_font_url
	}
}

public struct SetMathjaxFontUrlAction: Codable {
	public let type: AiAction
	public let payload: SetMathjaxFontUrlPayload

	public init(type: AiAction, payload: SetMathjaxFontUrlPayload) {
		self.type = type
		self.payload = payload
	}
}

public struct SetNoteDeletedPayload: Codable {
	/// The id of the note the was deleted to be used for resetting state on the Typescript
	/// side if the note id matches the current state.
	public let note_id: String

	public init(note_id: String) {
		self.note_id = note_id
	}
}

public struct SetNoteDeletedAction: Codable {
	public let type: WebviewContainerActions
	public let payload: SetNoteDeletedPayload

	public init(type: WebviewContainerActions, payload: SetNoteDeletedPayload) {
		self.type = type
		self.payload = payload
	}
}

public enum NoteDetailActions: String, Codable {
	case setNoteDetails = "set-note-details"
	case invalidateNoteDetails = "invalidate-note-details"
	case setNoteSummary = "set-note-summary"
}

public struct SetNoteDetailsAction: Codable {
	public let type: NoteDetailActions
	public let payload: NoteDetailState?

	public init(type: NoteDetailActions, payload: NoteDetailState?) {
		self.type = type
		self.payload = payload
	}
}

public struct SetNoteSummaryAction: Codable {
	public let type: NoteDetailActions
	public let payload: SummaryState

	public init(type: NoteDetailActions, payload: SummaryState) {
		self.type = type
		self.payload = payload
	}
}

public struct SetParsedMdxContentEditorAction: Codable {
	public let type: EditorStateActions
	/// The serialized flatbuffer for the OnParsedContentChangeEventBuffer table.
	public let payload: [UInt8]

	public init(type: EditorStateActions, payload: [UInt8]) {
		self.type = type
		self.payload = payload
	}
}

public struct SetParsedValuePayload: Codable {
	public let value: String

	public init(value: String) {
		self.value = value
	}
}

public struct SetParsedValueAction: Codable {
	public let type: EditorStateActions
	public let payload: SetParsedValuePayload

	public init(type: EditorStateActions, payload: SetParsedValuePayload) {
		self.type = type
		self.payload = payload
	}
}

public struct SetSnippetPropsPayload: Codable {
	public let snippetProps: SnippetState

	public init(snippetProps: SnippetState) {
		self.snippetProps = snippetProps
	}
}

public struct SetSnippetPropsAction: Codable {
	public let type: EditorStateActions
	public let payload: SetSnippetPropsPayload

	public init(type: EditorStateActions, payload: SetSnippetPropsPayload) {
		self.type = type
		self.payload = payload
	}
}

public struct SetWebviewFontSizePayload: Codable {
	/// The id of the note the was deleted to be used for resetting state on the Typescript
	/// side if the note id matches the current state.
	public let font_size: WebviewFontSize

	public init(font_size: WebviewFontSize) {
		self.font_size = font_size
	}
}

public struct SetWebviewFontSizeAction: Codable {
	public let type: WebviewContainerActions
	public let payload: SetWebviewFontSizePayload

	public init(type: WebviewContainerActions, payload: SetWebviewFontSizePayload) {
		self.type = type
		self.payload = payload
	}
}

public enum AiStateEvents: String, Codable {
	case sendGeneralAiRequestPhase2 = "send-general-ai-request-phase-2"
}

public enum AutoInsertedComponentName: String, Codable {
	case noteLink = "NoteLink"
	case autoInsertedTag = "AutoInsertedTag"
	case flusterCitation = "FlusterCitation"
	case dictionaryEntry = "DictionaryEntry"
	case flusterAiParsePendingContainer = "FlusterAiParsePendingContainer"
	case autoInsertedHeading = "AutoInsertedHeading"
	case autoInsertedBlockQuote = "AutoInsertedBlockQuote"
	case autoInsertedBlockMath = "AutoInsertedBlockMath"
	case autoInsertedInlineMath = "AutoInsertedInlineMath"
	case autoInsertedMarkdownLink = "AutoInsertedMarkdownLink"
	case autoInsertedMarkdownParagraph = "AutoInsertedMarkdownParagraph"
}

public enum AutoTaggableType: String, Codable {
	case tag
	case topic
	case subject
}

/// Represents the date given some generated mdx benchmark content
/// as the content will need to grow as components are added.
public enum BenchmarkGeneratedDateString: String, Codable {
	case initial = "2_2_2026"
	case firstWithAllSyntaxes = "2_16_2026"
}

public enum BenchmarkMagnitude: String, Codable {
	case five = "Five"
	case ten = "Ten"
	case twenty = "Twenty"
	case fifty = "Fifty"
}

/// From typescript to swift.
public enum BibtexEditorWebviewActions: String, Codable {
	case requestBibtexEditorData = "request-bibtex-data"
	case setWebviewLoaded = "set-bibtex-webview-loaded"
	case onEditorChange = "on-bib-editor-change"
}

/// From swift to typescript
public enum BibtexEditorWebviewEvents: String, Codable {
	case setInitialColorScheme = "set-bib-initial-color-scheme"
	case setBibtexEditorContent = "set-bibtex-data"
	case setEditorKeymap = "set-bib-editor-keymap"
	case setCodeTheme = "set-bib-code-theme"
	case setCodeThemeLight = "set-bib-code-theme-light"
	case setCodeThemeDark = "set-bib-code-theme-dark"
}

public enum BibtexEditorWebviewLocalStorageKeys: String, Codable {
	case initialValue = "bibtex-editor-initial-value"
}

/// From typescript to swift.
public enum DictionaryWebviewActions: String, Codable {
	case requestDictionaryData = "request-dictionary-data"
	case setWebviewLoaded = "set-webview-loaded"
}

/// From swift to typescript
public enum DictionaryWebviewEvents: String, Codable {
	case setInitialColorScheme = "set-initial-color-scheme"
	case setDictionaryData = "set-dictionary-data"
	case setCodeTheme = "set-code-theme"
}

public enum DictionaryWebviewIds: String, Codable {
	case dictionaryContainer = "dictionary-container"
}

public enum DictionaryWebviewStorageKeys: String, Codable {
	case scrollPositionPortrait = "dict-scroll-pos-portrait"
	case scrollPositionLandscape = "dict-scroll-pos-landscape"
	case dictionaryData = "dict-data"
}

public enum DocumentationComponentName: String, Codable {
	case inContentDocumentationContainer = "InContentDocumentationContainer"
	case inContentDocsEmphasisTypeList = "InContentDocsEmphasisTypeList"
	case inContentDocsHighlightDemo = "InContentDocsHighlightDemo"
	case inContentDocsUnderlineDemo = "InContentDocsUnderlineDemo"
}

/// From typescript to swift.
public enum EmbeddableComponentId: String, Codable {
	case admonition
	case hl = "highlight"
	case ul = "underline"
	case card
	case grid
	case utlityContainer = "util-container"
	case hrWithChildren = "hr-with-children"
	case hint = "embeddable-hint-component"
	case aINoteSummary = "ai-note-summary"
	case aIResearchSuggestions = "ai-research-suggestions"
	case aIGeneratedImage = "ai-generated-image"
}

public enum EmbeddableComponentName: String, Codable {
	case admonition = "Admonition"
	case hl = "Hl"
	case highlight = "Highlight"
	case ul = "Ul"
	case underline = "Underline"
	case card = "Card"
	case grid = "Grid"
	case utlityContainer = "Container"
	case hrWithChildren = "Hr"
	case hint = "Hint"
	case aINoteSummary = "AINoteSummary"
}

public enum InContentDocumentationFormat: String, Codable {
	case full
	case short
}

public enum InContentDocumentationId: String, Codable {
	case markdown = "Markdown"
	case docs = "Docs"
	case syntax = "Syntax"
	case jsx = "Jsx"
	case sizableObject = "Sizable"
	case emphasis = "Emphasis"
	case emoji = "Emoji"
	case components = "Components"
	case ai = "AI"
}

public enum InContentDocumentationSource: String, Codable {
	case componentDocs = "component"
	case internalDocs = "internal-docs"
}

/// From typescript to swift.
public enum MdxPreviewWebviewActions: String, Codable {
	case requestNoteData = "request-note-data"
	case setWebviewLoaded = "set-preview-webview-loaded"
	case viewNoteByUserDefinedId = "view-note-by-user-def-id"
	case viewNoteById = "view-note-by--id"
	case onTagClick = "tag-click-event"
	case onTopicClick = "handle-topic-click"
	case onSubjectClick = "handle-subject-click"
	case onCitationClick = "handle-citation-click"
	case showUserFacingNotification = "show-user-facing-notification"
}

/// From swift to typescript
public enum MdxPreviewWebviewEvents: String, Codable {
	case setInitialColorScheme = "set-initial-color-scheme"
	case setPreviewContent = "set-mdx-preview-content"
}

public enum NoteDetailEvents: String, Codable {
	/// Ask the AI to generate a summary of the currently focused note.
	case sendGenerateSummaryRequest = "send-gen-summary-req"
}

/// From typescript to swift.
public enum NoteDetailWebviewActions: String, Codable {
	case requestNoteDetailData = "request-note-detail-data"
	case setWebviewLoaded = "set-note-detail-webview-loaded"
	case onTagClick = "handle-tag-click"
	case onTopicClick = "handle-topic-click"
	case onSubjectClick = "handle-subject-click"
	case onCitationClick = "handle-citation-click"
}

/// From swift to typescript
public enum NoteDetailWebviewEvents: String, Codable {
	case setInitialColorScheme = "set-initial-color-scheme"
	case setNoteDetails = "set-note-details"
}

public enum ParserId: String, Codable {
	case tags
	case citations
	case dictionary
	case noteLink = "note_link"
	case documentation = "docs"
	case aiTrigger = "ai"
	case hrWithChildren = "hr"
}

/// From typescript to swift.
public enum SharedWebviewActions: String, Codable {
	case javascriptError = "javascript-error"
}

/// Events
public enum SharedWebviewEvents: String, Codable {
	case localStorageWrite = "broadcast-local-storage"
}

public enum SnippetCategoryId: String, Codable {
	case icons
	case math
	case components
	case componentVariants
	case emojis
}

public enum SplitviewEditorDomIds: String, Codable {
	case mdxPreview = "mdx-preview"
}

/// From typescript to swift.
public enum SplitviewEditorWebviewActions: String, Codable {
	case requestSplitviewEditorData = "request-editor-data"
	case requestParsedMdxContent = "request-parsed-mdx"
	case onEditorChange = "on-editor-change"
	case setWebviewLoaded = "set-editor-webview-loaded"
	case setIsLandscape = "set-is-landscape-view"
	case manualSaveRequest = "manual-save-req"
	case onBibEditorChange = "on-bib-editor-change"
}

/// From swift to typescript
public enum SplitviewEditorWebviewEvents: String, Codable {
	case setInitialColorScheme = "set-initial-color-scheme"
	case setSplitviewEditorContent = "set-editor-content"
	case setParsedMdxContent = "set-parsed-mdx-content"
	case setParsedMdxContentString = "set-editor-content-str"
	case setEditorKeymap = "set-editor-keymap"
	case setEditorSnippetProps = "set-editor-snippet-props"
	case setCodeTheme = "set-code-theme"
	case setCodeThemeLight = "set-code-theme-light"
	case setCodeThemeDark = "set-code-theme-dark"
	case resetPreviewScrollPosition = "reset-mdx-preview-scroll-position"
	case emitMdxParsingError = "mdx-parsing-error"
	case emitMdxParsingSuccess = "mdx-parsing-success"
	case setWebviewPreviewScrollLock = "set-webview-preview-scroll-lock"
	case editorStateUpdate = "cross-lang-editor-update"
	case editorStateParsedContentUpdate = "editor-parsed-content-update"
	case errorStateReset = "error-state-reset"
}

public enum SplitviewEditorWebviewLocalStorageKeys: String, Codable {
	case initialValue = "editor-initial-value"
	case parsedMdxData = "parsed-mdx-data"
	case codeTheme = "editor-code-theme"
	case codeThemeDark = "editor-code-theme-dark"
	case codeThemeLight = "editor-code-theme-light"
	case editorKeymap = "editor-keymap"
	case scrollPositionPreviewOnly = "editor-scroll-pos-preview-only"
	case scrollPositionSplitview = "editor-scroll-pos-splitview"
	case editorState = "editor-state"
}

public enum WebviewContainerEvents: String, Codable {
	case reduxStateLoaded = "redux-state-loaded"
}
