// THIS FILE IS AUTOMATICALLY GENERATED AS PART OF THE DOCGEN SCRIPT. CHANGES MADE HERE WILL BE LOST.

export const mcpToolNames = [ 
   "hello_world", 
   "query_workspaces", ] as const;




export const aiPrimaryTasks = [ 
   "general-chat", 
   "note-creation", 
   "note-summarization", 
   "flash-card-creation", 
   "fact-verification", 
   "bibliography-extraction", 
   "vector-generation-from-text", ] as const;