export enum AppPaths {
    dashboard = "/",
    onboarding = "/onboarding",
    aiChat = "/ai-chat",
    settings = "/settings",
    workspaces = "/workspaces",
    singleWorkspaceManagement = "/workspaces/manage",
    singleWorkspaceView = "/workspaces/view",
    flashcards = "/flashcards",
    flashcardsQuiz = "/flashcards/quiz",
    aiGenerateFlashcard = "/flashcards/ai-generate",
    database = "/database",
    search = "/search",
    viewConundrum = "/conundrum",
    health = "/health",
}
