// This file was generated by [rspc](https://github.com/specta-rs/rspc). Do not edit this file manually.

export type Procedures = {
	fs: {
	path_exists: { kind: "query", input: string, output: boolean, error: unknown },
},
	version: { kind: "query", input: null, output: { database: SchemaVersion; server: ServerVersion }, error: unknown },
}
//# sourceMappingURL=bindings_t.d.ts.map