// This file was generated by [rspc](https://github.com/specta-rs/rspc). Do not edit this file manually.

export type Procedures = {
	code: {
	highlight_code: { kind: "mutation", input: { code: string; lang: SupportedCodeBlockSyntax; theme: SupportedCodeBlockTheme; inline: boolean }, output: string, error: unknown },
},
	fs: {
	path_exists: { kind: "query", input: string, output: boolean, error: unknown },
},
	user_workspace_crud: {
	delete_by_predicate: { kind: "mutation", input: string, output: null, error: unknown },
	get_by_predicate: { kind: "query", input: { predicate: string | null; pagination: PaginationParams | null }, output: ({ root: string; label: string | null; respect_gitignore: boolean; ignore_hidden: boolean; bib_paths?: string[]; resource_dir?: string })[], error: unknown },
	save_many: { kind: "mutation", input: ({ root: string; label: string | null; respect_gitignore: boolean; ignore_hidden: boolean; bib_paths?: string[]; resource_dir?: string })[], output: null, error: unknown },
	update_many: { kind: "mutation", input: ({ root: string; label: string | null; bib_paths: string[] | null; respect_gitignore: boolean | null; ignore_hidden: boolean | null; resource_dir: string | null })[], output: null, error: unknown },
},
	version: { kind: "query", input: null, output: { database: SchemaVersion; server: ServerVersion }, error: unknown },
	workspace: {
	get_workspace_count: { kind: "query", input: string, output: { workspace: UserWorkspace; count: Partial<{ [key in ParsableFileType]: number }>; bib_path_exists: Partial<{ [key in string]: boolean }> }, error: unknown },
},
}
//# sourceMappingURL=bindings_t.d.ts.map