[package]
edition.workspace = true
name = "fluster_wasm"
publish = false
version.workspace = true

[lib]
crate-type = ["cdylib"]

[lints]
workspace = true

[dependencies]
wasm-bindgen = "0.2.114"


[package.metadata.wasm-pack.profile.release]
wasm-opt = ["-O4", "--enable-bulk-memory"]
