// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class GetSnippetPropsBuffer {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):GetSnippetPropsBuffer {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsGetSnippetPropsBuffer(bb:flatbuffers.ByteBuffer, obj?:GetSnippetPropsBuffer):GetSnippetPropsBuffer {
  return (obj || new GetSnippetPropsBuffer()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsGetSnippetPropsBuffer(bb:flatbuffers.ByteBuffer, obj?:GetSnippetPropsBuffer):GetSnippetPropsBuffer {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new GetSnippetPropsBuffer()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

citationIds(index: number):string
citationIds(index: number,optionalEncoding:flatbuffers.Encoding):string|Uint8Array
citationIds(index: number,optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb!.__vector(this.bb_pos + offset) + index * 4, optionalEncoding) : null;
}

citationIdsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startGetSnippetPropsBuffer(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addCitationIds(builder:flatbuffers.Builder, citationIdsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, citationIdsOffset, 0);
}

static createCitationIdsVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startCitationIdsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endGetSnippetPropsBuffer(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  builder.requiredField(offset, 4) // citationIds
  return offset;
}

static createGetSnippetPropsBuffer(builder:flatbuffers.Builder, citationIdsOffset:flatbuffers.Offset):flatbuffers.Offset {
  GetSnippetPropsBuffer.startGetSnippetPropsBuffer(builder);
  GetSnippetPropsBuffer.addCitationIds(builder, citationIdsOffset);
  return GetSnippetPropsBuffer.endGetSnippetPropsBuffer(builder);
}
}
