export type ConundrumInt = number;
/*
 Generated by typeshare 1.13.3
*/


export type ParsedElement = 
	| { tag: "Heading", content: MarkdownHeadingResult }
	| { tag: "BlockQuote", content: BlockQuoteResult }
	| { tag: "BlockMath", content: BlockMathResult }
	| { tag: "InlineMath", content: InlineMathResult }
	| { tag: "Text", content: string }
	| { tag: "BoldText", content: MarkdownBoldTextResult }
	| { tag: "ItalicText", content: MarkdownItalicTextResult }
	| { tag: "BoldAndItalicText", content: MarkdownBoldAndItalicTextResult }
	| { tag: "ParsedCodeBlock", content: ParsedCodeBlock }
	| { tag: "InlineCode", content: InlineCodeResult }
	| { tag: "MarkdownLink", content: MarkdownLinkResult }
	| { tag: "MarkdownParagraph", content: MarkdownParagraphResult }
	| { tag: "Emoji", content: EmojiResult }
	| { tag: "ReactComponentSelfClosing", content: ReactComponentSelfClosingResult }
	| { tag: "ReactComponentWithChildren", content: ReactComponentWithChildrenResult }
	| { tag: "ParsedCitation", content: ParsedCitation }
	| { tag: "ParsedOutgoingNoteLink", content: ParsedOutgoingNoteLink }
	| { tag: "Tag", content: ParsedTag }
	| { tag: "ParsedInspectionRequest", content: ParsedInspectionRequest }
	| { tag: "HrWithChildren", content: HrWithChildrenResult }
	| { tag: "Comment", content: ConundrumCommentResult }
	| { tag: "Children", content: Children }
	| { tag: "Javascript", content: ParsedJavascriptElement }
	| { tag: "Logic", content: ConundrumLogicToken };

/**
 * The representation of 'children', usually other markdown content. Unlike
 * other UI frameworks like React, `children` does not necessarily refer only
 * to the components that go within the main `children` property, but rather
 * any Conundrum content that is rendered inside of any of it's slots. A
 * `title`, a `subtitle` or a `label` might all be represented as children
 * since they accept Conundrum content and are represented in the UI, while
 * something like a `columns` property obviously is not.
 */
export type Children = ParsedElement[];

export type ConundrumBoolean = boolean;

export type ConundrumFloat = number;

export type ConundrumString = string;

/**
 * A simple utility around the heading depth, 1-6 just to add some convenience
 * methods.
 */
export type HeadingDepth = ConundrumInt;

/**
 * A set of common styles that can be applied as a group to indicate common
 * scenarios. These will become customizable soon so you won't be limited to
 * the default color values.
 * The emphasis documentation can be viewed via the `Emphasis??` command.
 */
export enum Emphasis {
	Info = "info",
	Error = "error",
	Warn = "warn",
	Success = "success",
	Primary = "primary",
	Important = "important",
	Research = "research",
	Highlight = "highlight",
	Card = "card",
}

export enum SizableOption {
	None = "none",
	Small = "small",
	Smedium = "smedium",
	Medium = "medium",
	Large = "large",
	Xl = "xl",
	Xxl = "xxl",
	Fit = "fit",
	Full = "full",
}

/**
 * This is applicable to pretty much any component where changing it's size
 * makes sense. Not so much text, where you're changing the content of the text
 * itself, but rather containers, where the size is changing irrespective of
 * the content inside of it.
 * This shouldn't be confused though, since this struct contains a **lot** more
 * properties than just those that can modify _size._ You can also modify
 * color, padding, margin, borders, and more.
 */
export interface SizablePropsGroup {
	/** Hides the MathJax labels in all child components. */
	hide_math_labels?: ConundrumBoolean;
	/**
	 * 'Floats' the component to the right. This is often combined with `width`
	 * or the `sidebar` property to create sidebar layouts.
	 */
	right?: ConundrumBoolean;
	/**
	 * 'Floats' the component to the left. This is often combined with `width`
	 * or the `sidebar` property to create sidebar layouts.
	 */
	left?: ConundrumBoolean;
	/**
	 * A utility property that sets a responsive max-width to create sidebar
	 * like layouts on large screens while allowing for full-width when the
	 * window is smaller.
	 */
	sidebar?: ConundrumBoolean;
	center_self?: ConundrumBoolean;
	/**
	 * Centers the content of this component's children, not the component
	 * itself.    pub center_self: Option<ConundrumBoolean>,
	 */
	center_content?: ConundrumBoolean;
	/** Add a small, muted border to the object. */
	border?: ConundrumBoolean;
	/**
	 * Tells the container to not forcefully create a new line and instead to
	 * flow with the rest of the content. Unless you're trying to apply
	 * properties to text inside of a paragraph using the Container component
	 * this is most likely not what you are looking for. If you want text to
	 * wrap around an element, use the `right` or `left` properties paired with
	 * a desired `width`.
	 */
	inline?: ConundrumBoolean;
	/** Casts an inset shadow from the object. */
	in_shadow?: SizableOption;
	/** Casts a shadow from the object. */
	shadow?: SizableOption;
	/** Rounds the corners of the container. Use `rounded=\ */
	rounded?: SizableOption;
	/**
	 * Change the text content of the container's children. Beware though, some
	 * edge cases might not respond as expected.
	 */
	text?: SizableOption;
	/** Set some custom width properties to create responsive layouts. */
	width?: SizableOption;
	/** Set some custom height properties to create responsive layouts. */
	height?: SizableOption;
	/**
	 * Add some padding around the **outside** of an object. If you are looking
	 * to create space on the _inside_ of an object you are looking for
	 * `padding`.
	 */
	margin?: SizableOption;
	margin_left?: SizableOption;
	margin_right?: SizableOption;
	margin_top?: SizableOption;
	margin_bottom?: SizableOption;
	margin_y?: SizableOption;
	margin_x?: SizableOption;
	/**
	 * Create padding on the _inside_ of an object. If you are trying to create
	 * space _around_ an object. you are probably looking for `margin`.
	 */
	padding?: SizableOption;
	padding_left?: SizableOption;
	padding_right?: SizableOption;
	padding_top?: SizableOption;
	padding_bottom?: SizableOption;
	padding_y?: SizableOption;
	padding_x?: SizableOption;
	/**
	 * When in Grid mode or in some other select layouts, this property create
	 * a gap between _all_ children.
	 */
	gap?: SizableOption;
	gap_y?: SizableOption;
	gap_x?: SizableOption;
}

export interface Admonition {
	title: ConundrumString;
	children: Children;
	/**
	 * The title depth between 1-6 for the markdown output. This will have no
	 * effect on mdx, jsx, or plain text output. Defaults to 5
	 * ```rust
	 * let admonition = Admonition {
	 * title: vec![],
	 * children: vec![],
	 * markdown_title_depth: None
	 * }
	 * assert_eq!(admonition.markdown_title_depth, Some(5));
	 * ```
	 */
	markdown_title_depth?: HeadingDepth;
	emphasis?: Emphasis;
	sizable?: SizablePropsGroup;
	/** Set to true to make the admonition foldable. Default: `false` */
	foldable?: ConundrumBoolean;
	/**
	 * If the admonition is `foldable`, `folded` can make the admonition folded
	 * by default. If the `foldable` property is false, this property does
	 * nothing.
	 */
	folded?: ConundrumBoolean;
}

/** All keys must be cast to lowercase and all `_` replaced with `-`. */
export enum SupportedCodeBlockSyntax {
	PlainText = "Plain Text",
	ASP = "ASP",
	HTML_ASP = "HTML (ASP)",
	ActionScript = "ActionScript",
	AppleScript = "AppleScript",
	BatchFile = "Batch File",
	NAntBuildFile = "NAnt Build File",
	CSharp = "C#",
	Cpp = "C++",
	C = "C",
	CSS = "CSS",
	Clojure = "Clojure",
	D = "D",
	Diff = "Diff",
	Erlang = "Erlang",
	HTML_Erlang = "HTML (Erlang)",
	Go = "Go",
	GraphvizDOT = "Graphviz (DOT)",
	Groovy = "Groovy",
	HTML = "HTML",
	Haskell = "Haskell",
	LiterateHaskell = "Literate Haskell",
	JavaServerPage = "Java Server Page (JSP)",
	Java = "Java",
	JavaDoc = "JavaDoc",
	JavaProperties = "Java Properties",
	JSON = "JSON",
	JavaScript = "JavaScript",
	RegularExpressionsJavascript = "Regular Expressions (Javascript)",
	BibTeX = "BibTeX",
	LaTeXLog = "LaTeX Log",
	LaTeX = "LaTeX",
	TeX = "TeX",
	Lisp = "Lisp",
	Lua = "Lua",
	MakeOutput = "Make Output",
	Makefile = "Makefile",
	Markdown = "Markdown",
	MultiMarkdown = "MultiMarkdown",
	MATLAB = "MATLAB",
	OCaml = "OCaml",
	OCamllex = "OCamllex",
	OCamlyacc = "OCamlyacc",
	Camlp4 = "camlp4",
	ObjectiveCpp = "Objective-C++",
	ObjectiveC = "Objective-C",
	PHPSource = "PHP Source",
	PHP = "PHP",
	Pascal = "Pascal",
	Perl = "Perl",
	Python = "Python",
	RegularExpressionsPython = "Regular Expressions (Python)",
	RConsole = "R Console",
	R = "R",
	Rdoc = "Rd (R Documentation)",
	HTML_Rails = "HTML (Rails)",
	JavaScript_Rails = "JavaScript (Rails)",
	RubyHaml = "Ruby Haml",
	RubyOnRails = "Ruby on Rails",
	SQL_Rails = "SQL (Rails)",
	RegularExpression = "Regular Expression",
	ReStructuredText = "reStructuredText",
	Ruby = "Ruby",
	CargoBuildResults = "Cargo Build Results",
	Rust = "Rust",
	SQL = "SQL",
	Scala = "Scala",
	Bash = "Bourne Again Shell (bash)",
	GenericUnixShell = "Shell-Unix-Generic",
	CommandsBuiltinShellBash = "commands-builtin-shell-bash",
	HTML_TCL = "HTML (Tcl)",
	Tcl = "Tcl",
	Textile = "Textile",
	XML = "XML",
	YAML = "YAML",
	ConundrumAi = "conundrum-ai",
	Dictionary = "dictionary",
}

export interface ParsedCodeBlock {
	language: SupportedCodeBlockSyntax;
	meta_data?: string;
	depth: number;
	content: string;
	full_match: string;
}

export interface AiSerializationRequestPhase1 {
	parsing_result: ParsedCodeBlock;
}

export interface BlockMathResult {
	body: ConundrumString;
	id?: ConundrumString;
	idx: number;
}

export interface BlockQuoteResult {
	/**
	 * The inner content already fully parsed into `ParsedElement`s.
	 * Nesting is handled recursively: a `> > ...` line becomes a
	 * `BlockQuote` variant inside this `Vec`.
	 */
	children: ParsedElement[];
	/** The full original source text that was consumed. */
	full_match: string;
}

export interface Card {
	title: ConundrumString;
	subtitle?: ConundrumString;
	children: Children;
	/**
	 * The title depth between 1-6 for the markdown output. This will have no
	 * effect on mdx, jsx, or plain text output. Defaults to 5
	 * ```rust
	 * let card = Card {
	 * title: vec![],
	 * subtitle: None,
	 * children: vec![],
	 * markdown_title_depth: None
	 * }
	 * assert_eq!(card.markdown_title_depth, Some(5));
	 * ```
	 */
	markdown_title_depth?: HeadingDepth;
}

export interface CitationResult {
	/** The parsed citation key. */
	citation_key: string;
	/** The complete bibtex entry */
	idx: number;
}

export interface CitationSummaryData {
	citation_key: string;
	body: string;
}

export interface ConundrumCommentResult {
	content: string;
}

export interface DocumentSpan {
	start: number;
	end: number;
}

export enum ConundrumErrorPurpose {
	Info = "info",
	Warn = "warn",
	Suggest = "suggestion",
	SyntaxError = "syntax",
	ConfigurationBug = "config",
}

export interface ConundrumError {
	/**
	 * A required message displayed in a toast or card header. Can contain
	 * regular, swift-inline compatible markdown only.
	 */
	msg: string;
	pos?: DocumentSpan;
	/**
	 * Details is an optional conundrum string offering a more thorough
	 * explanation to the user if one can be generated.
	 */
	details?: string;
	/**
	 * An indicator that can be used when the warning UI is implemented to show
	 * user's errors that allowed their notes to still compile. There's
	 * lot's of useful information that can be gathered from these errors,
	 * inclduding property suggestions & more.
	 * 
	 * Making it optional for now because I'm too lazy to go back and rewrite
	 * all of the errors.
	 */
	purpose?: ConundrumErrorPurpose;
}

export interface ConundrumObject {
	data: Map<string, ParsedElement>;
}

export interface DictionaryEntryResult {
	label: string;
	body: string;
}

export interface DictionaryEntryResultData {
	label: string;
	note_id?: string;
}

export interface EmojiData {
	name: string;
	svg: string;
}

export interface EmojiDocsDemo {
}

/**
 * Use the built-in `:smile:` syntax to insert a text sized emoji, or use the
 * `Emoji` component to create a scalable and resizable emoji as an image.
 */
export interface EmojiResult {
	name: ConundrumString;
	/**
	 * Because images are notoriously finicky to style, you should prefer the
	 * sizable boolean keys instead of the `width="small"` or similar
	 * properties. This means that your component might end up looking
	 * something like:
	 * 
	 * ```tsx
	 * <Emoji name="smile" medium border ... />
	 * ```
	 * 
	 * Instead of
	 * 
	 * ```tsx
	 * <Emoji name="smile" width="medium" border ... />
	 * ```
	 * 
	 * The other properties are still available, but these unique boolean
	 * properties will apply styles that will more reliably shape the
	 * underlying image.
	 */
	sizable: SizablePropsGroup;
	/** Default: "small", text sized. */
	size?: SizableOption;
}

export interface EmojiSearchResults {
	names: EmojiData[];
	/** The total number of matches */
	total: number;
}

/**
 * ## Example Usage
 * 
 * ```mdx
 * <EqRef id="my-equation" anchor>
 * $$
 * e=mc^2
 * $$
 * </EqRef>
 * 
 * yada, yada, yada, My equation <EqRef id="my-equation" /> is awesome...
 * ```
 * 
 * The above will result in something like:
 * 
 * _yada, yada, yada, My equation 1 is awesome..._
 * 
 * Or whatever index is represented by that equation, allowing you to reference
 * equations by index without worrying about the structure of your note
 * changing.
 * 
 * #### Indices
 * 
 * The equation reference component uses 1 based indices for plain text and
 * markdown since they are likely going to be displayed directly, and zero
 * based indices for everything where the output will be handled by a developer
 * before being displayed (React, HTML, Swift, etc..) because 1 based indices
 * suck.
 */
export interface EquationReference {
	/**
	 * The `id` field is a string that can be referenced later to use this
	 * equation's number.
	 */
	id: ConundrumString;
	/**
	 * This has no effect when `anchor=true`, but will have make the index
	 * subscript when `anchor` is not set.
	 */
	subscript?: ConundrumBoolean;
	/**
	 * This has no effect when `anchor=true`, but will have make the index
	 * superscript when `anchor` is not set.
	 */
	superscript?: ConundrumBoolean;
	/**
	 * Style the output index according to one of the available Emphasis styles
	 * if you like.
	 */
	emphasis?: Emphasis;
}

/**
 * The `[^1]` syntax that goes in the markdown content, _not_ the footnote that
 * goes in the footer.
 */
export interface FootNoteAnchor {
	idx: ConundrumInt;
}

export interface FootNoteFooter {
	idx: number;
	content: Children;
}

export interface FrontMatterResult {
	ignored_parsers: string[];
	title?: string;
	user_defined_id?: string;
	file_path?: string;
	topic?: string;
	subject?: string;
	summary?: string;
}

export type GridColumnPropUnion = 
	| { tag: "Number", content: ConundrumInt }
	| { tag: "String", content: ConundrumString };

export interface GridColumnGroup {
	none?: GridColumnPropUnion;
	small?: GridColumnPropUnion;
	smedium?: GridColumnPropUnion;
	medium?: GridColumnPropUnion;
	large?: GridColumnPropUnion;
	xl?: GridColumnPropUnion;
	xxl?: GridColumnPropUnion;
	full?: GridColumnPropUnion;
	fit?: ConundrumBoolean;
	responsive?: ConundrumBoolean;
}

/**
 * When a component is rendered in a markdown environment, apply these styles
 * if the more complex rendering strategies are not available.
 */
export enum InlineMarkdownOverride {
	Plain = "plain",
	BoldItalic = "bold_italic",
	Italic = "italic",
	Bold = "bold",
}

export interface Highlight {
	children: Children;
	/** Default: .highlight */
	emphasis: Emphasis;
	/**
	 * Control the markdown formatting when the output format is a markdown
	 * variant. This property is common throughout Conundrum, but the default
	 * is unique to each component.
	 * Default: `.Italic`
	 */
	markdown?: InlineMarkdownOverride;
}

export interface Hint {
	/**
	 * Note that `label` is a String and note a vector of children. This means
	 * that the fragment syntax won't work and markdown may or may not work in
	 * the label. Default: "hint".
	 */
	label?: ConundrumString;
	children: Children;
	emphasis: Emphasis;
	markdown_title_depth?: HeadingDepth;
}

export interface HrWithChildrenResult {
	children: Children;
}

export type CodeBlockLanguage = 
	| { tag: "DefaultLanguage", content?: undefined }
	| { tag: "UserProvided", content: string };

export interface InlineCodeResult {
	content: string;
	lang: CodeBlockLanguage;
}

export interface InlineMathResult {
	body: ConundrumString;
}

export interface JavascriptBooleanResult {
	value: boolean;
}

export type ParsedJavascriptElement = 
	| { tag: "Boolean", content: JavascriptBooleanResult }
	| { tag: "Number", content: JavascriptNumberResult }
	| { tag: "String", content: JavascriptStringResult }
	| { tag: "Object", content: JavascriptObjectResult }
	| { tag: "KeyValuePair", content: JavascriptObjectKeyValuePair }
	| { tag: "Function", content: JavascriptFunction };

export interface JavascriptFunction {
	parameters: ParsedJavascriptElement[];
	javascript_body: string;
}

export type ConundrumNumber = 
	| { tag: "Int", content: ConundrumInt }
	| { tag: "Float", content: ConundrumFloat };

/**
 * Creating the distinction between ints and floats will be important as the
 * runtime will execute mostly in Rust, and being able to parse some of the
 * mdx, javascript inputs will be super useful.
 */
export interface JavascriptNumberResult {
	value: ConundrumNumber;
}

export interface JavascriptObjectKeyValuePair {
	key: string;
	value: ParsedElement;
}

export interface JavascriptObjectResult {
	data: Map<string, ParsedElement>;
}

export interface JavascriptStringResult {
	value: string;
	delimiter: string;
}

export interface JsxStringPropertyResult {
}

export interface MarkdownBoldAndItalicTextResult {
	children: Children;
}

export interface MarkdownBoldTextResult {
	children: Children;
}

export interface MarkdownHeadingResult {
	depth: number;
	/**
	 * The indentation level to be used when displaying this in an inline table
	 * of contents, not necessarily the level of the heading since some heading
	 * lists will skip a depth.
	 */
	tab_depth: number;
	children: ParsedElement[];
	subtitle?: ParsedElement[];
	id: ConundrumString;
}

/**
 * The same as the `MarkdownHeadingResult` struct but wth the children
 * rendered.
 */
export interface MarkdownHeadingStringifiedResult {
	depth: number;
	tab_depth: number;
	content: string;
	id: string;
}

export interface MarkdownItalicTextResult {
	children: Children;
}

export interface MarkdownLinkResult {
	text: string;
	url: string;
}

export interface MarkdownParagraphResult {
	children: ParsedElement[];
}

/** The 'math' is embedded in `.jsx` as a child. */
export interface MathData {
	display: boolean;
	/**
	 * The `idx` field will only be set for equations where display=true, for
	 * obvious reasons.
	 */
	idx?: number;
	/** An optional user provided id, only applicable for block-level math. */
	id?: string;
	/** The primary math content. */
	content: string;
}

export interface TagResult {
	body: string;
}

export interface NoteOutgoingLinkResult {
	/** The user defined id on the target note. */
	link_to_note_id: string;
}

export interface MdxParsingResult {
	note_id?: string;
	content: string;
	tags: TagResult[];
	front_matter?: FrontMatterResult;
	ordered_citation_keys: string[];
	dictionary_entries: DictionaryEntryResult[];
	outgoing_links: NoteOutgoingLinkResult[];
	toc: MarkdownHeadingStringifiedResult[];
	/**
	 * Always set to false initially, but can be set to true by certain parsers
	 * to avoid further parsing.
	 */
	ignore_all_parsers: boolean;
	ai_secondary_parse_requests: AiSerializationRequestPhase1[];
	/**
	 * The map of the user provided equation id (to the `EqRef` component) and
	 * the index that the equation appears.
	 */
	eq_ref_map: Record<string, number>;
	warnings: ConundrumError[];
	included_components: string[];
}

export interface PaginationParams {
	per_page: number;
	page: number;
}

/**
 * The goal with these modifiers is to have a few different compile targets
 * (markdown, mdx, jsx, eventually straight to html/js, and then to an AST that
 * can be handled by other UI ecosystems), and these modifiers is how we can
 * achieve that.
 * 
 * All modifiers that start with `TargetXYZ` are applied as sort of a
 * collection of other modifiers, or at least that's how they're intended to
 * work.
 */
export enum ConundrumModifier {
	/**
	 * This might as well be called `TargetMarkdown`, but this was created
	 * before the idea of 'targets' came to be merged with 'modifiers' and I'm
	 * in too much of a hurry to change it now.
	 * 
	 * As with the `.PreferInlineMarkdownSyntax` flag, many components allow
	 * you to customize the bahavior of each component:
	 * 
	 * ```jsx
	 * <Card
	 * title="My title"
	 * /// Set the heading title depth.
	 * markdownHeading={3}
	 * >
	 * ...
	 * </Card>
	 * ```
	 */
	PreferMarkdownSyntax = "PreferMarkdownSyntax",
	/** Hide the emojis completely for platforms that don't support them. */
	HideEmojis = "HideEmojis",
	/**
	 * Curretly does pretty much the same thing as .PreferMarkdownSyntax, but
	 * once the markdown parser has been completely migrated this will stop
	 * things like wrapping the outermost block in a paragraph.
	 * 
	 * The goal with this is to behave much like SwiftUI's markdown support,
	 * with the ability to render only inline markdown for things like
	 * titles where a full `Admonition` wouldn't make sense.
	 * 
	 * Keep in mind that many components allow you to customize the
	 * **markdown** output as well as the html/js output. You can do the
	 * following:
	 * 
	 * ```jsx
	 * <Hl markdown="italic" highlight>My text</Hl>
	 * ```
	 */
	PreferInlineMarkdownSyntax = "PreferInlineMarkdownSyntax",
	/**
	 * Useful for search related features, being able to match text without
	 * markdown syntax interfering. Not super useful for much else.
	 */
	ForcePlainText = "ForcePlainText",
	/**
	 * This is really only useful for when your environment can't support any
	 * other output format.
	 */
	DecoratedPlainText = "DecoratedPlainText",
	/**
	 * Set this flag when the output is intended to be consumed by AI, probably
	 * with the `.PreferMarkdownSyntax` flag.
	 */
	ForAIInput = "ForAIInput",
	/**
	 * When this component is to be used for search text input, all of the
	 * component jsx and mdx syntax will be removed, leaving only
	 * searchable text.
	 */
	ForSearchInput = "ForSearchInput",
	/** Don't touch the code blocks, just return them exactly as is. */
	CodeBlocksAsIs = "CodeBlocksAsIs",
	/**
	 * Leave the markdown output mostly alone and render to mdx instead of jsx.
	 * This is a super easy gateway for developers to build around
	 * Conundrum as the compile target is **super** forgiving.
	 * 
	 * This is the default target for now, but the current goal is to finish
	 * rest of the parser, which would make the dependence on mdx obsolete.
	 */
	TargetMdx = "TargetMdx",
	/**
	 * This is the goal, but this is still _super_ buggy and should in no way
	 * be used in any application that you expect someone to actually use,
	 * but we'll get there...
	 */
	TargetJsx = "TargetJsx",
	/**
	 * This is even more of a futuristic goal, but for ultimate performance we
	 * can even leave behind React. There are other priorities for now, but
	 * this is something that will naturally come together as the framework
	 * progresses.
	 */
	TargetHtmlJs = "TargetHtmlJs",
}

export enum EmbeddableComponentName {
	Toc = "Toc",
	Admonition = "Admonition",
	Hl = "Hl",
	Highlight = "Highlight",
	Ul = "Ul",
	Underline = "Underline",
	Card = "Card",
	Grid = "Grid",
	UtlityContainer = "Container",
	HrWithChildren = "Hr",
	Hint = "Hint",
	Emoji = "Emoji",
	EqRef = "EqRef",
	Tabs = "Tabs",
	Tab = "Tab",
	AINoteSummary = "AINoteSummary",
}

export enum SupportedCodeBlockTheme {
	InspiredGitHub = "InspiredGitHub",
	SolarizedDark = "Solarized (dark)",
	SolarizedLight = "Solarized (light)",
	Base16_80sDark = "base16-eighties.dark",
	Base16_MochaDark = "base16-mocha.dark",
	Base16_OceanDark = "base16-ocean.dark",
	Base16_OceanLight = "base16-ocean.light",
}

export interface UIParams {
	dark_mode: boolean;
	/** A number 0-n, where n > 1 increases the fontsize. */
	font_scalar: number;
	math_font_scalar: number;
	syntax_theme?: SupportedCodeBlockTheme;
}

/** This is the core 'input' for Conundrum. */
export interface ParseConundrumOptions {
	/**
	 * The id of your note. This can be generic, unique to each application,
	 * but so-long as the note has the **concept** of an id the id can be
	 * inserted into certain components to make it easier for the front-end
	 * to collect data without the need for complicated outside state.
	 */
	note_id?: string;
	/** Your conundrum content, obviously. */
	content: string;
	/**
	 * Kind of the core piece of Conundrum, the ability to write in a superset
	 * of Markdown and to compile to a variety of targets, including just
	 * regular, traditional markdown (the goal is to comply with the Commonmark
	 * spec eventually, we're still missing some things that are being cleaned
	 * up by the runtime environment).
	 */
	modifiers: ConundrumModifier[];
	/**
	 * Hide specific components that are incompatable with the target output
	 * environment. This is done automatically with the `.ForAiInput` flag
	 * for all AI input components so not to confuse the AI, but there
	 * maybe other use cases as well. Any component added here will render
	 * _nothing_, but it's state will still be applied to the result.
	 */
	hide_components: EmbeddableComponentName[];
	ui_params: UIParams;
}

export interface ParsedCitation {
	key: string;
	full_match: string;
	idx: number;
}

export interface ParsedInspectionRequest {
	/** An EmbeddableComponentName or InContentDocumentationId */
	keyword: string;
	level: number;
	full_match: string;
}

export interface ParsedOutgoingNoteLink {
	/** The user-defined id of the note which is being linked to. */
	note_id: string;
	/** The text content of the link. `[The stuff here](note:MyNote)` */
	content: string;
	/**
	 * The full content of the input string that represents this outgoing note
	 * link.
	 */
	full_match: string;
}

export interface ParsedTag {
	/** The tag's body */
	body: string;
	/** The full match of the content that was originally in the note. */
	full_match: string;
	markdown?: InlineMarkdownOverride;
}

export type ConundrumComponentType = 
	| { tag: "Toc", content: TableOfContents }
	| { tag: "Container", content: UtilityContainer }
	| { tag: "Card", content: Card }
	| { tag: "Tabs", content: TabsGroup }
	| { tag: "Tab", content: Tab }
	| { tag: "Grid", content: ResponsiveGrid }
	| { tag: "Hr", content: HrWithChildrenResult }
	| { tag: "Admonition", content: Admonition }
	| { tag: "Hint", content: Hint }
	| { tag: "Ul", content: Underline }
	| { tag: "Hl", content: Highlight }
	| { tag: "Emoji", content: EmojiResult }
	| { tag: "EqRef", content: EquationReference }
	| { tag: "EmojiDocsDemo", content: EmojiDocsDemo };

export interface ReactComponentSelfClosingResult {
	full_text: string;
	component: ConundrumComponentType;
}

export interface ReactComponentWithChildrenResult {
	full_text: string;
	component: ConundrumComponentType;
}

export type GridColumnProps = 
	| { tag: "ByColumn", content: GridColumnGroup }
	| { tag: "Generalized", content: ConundrumInt };

export interface ResponsiveGrid {
	sizable?: SizablePropsGroup;
	columns?: GridColumnProps;
	children: Children;
}

export interface StringUnion {
	opts: string[];
	value: string;
}

export interface Tab {
	/** The label of the button that toggles this tab. */
	label: ConundrumString;
	/**
	 * This is only required if the `label` field occurs more than once in the
	 * same `Tabs` component. Each `Tab` must have a unique `id` field, it's
	 * just set to the label by default.
	 */
	id?: ConundrumString;
	children: Children;
}

export interface TableOfContents {
	expanded?: ConundrumBoolean;
}

/**
 * Group and organize your notes by swappable tabs. Pretty self explanatory
 * honestly...
 * 
 * ### Usage
 * > I know it's called `TabsGroup` here, but in Conundrum it's actually
 * > implemented as `Tabs`.
 * 
 * ```jsx
 * <Tabs>
 * <Tab label="My label">
 * My tab content one
 * </Tab>
 * <Tab label="My label 2">
 * My tab content two
 * </Tab>
 * <Tab label="My label"
 * // This id is required because the
 * // label appears more than once!
 * id="myUniqueId">
 * My tab content three
 * </Tab>
 * </Tabs>
 * ```
 */
export interface TabsGroup {
	/** The styles applied to the active tab. Default: `.card` */
	emphasis?: Emphasis;
	/**
	 * The `Tabs` component extends the `SizablePropsGroup` struct, but be
	 * careful... you're getting into the struggles of a developer now as
	 * these responsive containers can be difficult to make look good on
	 * all screen sizes. You'll get the hang of it, but be sure not to be too
	 * ambitious and implement a look that _barely_ fits, because it almost
	 * surely **won't** fit when you rotate the device or open another
	 * window.
	 */
	sizable?: SizablePropsGroup;
	children: Children;
}

export interface TitleGroup {
	title: string;
	subtitle?: string;
}

export interface Underline {
	children: Children;
	/** Default: .highlight */
	emphasis: Emphasis;
	/** Default: .Plain */
	markdown?: InlineMarkdownOverride;
}

/**
 * > Note that the `label` property can also be changed from it's default
 * > 'Hint' to any string.
 * 
 * 
 * The `Container` component is an intentionally almost entirely unstyled
 * component that accepts most of the _generic_ properties accepted elsewhere.
 * This means that it takes an optional `Emphasis` as a boolean, and all of the
 * `SizableObject` properties like `width`, `margin`, `padding`, `text` for
 * font size and a handful of positionable props. The goal with the `Container`
 * component is to provide a blank canvas to allow you to create some
 * responsive & informative layouts that fit your own use case.
 */
export interface UtilityContainer {
	sizable: SizablePropsGroup;
	emphasis?: Emphasis;
	children: Children;
}

export enum AiSerializationRequestType {
	CreateNoteSpecificStudyGuide = "CreateNoteSpecificStudyGuide",
	SummarizeNote = "SummarizeNote",
	RecommendResearch = "RecommendResearch",
}

export enum AutoInsertedComponentName {
	NoteLink = "NoteLink",
	AutoInsertedTag = "AutoInsertedTag",
	FlusterCitation = "FlusterCitation",
	DictionaryEntry = "DictionaryEntry",
	FlusterAiParsePendingContainer = "FlusterAiParsePendingContainer",
	AutoInsertedHeading = "AutoInsertedHeading",
	AutoInsertedCodeBlock = "AutoInsertedCodeBlock",
	AutoInsertedBlockQuote = "AutoInsertedBlockQuote",
	AutoInsertedMathBlock = "AutoInsertedMathBlock",
	AutoInsertedMarkdownLink = "AutoInsertedMarkdownLink",
	AutoInsertedMarkdownParagraph = "AutoInsertedMarkdownParagraph",
}

/**
 * To enforce some uniformity and ease-of-use between components, this enum
 * represents a list of commonly used property keys. The code itself doesn't
 * care that these keys are the same, but the predictability should help new
 * users.
 */
export enum CommonComponentPropertyKey {
	MarkdownHeading = "markdownHeading",
	InlineMarkdownOverride = "markdown",
}

export type ConundrumErrorVariant = 
	| { tag: "MultiThreadingError", content?: undefined }
	| { tag: "FailToFindTitleGroup", content?: undefined }
	| { tag: "FailToFindComponent", content: string }
	| { tag: "FailToGenerateString", content?: undefined }
	| { tag: "FrontMatterError", content?: undefined }
	| { tag: "UserFacingGeneralParserError", content: ConundrumError }
	| { tag: "UserFacingMissingOrIncorrectProperty", content: ConundrumError }
	| { tag: "InternalParserError", content: ConundrumError };

export type ConundrumLogicToken = 
	| { tag: "Number", content: ConundrumNumber }
	| { tag: "String", content: ConundrumString }
	| { tag: "Bool", content: ConundrumBoolean };

export enum DocumentationComponentName {
	InContentDocumentationContainer = "InContentDocumentationContainer",
	InContentDocsEmphasisTypeList = "InContentDocsEmphasisTypeList",
	InContentDocsHighlightDemo = "InContentDocsHighlightDemo",
	InContentDocsUnderlineDemo = "InContentDocsUnderlineDemo",
	EmojiDocumentationDemo = "AutoInsertedNestedEmojiDocumentation",
}

/** From typescript to swift. */
export enum EmbeddableComponentId {
	Toc = "toc",
	Admonition = "admonition",
	Hl = "highlight",
	Ul = "underline",
	Card = "card",
	Grid = "grid",
	UtlityContainer = "util-container",
	HrWithChildren = "hr-with-children",
	Hint = "embeddable-hint-component",
	Emoji = "emoji-component",
	Tabs = "tab-group",
	Tab = "tab-group-tab",
	EqRef = "equation-reference",
	AINoteSummary = "ai-note-summary",
}

export enum InContentDocumentationFormat {
	Full = "full",
	Short = "short",
}

export enum InContentDocumentationId {
	Markdown = "Markdown",
	Docs = "Docs",
	Syntax = "Syntax",
	Jsx = "Jsx",
	Code = "Code",
	SizableObject = "Sizable",
	Emphasis = "Emphasis",
	Emoji = "Emoji",
	Components = "Components",
	AI = "AI",
	Conundrum = "Conundrum",
}

export enum InContentDocumentationSource {
	ComponentDocs = "component",
	InternalDocs = "internal-docs",
}

export enum ParserId {
	Tags = "tags",
	Citations = "citations",
	Dictionary = "dictionary",
	NoteLink = "note_link",
	Documentation = "docs",
	AiTrigger = "ai",
	HrWithChildren = "hr",
}

