/*
 Generated by typeshare 1.13.3
*/


/** From typescript to swift. */
export enum BibtexEditorWebviewActions {
	RequestBibtexEditorData = "request-bibtex-data",
	SetWebviewLoaded = "set-bibtex-webview-loaded",
	OnEditorChange = "on-bib-editor-change",
}

/** From swift to typescript */
export enum BibtexEditorWebviewEvents {
	SetInitialColorScheme = "set-bib-initial-color-scheme",
	SetBibtexEditorContent = "set-bibtex-data",
	SetEditorKeymap = "set-bib-editor-keymap",
	SetCodeTheme = "set-bib-code-theme",
	SetCodeThemeLight = "set-bib-code-theme-light",
	SetCodeThemeDark = "set-bib-code-theme-dark",
}

export enum BibtexEditorWebviewLocalStorageKeys {
	InitialValue = "bibtex-editor-initial-value",
}

/** From typescript to swift. */
export enum MdxPreviewWebviewActions {
	RequestNoteData = "request-note-data",
	SetWebviewLoaded = "set-preview-webview-loaded",
}

/** From swift to typescript */
export enum MdxPreviewWebviewEvents {
	SetInitialColorScheme = "set-initial-color-scheme",
	SetPreviewContent = "set-mdx-preview-content",
}

/** From typescript to swift. */
export enum NoteDetailWebviewActions {
	RequestNoteDetailData = "request-note-detail-data",
	SetWebviewLoaded = "set-note-detail-webview-loaded",
}

/** From swift to typescript */
export enum NoteDetailWebviewEvents {
	SetInitialColorScheme = "set-initial-color-scheme",
	SetNoteDetails = "set-note-details",
}

/** From typescript to swift. */
export enum SplitviewEditorWebviewActions {
	RequestSplitviewEditorData = "request-editor-data",
	RequestParsedMdxContent = "request-parsed-mdx",
	OnEditorChange = "on-editor-change",
	SetWebviewLoaded = "set-editor-webview-loaded",
	OnTagClick = "tag-click-event",
	SetIsLandscape = "set-is-landscape-view",
}

/** From swift to typescript */
export enum SplitviewEditorWebviewEvents {
	SetInitialColorScheme = "set-initial-color-scheme",
	SetSplitviewEditorContent = "set-editor-content",
	SetParsedMdxContent = "set-parsed-mdx-content",
	SetEditorKeymap = "set-editor-keymap",
	SetCodeTheme = "set-code-theme",
	SetCodeThemeLight = "set-code-theme-light",
	SetCodeThemeDark = "set-code-theme-dark",
	ResetPreviewScrollPosition = "reset-mdx-preview-scroll-position",
}

export enum SplitviewEditorWebviewLocalStorageKeys {
	InitialValue = "editor-initial-value",
	ParsedMdxData = "parsed-mdx-data",
	CodeTheme = "editor-code-theme",
	CodeThemeDark = "editor-code-theme-dark",
	CodeThemeLight = "editor-code-theme-light",
	EditorKeymap = "editor-keymap",
}

