/*
 Generated by typeshare 1.13.3
*/


export enum AutoTaggableType {
	Tag = "tag",
	Topic = "topic",
	Subject = "subject",
}

/** From typescript to swift. */
export enum BibtexEditorWebviewActions {
	RequestBibtexEditorData = "request-bibtex-data",
	SetWebviewLoaded = "set-bibtex-webview-loaded",
	OnEditorChange = "on-bib-editor-change",
}

/** From swift to typescript */
export enum BibtexEditorWebviewEvents {
	SetInitialColorScheme = "set-bib-initial-color-scheme",
	SetBibtexEditorContent = "set-bibtex-data",
	SetEditorKeymap = "set-bib-editor-keymap",
	SetCodeTheme = "set-bib-code-theme",
	SetCodeThemeLight = "set-bib-code-theme-light",
	SetCodeThemeDark = "set-bib-code-theme-dark",
}

export enum BibtexEditorWebviewLocalStorageKeys {
	InitialValue = "bibtex-editor-initial-value",
}

/** From typescript to swift. */
export enum DictionaryWebviewActions {
	RequestDictionaryData = "request-dictionary-data",
	SetWebviewLoaded = "set-webview-loaded",
}

/** From swift to typescript */
export enum DictionaryWebviewEvents {
	SetInitialColorScheme = "set-initial-color-scheme",
	SetDictionaryData = "set-dictionary-data",
	SetCodeTheme = "set-code-theme",
}

export enum DictionaryWebviewIds {
	DictionaryContainer = "dictionary-container",
}

export enum DictionaryWebviewStorageKeys {
	ScrollPositionPortrait = "dict-scroll-pos-portrait",
	ScrollPositionLandscape = "dict-scroll-pos-landscape",
	DictionaryData = "dict-data",
}

/** From typescript to swift. */
export enum MdxPreviewWebviewActions {
	RequestNoteData = "request-note-data",
	SetWebviewLoaded = "set-preview-webview-loaded",
	ViewNoteByUserDefinedId = "view-note-by-user-def-id",
	ViewNoteById = "view-note-by--id",
	OnTagClick = "tag-click-event",
}

/** From swift to typescript */
export enum MdxPreviewWebviewEvents {
	SetInitialColorScheme = "set-initial-color-scheme",
	SetPreviewContent = "set-mdx-preview-content",
}

/** From typescript to swift. */
export enum NoteDetailWebviewActions {
	RequestNoteDetailData = "request-note-detail-data",
	SetWebviewLoaded = "set-note-detail-webview-loaded",
	HandleTagClick = "handle-tag-click",
	HandleTopicClick = "handle-topic-click",
	HandleSubjectClick = "handle-subject-click",
	HandleCitationClick = "handle-citation-click",
}

/** From swift to typescript */
export enum NoteDetailWebviewEvents {
	SetInitialColorScheme = "set-initial-color-scheme",
	SetNoteDetails = "set-note-details",
}

/** From typescript to swift. */
export enum SharedWebviewActions {
	JavascriptError = "javascript-error",
}

/** From typescript to swift. */
export enum SplitviewEditorWebviewActions {
	RequestSplitviewEditorData = "request-editor-data",
	RequestParsedMdxContent = "request-parsed-mdx",
	OnEditorChange = "on-editor-change",
	SetWebviewLoaded = "set-editor-webview-loaded",
	OnTagClick = "tag-click-event",
	SetIsLandscape = "set-is-landscape-view",
}

/** From swift to typescript */
export enum SplitviewEditorWebviewEvents {
	SetInitialColorScheme = "set-initial-color-scheme",
	SetSplitviewEditorContent = "set-editor-content",
	SetParsedMdxContent = "set-parsed-mdx-content",
	SetParsedMdxContentString = "set-editor-content-str",
	SetEditorKeymap = "set-editor-keymap",
	SetEditorSnippetProps = "set-editor-snippet-props",
	SetCodeTheme = "set-code-theme",
	SetCodeThemeLight = "set-code-theme-light",
	SetCodeThemeDark = "set-code-theme-dark",
	ResetPreviewScrollPosition = "reset-mdx-preview-scroll-position",
	EmitMdxParsingError = "mdx-parsing-error",
	EmitMdxParsingSuccess = "mdx-parsing-success",
}

export enum SplitviewEditorWebviewIds {
	PortraitPreview = "mdx-preview-portrait",
	LandscapePreview = "mdx-preview-landscape",
}

export enum SplitviewEditorWebviewLocalStorageKeys {
	InitialValue = "editor-initial-value",
	ParsedMdxData = "parsed-mdx-data",
	CodeTheme = "editor-code-theme",
	CodeThemeDark = "editor-code-theme-dark",
	CodeThemeLight = "editor-code-theme-light",
	EditorKeymap = "editor-keymap",
	ScrollPositionPortrait = "splitview-editor-scroll-position-portrait",
	ScrollPositionLandscape = "splitview-editor-scroll-position-landscape",
}

/** From typescript to swift. */
export enum WebviewEnvironment {
	MacOS = "fluster-mac",
	IPad = "fluster-ipad",
	MultiPlatformDesktop = "fluster-multi-platform-desktop",
}

