pub const BASE_TEMPERATURE_CHAT: f32 = 0.5;
pub const BASE_TEMPERATURE_NOTE_CREATION: f32 = 0.5;
pub const BASE_TEMPERATURE_TEXT_SUMMARIZATION: f32 = 0.5;
pub const BASE_TEMPERATURE_STRUCTURED_GENERATION: f32 = 0.2;
