// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

/**
 * THIS toString METHOD WILL NOT MATCH THE RUST, TYPESCRIPT, or RUST EQUIVALENT!!!
 */
export enum EditorSaveMethodReflection {
  OnSave = 1,
  OnChange = 2
}
