// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { EditorCitationReflection } from '../state-reflection/editor-citation-reflection.js';
import { EditorSaveMethodReflection } from '../state-reflection/editor-save-method-reflection.js';
import { EditorTagReflection } from '../state-reflection/editor-tag-reflection.js';
import { EditorViewReflection } from '../state-reflection/editor-view-reflection.js';
import { SnippetStateReflection } from '../state-reflection/snippet-state-reflection.js';


export class EditorStateReflection {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):EditorStateReflection {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsEditorStateReflection(bb:flatbuffers.ByteBuffer, obj?:EditorStateReflection):EditorStateReflection {
  return (obj || new EditorStateReflection()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsEditorStateReflection(bb:flatbuffers.ByteBuffer, obj?:EditorStateReflection):EditorStateReflection {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new EditorStateReflection()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

noteId():string|null
noteId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
noteId(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

baseKeymap():string|null
baseKeymap(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
baseKeymap(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

citations(index: number, obj?:EditorCitationReflection):EditorCitationReflection|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? (obj || new EditorCitationReflection()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

citationsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

keymap():string|null
keymap(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
keymap(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

theme():string|null
theme(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
theme(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

tags(index: number, obj?:EditorTagReflection):EditorTagReflection|null {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? (obj || new EditorTagReflection()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

tagsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

allCitationIds(index: number):string
allCitationIds(index: number,optionalEncoding:flatbuffers.Encoding):string|Uint8Array
allCitationIds(index: number,optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? this.bb!.__string(this.bb!.__vector(this.bb_pos + offset) + index * 4, optionalEncoding) : null;
}

allCitationIdsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

value():string|null
value(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
value(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 18);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

parsedValue():string|null
parsedValue(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
parsedValue(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 20);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

haveSetInitialValue():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 22);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

editorView():EditorViewReflection {
  const offset = this.bb!.__offset(this.bb_pos, 24);
  return offset ? this.bb!.readInt8(this.bb_pos + offset) : EditorViewReflection.Pending;
}

snippetProps(obj?:SnippetStateReflection):SnippetStateReflection|null {
  const offset = this.bb!.__offset(this.bb_pos, 26);
  return offset ? (obj || new SnippetStateReflection()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

lockEditorScrollToPreview():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 28);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

saveMethod():EditorSaveMethodReflection {
  const offset = this.bb!.__offset(this.bb_pos, 30);
  return offset ? this.bb!.readInt8(this.bb_pos + offset) : EditorSaveMethodReflection.OnChange;
}

autoSaveTimeout():number {
  const offset = this.bb!.__offset(this.bb_pos, 32);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

static startEditorStateReflection(builder:flatbuffers.Builder) {
  builder.startObject(15);
}

static addNoteId(builder:flatbuffers.Builder, noteIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, noteIdOffset, 0);
}

static addBaseKeymap(builder:flatbuffers.Builder, baseKeymapOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, baseKeymapOffset, 0);
}

static addCitations(builder:flatbuffers.Builder, citationsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, citationsOffset, 0);
}

static createCitationsVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startCitationsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addKeymap(builder:flatbuffers.Builder, keymapOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, keymapOffset, 0);
}

static addTheme(builder:flatbuffers.Builder, themeOffset:flatbuffers.Offset) {
  builder.addFieldOffset(4, themeOffset, 0);
}

static addTags(builder:flatbuffers.Builder, tagsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(5, tagsOffset, 0);
}

static createTagsVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startTagsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addAllCitationIds(builder:flatbuffers.Builder, allCitationIdsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(6, allCitationIdsOffset, 0);
}

static createAllCitationIdsVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startAllCitationIdsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addValue(builder:flatbuffers.Builder, valueOffset:flatbuffers.Offset) {
  builder.addFieldOffset(7, valueOffset, 0);
}

static addParsedValue(builder:flatbuffers.Builder, parsedValueOffset:flatbuffers.Offset) {
  builder.addFieldOffset(8, parsedValueOffset, 0);
}

static addHaveSetInitialValue(builder:flatbuffers.Builder, haveSetInitialValue:boolean) {
  builder.addFieldInt8(9, +haveSetInitialValue, +false);
}

static addEditorView(builder:flatbuffers.Builder, editorView:EditorViewReflection) {
  builder.addFieldInt8(10, editorView, EditorViewReflection.Pending);
}

static addSnippetProps(builder:flatbuffers.Builder, snippetPropsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(11, snippetPropsOffset, 0);
}

static addLockEditorScrollToPreview(builder:flatbuffers.Builder, lockEditorScrollToPreview:boolean) {
  builder.addFieldInt8(12, +lockEditorScrollToPreview, +false);
}

static addSaveMethod(builder:flatbuffers.Builder, saveMethod:EditorSaveMethodReflection) {
  builder.addFieldInt8(13, saveMethod, EditorSaveMethodReflection.OnChange);
}

static addAutoSaveTimeout(builder:flatbuffers.Builder, autoSaveTimeout:number) {
  builder.addFieldInt32(14, autoSaveTimeout, 0);
}

static endEditorStateReflection(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  builder.requiredField(offset, 18) // value
  return offset;
}

}
