/*
 Generated by typeshare 1.13.3
*/


export enum UniqueSettingKey {
	FirstName = "first-name",
	LastName = "last-name",
	Profession = "profession",
	AutoSyncOnNewChat = "auto-sync-on-new-chat",
	AutoSyncOnNewMsg = "auto-sync-on-new-msg",
	LocalAiPreference = "local-ai-preference",
	SaveLogDuration = "save-log-duration",
	LogVectorGenMethod = "log-vector-gen-method",
}

