// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { CitationResult } from '../../mdx-serialization/citation-result.js';


export class ParseMdxOptions {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):ParseMdxOptions {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsParseMdxOptions(bb:flatbuffers.ByteBuffer, obj?:ParseMdxOptions):ParseMdxOptions {
  return (obj || new ParseMdxOptions()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsParseMdxOptions(bb:flatbuffers.ByteBuffer, obj?:ParseMdxOptions):ParseMdxOptions {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ParseMdxOptions()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

content():string|null
content(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
content(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

citations(index: number, obj?:CitationResult):CitationResult|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new CitationResult()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

citationsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startParseMdxOptions(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addContent(builder:flatbuffers.Builder, contentOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, contentOffset, 0);
}

static addCitations(builder:flatbuffers.Builder, citationsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, citationsOffset, 0);
}

static createCitationsVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startCitationsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endParseMdxOptions(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createParseMdxOptions(builder:flatbuffers.Builder, contentOffset:flatbuffers.Offset, citationsOffset:flatbuffers.Offset):flatbuffers.Offset {
  ParseMdxOptions.startParseMdxOptions(builder);
  ParseMdxOptions.addContent(builder, contentOffset);
  ParseMdxOptions.addCitations(builder, citationsOffset);
  return ParseMdxOptions.endParseMdxOptions(builder);
}
}
