graph TD
	RPGS("@conundrum/docgen#build:mac") --> ETQY("@conundrum/swift#build:mac")
	RPGS("@conundrum/docgen#build:mac") --> KEFT("@conundrum/ts#build:mac")
	RPGS("@conundrum/docgen#build:mac") --> PRBV("@conundrum/wasm#build:mac")
	RPGS("@conundrum/docgen#build:mac") --> CXPQ("@fluster/bibtex_editor_webview#build:mac")
	RPGS("@conundrum/docgen#build:mac") --> MLKN("@fluster/editor_webview#build:mac")
	RPGS("@conundrum/docgen#build:mac") --> ZHXY("@fluster/note_detail_webview#build:mac")
	RPGS("@conundrum/docgen#build:mac") --> OVTW("@fluster/standalone_mdx_editor#build:mac")
	RPGS("@conundrum/docgen#build:mac") --> NDRI("@fluster/webview_utils#build")
	WGGN("@conundrum/main#build:scss") --> RDVF("___ROOT___")
	ETQY("@conundrum/swift#build:mac") --> PVEJ("@conundrum/swift#build:macSwift")
	PVEJ("@conundrum/swift#build:macSwift") --> RDVF("___ROOT___")
	CHNJ("@conundrum/swift#build:postCodegenCleanup") --> RDVF("___ROOT___")
	SXVB("@conundrum/swift#copy:extraSwift") --> RDVF("___ROOT___")
	VVSC("@conundrum/ts#build") --> WAGD("@conundrum/ts#build:vite")
	VVSC("@conundrum/ts#build") --> CQCF("@conundrum/ts#copy:globalCSS")
	KEFT("@conundrum/ts#build:mac") --> WGGN("@conundrum/main#build:scss")
	WAGD("@conundrum/ts#build:vite") --> RDVF("___ROOT___")
	CQCF("@conundrum/ts#copy:globalCSS") --> WGGN("@conundrum/main#build:scss")
	PRBV("@conundrum/wasm#build:mac") --> RDVF("___ROOT___")
	NOOO("@fluster/bib_lezer#build") --> CKYN("@fluster/bib_lezer#build:parser")
	NOOO("@fluster/bib_lezer#build") --> GPSL("@fluster/bib_lezer#build:scss")
	NOOO("@fluster/bib_lezer#build") --> QHDQ("@fluster/bib_lezer#build:ts")
	CKYN("@fluster/bib_lezer#build:parser") --> RDVF("___ROOT___")
	GPSL("@fluster/bib_lezer#build:scss") --> QHDQ("@fluster/bib_lezer#build:ts")
	QHDQ("@fluster/bib_lezer#build:ts") --> CKYN("@fluster/bib_lezer#build:parser")
	CXPQ("@fluster/bibtex_editor_webview#build:mac") --> NDRI("@fluster/webview_utils#build")
	MLKN("@fluster/editor_webview#build:mac") --> NDRI("@fluster/webview_utils#build")
	JJLV("@fluster/lezer#build") --> RDVF("___ROOT___")
	QLYZ("@fluster/lezer#build:website") --> JJLV("@fluster/lezer#build")
	ZHXY("@fluster/note_detail_webview#build:mac") --> NDRI("@fluster/webview_utils#build")
	OVTW("@fluster/standalone_mdx_editor#build:mac") --> NDRI("@fluster/webview_utils#build")
	NDRI("@fluster/webview_utils#build") --> NOOO("@fluster/bib_lezer#build")
	NDRI("@fluster/webview_utils#build") --> ORSQ("@fluster/webview_utils#build:website")
	JKAP("@fluster/webview_utils#build:tailwind") --> WGGN("@conundrum/main#build:scss")
	ORSQ("@fluster/webview_utils#build:website") --> VVSC("@conundrum/ts#build")
	ORSQ("@fluster/webview_utils#build:website") --> QLYZ("@fluster/lezer#build:website")
