graph TD
	RPGS("@conundrum/docgen#build:mac") --> ETQY("@conundrum/swift#build:mac")
	RPGS("@conundrum/docgen#build:mac") --> KEFT("@conundrum/ts#build:mac")
	RPGS("@conundrum/docgen#build:mac") --> PRBV("@fluster/bibtex_editor_webview#build:mac")
	RPGS("@conundrum/docgen#build:mac") --> CXPQ("@fluster/editor_webview#build:mac")
	RPGS("@conundrum/docgen#build:mac") --> MLKN("@fluster/note_detail_webview#build:mac")
	RPGS("@conundrum/docgen#build:mac") --> ZHXY("@fluster/standalone_mdx_editor#build:mac")
	RPGS("@conundrum/docgen#build:mac") --> OVTW("@fluster/webview_utils#build")
	NDRI("@conundrum/main#build:scss") --> WGGN("___ROOT___")
	ETQY("@conundrum/swift#build:mac") --> RDVF("@conundrum/swift#build:macSwift")
	RDVF("@conundrum/swift#build:macSwift") --> WGGN("___ROOT___")
	PVEJ("@conundrum/swift#build:postCodegenCleanup") --> WGGN("___ROOT___")
	CHNJ("@conundrum/swift#copy:extraSwift") --> WGGN("___ROOT___")
	SXVB("@conundrum/ts#build") --> VVSC("@conundrum/ts#build:vite")
	SXVB("@conundrum/ts#build") --> WAGD("@conundrum/ts#copy:globalCSS")
	KEFT("@conundrum/ts#build:mac") --> NDRI("@conundrum/main#build:scss")
	VVSC("@conundrum/ts#build:vite") --> WGGN("___ROOT___")
	WAGD("@conundrum/ts#copy:globalCSS") --> NDRI("@conundrum/main#build:scss")
	PRBV("@fluster/bibtex_editor_webview#build:mac") --> OVTW("@fluster/webview_utils#build")
	CXPQ("@fluster/editor_webview#build:mac") --> OVTW("@fluster/webview_utils#build")
	CQCF("@fluster/lezer#build") --> WGGN("___ROOT___")
	NOOO("@fluster/lezer#build:website") --> CQCF("@fluster/lezer#build")
	MLKN("@fluster/note_detail_webview#build:mac") --> OVTW("@fluster/webview_utils#build")
	ZHXY("@fluster/standalone_mdx_editor#build:mac") --> OVTW("@fluster/webview_utils#build")
	OVTW("@fluster/webview_utils#build") --> CKYN("@fluster/webview_utils#build:website")
	GPSL("@fluster/webview_utils#build:tailwind") --> NDRI("@conundrum/main#build:scss")
	CKYN("@fluster/webview_utils#build:website") --> SXVB("@conundrum/ts#build")
	CKYN("@fluster/webview_utils#build:website") --> NOOO("@fluster/lezer#build:website")
