graph TD
	RPGS("@conundrum/generated#build:scss") --> ETQY("___ROOT___")
	KEFT("@conundrum/ts#build") --> PRBV("@conundrum/ts#build:vite")
	KEFT("@conundrum/ts#build") --> CXPQ("@conundrum/ts#copy:globalCSS")
	PRBV("@conundrum/ts#build:vite") --> ETQY("___ROOT___")
	MLKN("@conundrum/ts#build:website") --> KEFT("@conundrum/ts#build")
	CXPQ("@conundrum/ts#copy:globalCSS") --> RPGS("@conundrum/generated#build:scss")
	ZHXY("@conundrum/wasm#build") --> ETQY("___ROOT___")
	OVTW("@conundrum/wasm#build:ts") --> ZHXY("@conundrum/wasm#build")
	NDRI("@conundrum/wasm#build:website") --> ZHXY("@conundrum/wasm#build")
	NDRI("@conundrum/wasm#build:website") --> OVTW("@conundrum/wasm#build:ts")
	WGGN("@conundrum/webAssets#build:website") --> ETQY("___ROOT___")
	RDVF("@fluster/lezer#build") --> ETQY("___ROOT___")
	PVEJ("@fluster/lezer#build:website") --> RDVF("@fluster/lezer#build")
	CHNJ("@fluster/wasm#build:website") --> ETQY("___ROOT___")
	SXVB("@fluster/website#build:website") --> MLKN("@conundrum/ts#build:website")
	SXVB("@fluster/website#build:website") --> NDRI("@conundrum/wasm#build:website")
	SXVB("@fluster/website#build:website") --> WGGN("@conundrum/webAssets#build:website")
	SXVB("@fluster/website#build:website") --> CHNJ("@fluster/wasm#build:website")
	SXVB("@fluster/website#build:website") --> VVSC("@fluster/webview_utils#build:website")
	WAGD("@fluster/webview_utils#build:tailwind") --> ETQY("___ROOT___")
	VVSC("@fluster/webview_utils#build:website") --> KEFT("@conundrum/ts#build")
	VVSC("@fluster/webview_utils#build:website") --> PVEJ("@fluster/lezer#build:website")
