import { BibtexEditorWebviewActions, BibtexEditorWebviewEvents, BibtexEditorWebviewLocalStorageKeys, DictionaryWebviewActions, DictionaryWebviewEvents, NoteDetailWebviewActions, NoteDetailWebviewEvents, SplitviewEditorWebviewActions, SplitviewEditorWebviewEvents, SplitviewEditorWebviewLocalStorageKeys } from "@/code_gen/typeshare/fluster_core_utilities";

export type AnyWebviewAction = NoteDetailWebviewActions | SplitviewEditorWebviewActions | BibtexEditorWebviewActions | DictionaryWebviewActions
export type AnyWebviewEvent = NoteDetailWebviewEvents | SplitviewEditorWebviewEvents | BibtexEditorWebviewEvents | DictionaryWebviewEvents
export type AnyWebviewStorageKey = SplitviewEditorWebviewLocalStorageKeys | BibtexEditorWebviewLocalStorageKeys
