
[profile.default]
success-output = "immediate"
failure-output = "immediate"

# -- Initialize Database first
[[profiles.default.overrides]]
filter = "vector::database::initialize_db::initialize_db::initializes_db"
priority = 100

