use winnow::error::ErrMode;

use crate::lang::runtime::state::{
    conundrum_error::ConundrumError,
    conundrum_error_variant::{ConundrumErrorVariant, ConundrumModalResult},
};

pub fn code_block_lang_match(s: &str) -> ConundrumModalResult<String> {
    let _s = s.to_lowercase().replace("_", "-");
    match _s.as_str() {
        "text" => Some("Plain Text"),
        "python" => Some("Python"),
        "py" => Some("Python"),
        "css" => Some("CSS"),
        "go" => Some("Go"),
        "js" => Some("JavaScript"),
        "erlang" => Some("Erlang"),
        "c#" => Some("C#"),
        "c++" => Some("C++"),
        "c" => Some("C"),
        "asp" => Some("ASP"),
        "batch file" => Some("Batch File"),
        "nant build file" => Some("NAnt Build File"),
        "clojure" => Some("Clojure"),
        "d" => Some("D"),
        "diff" => Some("Diff"),
        "graphviz-dot" => Some("Graphviz (DOT)"),
        "graphviz" => Some("Graphviz (DOT)"),
        "groovy" => Some("Groovy"),
        "html" => Some("HTML"),
        "haskell" => Some("Haskell"),
        "literate-haskell" => Some("Literate Haskell"),
        "java-server-page" => Some("Java Server Page (JSP)"),
        "java" => Some("Java"),
        "javadoc" => Some("JavaDoc"),
        "java-properties" => Some("Java Properties"),
        "json" => Some("JSON"),
        "javascript" => Some("JavaScript"),
        "regular-expressions-js" => Some("Regular Expressions (Javascript)"),
        "regex-js" => Some("Regular Expressions (Javascript)"),
        "bibtex" => Some("BibTeX"),
        "latex-log" => Some("LaTeX Log"),
        "latex" => Some("LaTeX"),
        "tex" => Some("TeX"),
        "lisp" => Some("Lisp"),
        "lua" => Some("Lua"),
        "make output" => Some("Make Output"),
        "makefile" => Some("Makefile"),
        "markdown" => Some("Markdown"),
        "multimarkdown" => Some("MultiMarkdown"),
        "matlab" => Some("MATLAB"),
        "ocaml" => Some("OCaml"),
        "ocamllex" => Some("OCamllex"),
        "ocamlyacc" => Some("OCamlyacc"),
        "camlp4" => Some("camlp4"),
        "objective-c++" => Some("Objective-C++"),
        "objective-c" => Some("Objective-C"),
        "php-source" => Some("PHP Source"),
        "php" => Some("PHP"),
        "pascal" => Some("Pascal"),
        "perl" => Some("Perl"),
        "regular expressions (python)" => Some("Regular Expressions (Python)"),
        "r-console" => Some("R Console"),
        "r" => Some("R"),
        "rd" => Some("Rd (R Documentation)"),
        "html-rails" => Some("HTML (Rails)"),
        "javascript-rails" => Some("JavaScript (Rails)"),
        "ruby-haml" => Some("Ruby Haml"),
        "ruby-on-rails" => Some("Ruby on Rails"),
        "sql-rails" => Some("SQL (Rails)"),
        "regular-expression" => Some("Regular Expression"),
        "regex" => Some("Regular Expression"),
        "restructuredtext" => Some("reStructuredText"),
        "ruby" => Some("Ruby"),
        "cargo-build-results" => Some("Cargo Build Results"),
        "rust" => Some("Rust"),
        "sql" => Some("SQL"),
        "scala" => Some("Scala"),
        "bash" => Some("Bourne Again Shell (bash)"),
        "shell-unix-generic" => Some("Shell-Unix-Generic"),
        "commands-builtin-shell-bash" => Some("commands-builtin-shell-bash"),
        "html-tcl" => Some("HTML (Tcl)"),
        "tcl" => Some("Tcl"),
        "textile" => Some("Textile"),
        "xml" => Some("XML"),
        "yaml" => Some("YAML"),
        _ => None,
    }.map(|s| s.to_string()).ok_or_else(|| {
        println!("Failed to find language");
        ErrMode::Cut(
            ConundrumErrorVariant::InternalParserError(ConundrumError::from_msg_and_details("Invalid language", format!("The `{}` language you requested is not provided by the Conundrum compiler. Since I'm building this while homeless and without internet, it's a challenge to find the precious time on WIFI to integrate more languages, but they are coming... I promise. For now you can see the available languages in the `Code??` docs.", s).as_str()))
        )
    })
}
