#!/bin/bash

branch="$(git rev-parse --abbrev-ref HEAD)"

if [ "$branch" = "master" ] || [ "$branch" = "main" ]; then
    echo "You can't commit directly to $branch branch Einstein..."
    exit 1
fi

just format_package_jsons

git add packages/webview_utils/package.json
git add packages/webviews/*/package.json
