/*
 Generated by typeshare 1.13.3
 */

import Foundation

public enum CDRMConundrumWebEvents: String, Codable {
	/// Useful for things like resizable pains, to more easily emit your own
	/// resize event that Conundrum will handle to update the components
	/// accordingly.
	case manualResize = "cdrm-manual-resize"
	case cdrmContentLoaded = "cdrm-content-loaded"
	case codeblockCopied = "cdrm-codeblock-copy"
	case noteLinkClick = "cdrm-note-id-link-click"
	case copyToClipboard = "cdrm-content-copied"
	case dictionaryEntryLabelClick = "dictionary-entry-click"
	case tocItemClick = "toc-item-click"
	case tagClick = "tag-click"
}
